import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import {WebSocket} from 'ws';
import {startHub} from '../platform/cloud/hub.mjs';
import {runtimeConfig,workerRpc} from '../scripts/runtime.mjs';

test('real native collaboration: concurrent edits, isolation, roles, artifacts and restart', {timeout:240000},async t=>{
  const folder=path.resolve('.runtime/cloud-tests',crypto.randomUUID());let hub=await startHub({port:0,stateDirectory:folder});let endpoint=`http://127.0.0.1:${hub.port}`;
  t.after(async()=>{await hub.close();});
  const clients={};
  const call=async(method,params={},identity)=>{const r=await fetch(`${endpoint}/rpc`,{method:'POST',headers:{'Content-Type':'application/json',...(identity?{Authorization:`Bearer ${clients[identity].token}`}:{})},body:JSON.stringify({method,params})});const data=await r.json();if(!data.ok)throw Object.assign(new Error(data.error.message),data.error);return data.result;};
  await t.test('passwords are hashed and unauthenticated access is denied',async()=>{for(const id of ['owner','editor','viewer','stranger'])clients[id]=await call('cloud.auth.signUp',{email:`${id}-${crypto.randomUUID()}@test.invalid`,name:id,password:crypto.randomBytes(24).toString('base64url')});await assert.rejects(call('cloud.projects'),{code:'AUTH_REQUIRED'});const users=hub.db.prepare('SELECT * FROM users').all();assert.equal(users.length,4);assert.equal(users.every(u=>u.password_hash.length===128&&!('password' in u)),true);});
  let current,roomId,projectId,editorInvite,viewerInvite;
  await t.test('member-only shared native project and one-time role join',async()=>{current=await call('cloud.create',{name:'레지스터 협업 검증',example:'inverter'},'owner');roomId=current.room.id;projectId=current.project.id;editorInvite=await call('cloud.invite',{room_id:roomId,role:'editor'},'owner');viewerInvite=await call('cloud.invite',{room_id:roomId,role:'viewer'},'owner');await call('cloud.join',{token:editorInvite.token},'editor');await call('cloud.join',{token:viewerInvite.token},'viewer');await assert.rejects(call('cloud.open',{id:roomId},'stranger'),{code:'FORBIDDEN'});assert.equal((await call('cloud.projects',{},'stranger')).length,0);await assert.rejects(call('cloud.invite',{room_id:roomId,role:'editor'},'editor'),{code:'FORBIDDEN'});});
  await t.test('publishing a local immutable bundle clones a shared native authority',async()=>{const config=await runtimeConfig();const source=await workerRpc(config,'project.export_bundle',{project_id:projectId,inline:true});assert.equal(source.ok,true,JSON.stringify(source.error));const published=await call('cloud.create',{bundle_base64:source.result.bundle_base64},'owner');assert.notEqual(published.project.id,projectId);assert.equal(published.project.revision,1);const publishedScene=await call('cloud.open',{id:published.room.id},'owner');assert.equal(publishedScene.scene.shapes.length,(await call('cloud.open',{id:roomId},'owner')).scene.shapes.length);});
  const mutate=(command,identity='owner',base=current.project.revision,id=crypto.randomUUID())=>call('cloud.native',{room_id:roomId,method:'layout.apply_command',params:{project_id:projectId,command},base_revision:base,command_id:id},identity);
  let a,b,aID,bID;
  await t.test('simultaneous disjoint geometry commits preserve both revisions',async()=>{const base=current.project.revision;[a,b]=await Promise.all([mutate({type:'add_box',layer_id:current.project.layers.find(l=>l.name==='met1'||l.name==='metal1')?.id||current.project.layers[0].id,box:['400000','400000','401000','401000']},'owner',base),mutate({type:'add_box',layer_id:current.project.layers.find(l=>l.name==='met1'||l.name==='metal1')?.id||current.project.layers[0].id,box:['410000','410000','411000','411000']},'editor',base)]);assert.notEqual(a.revision,b.revision);current=await call('cloud.open',{id:roomId},'owner');assert.equal(current.project.revision,base+2);const added=current.scene.shapes.filter(s=>s.polygon.some(p=>p[0]==='400000'||p[0]==='410000'));assert.equal(added.length,2);[aID,bID]=added.map(s=>s.id);});
  await t.test('overlapping concurrent edits return EDIT_CONFLICT without lost geometry',async()=>{const base=current.project.revision;const outcomes=await Promise.allSettled([mutate({type:'move_shape',id:aID,dx:'5',dy:'0'},'owner',base),mutate({type:'move_shape',id:aID,dx:'10',dy:'0'},'editor',base)]);assert.equal(outcomes.filter(o=>o.status==='fulfilled').length,1);assert.equal(outcomes.find(o=>o.status==='rejected').reason.code,'EDIT_CONFLICT');current=await call('cloud.open',{id:roomId},'owner');assert.equal(current.project.revision,base+1);});
  let replay,replayId,replayBase,replayCommand;
  await t.test('same command retry is exactly once and reuse mismatch is rejected',async()=>{replayId=crypto.randomUUID();replayBase=current.project.revision;replayCommand={type:'move_shape',id:bID,dx:'5',dy:'0'};replay=await mutate(replayCommand,'editor',replayBase,replayId);const second=await mutate(replayCommand,'editor',replayBase,replayId);assert.equal(second.revision,replay.revision);await assert.rejects(mutate({...replayCommand,dx:'15'},'editor',replayBase,replayId),{code:'IDEMPOTENCY_CONFLICT'});current=await call('cloud.open',{id:roomId},'owner');assert.equal(current.project.revision,replayBase+1);});
  await t.test('viewer writes and cross-project run reads are rejected by server',async()=>{await assert.rejects(mutate({type:'delete_shape',id:aID},'viewer'),{code:'READ_ONLY'});const config=await runtimeConfig();const other=await workerRpc(config,'project.create',{name:'separate',example:'mosfet'});const run=await workerRpc(config,'simulation.run',{project_id:other.result.id,analysis:'op'});assert.equal(run.ok,true);await assert.rejects(call('cloud.native',{room_id:roomId,method:'job.status',params:{run_id:run.result.id}},'viewer'),{code:'FORBIDDEN'});});
  const sockets=[];
  t.after(()=>sockets.forEach(s=>s.close()));
  function watch(identity){const ws=new WebSocket(endpoint.replace('http','ws')+'/events');sockets.push(ws);const events=[];ws.on('message',m=>events.push(JSON.parse(m)));ws.on('open',()=>ws.send(JSON.stringify({type:'subscribe',token:clients[identity].token,room_id:roomId,peer_id:identity})));return {ws,events};}
  async function until(check,timeout=20000){const deadline=Date.now()+timeout;while(Date.now()<deadline){if(check())return;await new Promise(r=>setTimeout(r,30));}assert.fail('Realtime event timeout');}
  let ownerStream,editorStream;
  await t.test('authenticated live presence and revision events reach collaborators',async()=>{ownerStream=watch('owner');editorStream=watch('editor');await until(()=>ownerStream.events.some(e=>e.type==='ready')&&editorStream.events.some(e=>e.type==='ready'));editorStream.ws.send(JSON.stringify({type:'presence',selection:aID,cursor:{x:'400005',y:'400000',layer_id:current.project.layers.find(l=>l.name==='met1'||l.name==='metal1')?.id||current.project.layers[0].id}}));await until(()=>ownerStream.events.some(e=>e.type==='presence'&&e.presence.some(p=>p.name==='editor'&&p.cursor?.x==='400005')));const before=current.project.revision;await mutate({type:'move_shape',id:bID,dx:'5',dy:'0'},'owner',before);await until(()=>editorStream.events.some(e=>e.type==='snapshot'&&e.revision===before+1));current=await call('cloud.open',{id:roomId},'owner');});
  let completedRun;
  await t.test('remote ngspice job and its real raw artifact are visible to members only',async()=>{const run=await call('cloud.native',{room_id:roomId,method:'simulation.run',params:{project_id:projectId,analysis:'tran'},base_revision:current.project.revision,command_id:crypto.randomUUID()},'editor');await until(()=>ownerStream.events.some(e=>e.type==='snapshot'),30000);const start=Date.now();while(Date.now()-start<120000){completedRun=await call('cloud.native',{room_id:roomId,method:'job.status',params:{run_id:run.id}},'viewer');if(['completed','failed','canceled'].includes(completedRun.execution_status))break;await new Promise(r=>setTimeout(r,300));}assert.equal(completedRun.execution_status,'completed');assert.equal(completedRun.tool,'ngspice');assert.ok(completedRun.waveforms.length>0);const key=Object.keys(completedRun.artifacts).find(k=>k.includes('raw'))||Object.keys(completedRun.artifacts)[0];const query=new URLSearchParams({room_id:roomId,run_id:run.id,key});const artifact=await fetch(`${endpoint}/artifact?${query}`,{headers:{Authorization:`Bearer ${clients.viewer.token}`}});assert.equal(artifact.status,200);assert.ok((await artifact.arrayBuffer()).byteLength>10);const denied=await fetch(`${endpoint}/artifact?${query}`,{headers:{Authorization:`Bearer ${clients.stranger.token}`}});assert.equal(denied.status,403);});
  await t.test('role removal immediately revokes RPC and live channel',async()=>{await call('cloud.setRole',{room_id:roomId,user_id:clients.editor.user.id,role:'removed'},'owner');await assert.rejects(call('cloud.open',{id:roomId},'editor'),{code:'FORBIDDEN'});await until(()=>editorStream.ws.readyState===WebSocket.CLOSED);});
  await t.test('interrupted server commit reconciles the actual native receipt exactly once',async()=>{for(const stream of sockets)stream.close();const config=await runtimeConfig();const commandId=crypto.randomUUID();const key=roomId+':'+commandId;const base=current.project.revision;const params={project_id:projectId,command:{type:'add_box',layer_id:current.project.layers[0].id,box:['420000','420000','421000','421000']}};const hash=crypto.createHash('sha256').update(JSON.stringify({method:'layout.apply_command',params,base_revision:base})).digest('hex');hub.db.prepare('INSERT INTO commands(id,room_id,user_id,method,hash,base_revision,scopes,params,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(key,roomId,clients.owner.user.id,'layout.apply_command',hash,base,'[]',JSON.stringify(params),'processing',Date.now());const native=await workerRpc(config,'layout.apply_command',{...params,expected_revision:base,command_id:key});assert.equal(native.ok,true,JSON.stringify(native.error));await hub.close();hub=await startHub({port:0,stateDirectory:folder});endpoint='http://127.0.0.1:'+hub.port;const reconciled=await call('cloud.native',{room_id:roomId,method:'layout.apply_command',params,base_revision:base,command_id:commandId},'owner');assert.equal(reconciled.revision,native.result.revision);assert.equal((await call('cloud.native',{room_id:roomId,method:'layout.apply_command',params,base_revision:base,command_id:commandId},'owner')).revision,reconciled.revision);current=await call('cloud.open',{id:roomId},'owner');assert.equal(current.project.revision,base+1);});
  await t.test('server restart retains account membership project and command receipt',async()=>{for(const s of sockets)s.close();await hub.close();hub=await startHub({port:0,stateDirectory:folder});endpoint=`http://127.0.0.1:${hub.port}`;const reopened=await call('cloud.open',{id:roomId},'owner');assert.equal(reopened.project.id,projectId);assert.equal(reopened.project.revision,current.project.revision);const commands=hub.db.prepare("SELECT count(*) AS n FROM commands WHERE status='completed'").get();assert.ok(commands.n>=5);assert.equal((await call('cloud.members',{room_id:roomId},'owner')).length,2);});
  await fs.mkdir('docs/evidence',{recursive:true});await fs.writeFile('docs/evidence/cloud-integration.json',JSON.stringify({service:'Register collaboration',verified_at:new Date().toISOString(),transport:'HTTP and authenticated WebSocket',backend:'actual KLayout/ngspice worker',cloud_deployment:'not_provisioned',checks:12,project_id:projectId,revision:current.project.revision,run_id:completedRun.id},null,2));
});
