import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,mkdir,readFile,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {assistantRpc,collectEvidence,validateReview,status,review,history} from '../scripts/design-assistant.mjs';

const id='a'.repeat(32),project={id,name:'test',revision:1,cell:'test',pdk_id:'sky130A',runs:[],testbench:{analysis:'tran'}};
const graph={revision:1,devices:[{id:'r1',name:'R1',kind:'resistor',pins:{'+':'IN','-':'OUT'},parameters:{value:1000}}],nets:[{name:'IN',pins:[{device_id:'r1',pin:'+'}]}],issues:[],layout_binding:{status:'not-generated'},scope:'selected cell',limits:[]};
const valid={summary:'실제 근거에 대한 검토입니다.',findings:[{severity:'warning',title:'해석 필요',explanation:'해석 이력이 없습니다.',evidence_ids:['issue:0'],suggested_check:'simulate'}],limitations:['AI 검토는 엔진 검증이 아닙니다.']};
const call=async(_worker,method)=>({ok:true,result:method==='project.snapshot'?structuredClone(project):structuredClone(graph)});
async function fixture(t,budget=1){const workspace=await mkdtemp(path.join(os.tmpdir(),'register-assistant-'));t.after(()=>rm(workspace,{recursive:true,force:true}));await mkdir(path.join(workspace,'.runtime/assistant'),{recursive:true});await writeFile(path.join(workspace,'.runtime/assistant/settings.json'),JSON.stringify({budget_usd:budget}));await writeFile(path.join(workspace,'.env.local'),'OPENAI_API_KEY=fixture-not-a-real-key\n');return {workspace};}
const args=async(worker,provider='openai')=>({project_id:id,expected_revision:1,provider,approved:true,evidence_hash:(await collectEvidence(worker,{project_id:id,expected_revision:1},call)).fingerprint});
const okResponse=()=>new Response(JSON.stringify({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(valid)}]}],usage:{input_tokens:100,output_tokens:100}}));

test('evidence is deterministic, bounded and marks unexecuted checks',async t=>{const w=await fixture(t),e=await collectEvidence(w,{project_id:id,expected_revision:1},call);assert.equal(e.fingerprint,(await collectEvidence(w,{project_id:id,expected_revision:1},call)).fingerprint);assert.equal(e.issues.filter(i=>i.code==='NOT_VERIFIED').length,4);assert.equal(JSON.stringify(e).includes('fixture-not-a-real-key'),false);assert.equal(e.connectivity.layout_status,'not-generated');});
test('project and graph revisions must agree',async t=>{const w=await fixture(t);await assert.rejects(collectEvidence(w,{project_id:id,expected_revision:2},call),{code:'REVISION_CONFLICT'});await assert.rejects(collectEvidence(w,{project_id:id,expected_revision:1},async(w,m)=>m==='design.connectivity'?{ok:true,result:{...graph,revision:2}}:call(w,m)),{code:'REVISION_CONFLICT'});});
test('unknown evidence and unsupported action fields are rejected',()=>{const e={evidence_ids:['issue:0']};assert.equal(validateReview(valid,e).findings.length,1);assert.throws(()=>validateReview({...valid,findings:[{...valid.findings[0],evidence_ids:['invented']}]},e),{code:'AI_EVIDENCE'});assert.throws(()=>validateReview({...valid,command:'delete'},e));});
test('approval and original evidence hash are mandatory before provider calls',async t=>{const w=await fixture(t);let sends=0;const options={call,fetcher:async()=>{sends++;return okResponse();}},a=await args(w);await assert.rejects(review(w,{...a,approved:false},options));await assert.rejects(review(w,{...a,evidence_hash:'f'.repeat(64)},options),{code:'STALE_AI_EVIDENCE'});assert.equal(sends,0);});
test('zero budget prevents a paid request',async t=>{const w=await fixture(t,0);let sends=0;await assert.rejects(review(w,await args(w),{call,fetcher:async()=>{sends++;return okResponse();}}),{code:'AI_BUDGET'});assert.equal(sends,0);});
test('OpenAI request is bounded, private, strict and has no tools',async t=>{const w=await fixture(t);const result=await review(w,await args(w),{call,fetcher:async(url,init)=>{assert.equal(url,'https://api.openai.com/v1/responses');const b=JSON.parse(init.body);assert.equal(b.store,false);assert.equal(b.service_tier,'default');assert.equal(b.max_output_tokens,4096);assert.equal(b.text.format.strict,true);assert.equal(b.tools,undefined);assert.equal(b.input.some(i=>i.content.includes('fixture-not-a-real-key')),false);return okResponse();}});assert.equal(result.advisory_only,true);assert.equal(result.freshness,'current');assert.ok(result.budget_reservation.reserved_usd>0);const saved=JSON.parse(await readFile(path.join(w.workspace,'.runtime/assistant/reviews',result.id+'.json')));assert.equal(saved.advisory_only,true);assert.equal(JSON.stringify(saved).includes('fixture-not-a-real-key'),false);});
test('HTTP failure keeps the reservation and does not retry',async t=>{const w=await fixture(t);let sends=0;await assert.rejects(review(w,await args(w),{call,fetcher:async()=>{sends++;return new Response('provider secret body',{status:429});}}),{code:'AI_PROVIDER_ERROR'});assert.equal(sends,1);const ledger=JSON.parse(await readFile(path.join(w.workspace,'.runtime/assistant/budget.json')));assert.ok(ledger.reserved_usd>0);assert.equal(ledger.requests.length,1);});
test('exhausted budget is blocked before fetch',async t=>{const w=await fixture(t);await writeFile(path.join(w.workspace,'.runtime/assistant/budget.json'),JSON.stringify({reserved_usd:1,requests:[]}));let sends=0;await assert.rejects(review(w,await args(w),{call,fetcher:async()=>{sends++;return okResponse();}}),{code:'AI_BUDGET'});assert.equal(sends,0);});
test('concurrent reservations cannot overspend',async t=>{const w=await fixture(t,.007),a=await args(w);const rs=await Promise.allSettled(Array.from({length:6},()=>review(w,a,{call,fetcher:async()=>okResponse()})));const ledger=JSON.parse(await readFile(path.join(w.workspace,'.runtime/assistant/budget.json')));assert.ok(ledger.reserved_usd<=.007);assert.ok(rs.some(r=>r.status==='rejected'));});
test('late response is marked stale if design changes',async t=>{const w=await fixture(t);let n=0;const changed=async(w,m)=>{if(m==='project.snapshot'&&++n===2)return {ok:true,result:{...project,revision:2}};return call(w,m);};const r=await review(w,await args(w),{call:changed,fetcher:async()=>okResponse()});assert.equal(r.freshness,'stale');});
test('status does not call OpenAI and exposes no key',async t=>{const w=await fixture(t);const s=await status(w.workspace,{fetcher:async(url)=>{assert.match(url,/^http:\/\/127\.0\.0\.1:/);return new Response(JSON.stringify({models:[]}));}});assert.equal(s.openai.configured,true);assert.equal(s.automatic_calls,false);assert.equal(JSON.stringify(s).includes('fixture-not-a-real-key'),false);});
test('non-loopback Ollama configuration is rejected',async t=>{const w=await fixture(t);await writeFile(path.join(w.workspace,'.runtime/assistant/settings.json'),JSON.stringify({ollama_url:'https://untrusted.example'}));await assert.rejects(status(w.workspace),{code:'AI_ENDPOINT'});});
test('Ollama uses the same evidence/schema gate without spending API budget',async t=>{const w=await fixture(t),a=await args(w,'ollama');const result=await review(w,{...a,model:'local-fixture'},{call,fetcher:async(url,init)=>{if(url.endsWith('/api/tags'))return new Response(JSON.stringify({models:[{name:'local-fixture'}]}));assert.match(url,/^http:\/\/127\.0\.0\.1:/);const b=JSON.parse(init.body);assert.equal(b.format.type,'object');assert.equal(b.stream,false);return new Response(JSON.stringify({message:{content:JSON.stringify(valid)},prompt_eval_count:5,eval_count:10}));}});assert.equal(result.budget_reservation,null);});
test('unrecognized method cannot execute arbitrary work',async t=>{const w=await fixture(t);const r=await assistantRpc(w,'assistant.execute_shell',{},{});assert.equal(r.ok,false);assert.equal(r.error.code,'UNSUPPORTED_METHOD');});
test('saved advice can be loaded without paid requests; new engine evidence marks it stale',async t=>{const w=await fixture(t);const r=await review(w,await args(w),{call,fetcher:async()=>okResponse()});const original=await history(w,{project_id:id,expected_revision:1},call);assert.equal(original[0].id,r.id);assert.equal(original[0].freshness,'current');const changed=async(w,m)=>m==='project.snapshot'?{ok:true,result:{...project,runs:[{id:'run1',revision:1,kind:'drc',execution_status:'completed',analysis_result:'pass',freshness:'current'}]}}:call(w,m);assert.equal((await history(w,{project_id:id,expected_revision:1},changed))[0].freshness,'stale');});
