import test from 'node:test';
import assert from 'node:assert/strict';
import {desktopDiagnostics,normalizeMount} from '../scripts/desktop-diagnostics.mjs';
const token='not-a-real-credential'.padEnd(40,'x');
const base={workspace:'D:\\Design',platform:'win32',arch:'x64',check:async()=>{},read:async()=>JSON.stringify({url:'http://127.0.0.1:18765',token})};
function runner({type='linux',mount='/run/desktop/mnt/host/d/Design',missing=false}={}){const calls=[];return {calls,run:async args=>{calls.push(args);return args[0]==='--version'?{ok:!missing,stdout:'Docker test version'}:args[0]==='info'?{ok:true,stdout:type}:{ok:true,stdout:mount};}};}
test('missing Docker stays read-only and supplies offline viewer/recovery instructions',async()=>{const r=runner({missing:true});let fetches=0;const v=await desktopDiagnostics({...base,...r,fetchImpl:async()=>{fetches++;throw Error('must not call');}});assert.equal(fetches,0);assert.equal(v.engine_ready,false);assert.equal(v.items.find(i=>i.id==='docker').status,'missing');assert.deepEqual(r.calls,[['--version']]);assert.equal(v.read_only,true);assert(!JSON.stringify(v).includes(token));});
test('Windows container mode is blocked before engine requests',async()=>{const r=runner({type:'windows'});const v=await desktopDiagnostics({...base,...r,fetchImpl:async()=>{throw Error('must not call');}});assert.equal(v.items.find(i=>i.id==='docker-engine').status,'blocked');assert.equal(v.engine_ready,false);assert.equal(r.calls.length,2);});
test('foreign workspace is never started, stopped or contacted',async()=>{const r=runner({mount:'D:\\Other'});const v=await desktopDiagnostics({...base,...r,fetchImpl:async()=>{throw Error('must not call');}});assert.equal(v.items.find(i=>i.id==='container').status,'blocked');assert.equal(v.engine_ready,false);assert(r.calls.every(args=>['--version','info','inspect'].includes(args[0])));});
test('authenticated current workspace is ready; token is used only in the request',async()=>{const r=runner();const v=await desktopDiagnostics({...base,...r,fetchImpl:async(url,options)=>{assert.equal(url,'http://127.0.0.1:18765/rpc');assert.equal(options.headers['X-MOS-Token'],token);assert.deepEqual(JSON.parse(options.body),{method:'pdk.capabilities',params:{}});return {ok:true,status:200,json:async()=>({ok:true,result:{available:true}})};}});assert.equal(v.engine_ready,true);assert(!JSON.stringify(v).includes(token));});
test('an authentication mismatch is reported without leaking session data',async()=>{const r=runner();const v=await desktopDiagnostics({...base,...r,fetchImpl:async()=>({ok:false,status:401})});assert.equal(v.engine_ready,false);assert.equal(v.items.find(i=>i.id==='session').status,'blocked');assert(!JSON.stringify(v).includes(token));});
test('unsafe or malformed persisted URLs are never fetched',async()=>{for(const url of ['https://example.com','http://127.0.0.1/secret','http://name:password@127.0.0.1','http://127.0.0.1/?token=secret']){const r=runner();const v=await desktopDiagnostics({...base,...r,read:async()=>JSON.stringify({url,token}),fetchImpl:async()=>{throw Error('must not call');}});assert.equal(v.engine_ready,false);assert.equal(v.items.find(i=>i.id==='session').status,'pending');}});
test('mount matching respects Unix case and Docker Desktop Windows drive paths',()=>{assert.equal(normalizeMount('D:\\Design\\'),normalizeMount('/run/desktop/mnt/host/d/Design'));assert.notEqual(normalizeMount('/home/design'),normalizeMount('/home/Design'));});
