import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import {startHub} from '../platform/cloud/hub.mjs';
import {runtimeConfig,workerRpc} from '../scripts/runtime.mjs';

test('integrated PVT and exact route transactions preserve shared project boundaries',{timeout:150000},async t=>{
  const hub=await startHub({port:0,stateDirectory:path.resolve('.runtime/integrated-cloud',crypto.randomUUID())});t.after(()=>hub.close());
  const url=`http://127.0.0.1:${hub.port}`,users={},checks=[],config=await runtimeConfig();
  const call=async(method,params={},who='owner')=>{const data=await fetch(`${url}/rpc`,{method:'POST',headers:{'Content-Type':'application/json',...(users[who]?{Authorization:`Bearer ${users[who].token}`}:{})},body:JSON.stringify({method,params})}).then(r=>r.json());if(!data.ok)throw Object.assign(new Error(data.error.message),data.error);return data.result;};
  for(const who of ['owner','editor','viewer'])users[who]=await call('cloud.auth.signUp',{email:`${who}-${crypto.randomUUID()}@test.invalid`,name:who,password:crypto.randomBytes(24).toString('base64url')},who);
  let shared=await call('cloud.create',{name:'Actual integrated PVT and routing',example:'mosfet'});
  const other=await call('cloud.create',{name:'Independent design isolation',example:'mosfet'});
  for(const role of ['editor','viewer']){const invite=await call('cloud.invite',{room_id:shared.room.id,role});await call('cloud.join',{token:invite.token},role);}
  const native=(method,params={},who='editor',base=shared.project.revision,cid=crypto.randomUUID(),room=shared.room.id,pid=shared.project.id)=>call('cloud.native',{room_id:room,method,params:{...params,project_id:pid},base_revision:base,command_id:cid},who);
  const catalog=await native('design.catalog',{},'viewer');assert(catalog.templates.length>=4);
  const sources=await native('pvt.sources',{},'viewer');assert(sources.bindings.length>0);
  const pvt={analysis:'dc',corners:['tt'],temperatures_C:[27],supplies_V:[1.2,1.8],supply:sources.bindings[0],metrics:[{name:'Id',source:'measurement',key:'Id_max'}],constraints:[{metric:'Id',op:'>=',value:0}],max_parallel:1,wall_time_s:120,point_timeout_s:90};
  const save={expected_revision:shared.project.revision,config:pvt},cid=crypto.randomUUID();
  await assert.rejects(native('pvt.create',save,'viewer'),{code:'READ_ONLY'});
  const study=await native('pvt.create',save,'editor',shared.project.revision,cid);
  assert.equal((await native('pvt.create',save,'editor',shared.project.revision,cid)).id,study.id);
  await assert.rejects(native('pvt.status',{study_id:study.id},'owner',other.project.revision,crypto.randomUUID(),other.room.id,other.project.id),{code:'FORBIDDEN'});
  await assert.rejects(native('pvt.start',{study_id:study.id,expected_revision:shared.project.revision},'viewer'),{code:'READ_ONLY'});
  await assert.rejects(native('design.create_template',{template_id:'rc_lowpass',command_id:crypto.randomUUID()},'owner'),{code:'UNSUPPORTED_METHOD'});
  checks.push('verified source selection, exactly once study save, viewer execution denial, study isolation and explicit local template creation');
  await native('pvt.start',{study_id:study.id,expected_revision:shared.project.revision});
  let completed;const deadline=Date.now()+110000;
  do{completed=await native('pvt.status',{study_id:study.id},'viewer');if(['completed','failed','canceled'].includes(completed.execution_status))break;await new Promise(r=>setTimeout(r,200));}while(Date.now()<deadline);
  assert.equal(completed.execution_status,'completed',JSON.stringify(completed.points));assert.equal(completed.points.length,2);
  for(const point of completed.points){assert.equal(point.execution_status,'completed');assert.equal(point.analysis_result,'pass');assert(Number.isFinite(point.metrics.Id));assert(point.run_id);const run=await native('job.status',{run_id:point.run_id},'viewer');assert.equal(run.project_id,point.project_id);await native('job.logs',{run_id:point.run_id},'viewer');await assert.rejects(native('job.status',{run_id:point.run_id},'owner',other.project.revision,crypto.randomUUID(),other.room.id,other.project.id),{code:'FORBIDDEN'});}
  assert.notEqual(completed.points[0].metrics.Id,completed.points[1].metrics.Id);
  assert.equal((await call('cloud.open',{id:shared.room.id})).project.revision,shared.project.revision);
  const inventory=await workerRpc(config,'project.list');assert(inventory.ok);for(const point of completed.points)assert(!inventory.result.some(p=>p.id===point.project_id));
  checks.push('actual ngspice conditions and distinct currents, immutable parent, room-scoped child job logs, private point inventory');
  const rules=await native('design.routing_rules',{},'viewer');assert.match(rules.fingerprint,/^[a-f0-9]{64}$/);
  const previewInput={layer_id:rules.layers[0].layer_id,start:['50000','50000'],end:['52000','52000'],width:'200',net:'D',order:'x-first'};
  const preview=await native('design.route_preview',previewInput,'viewer');assert.equal(preview.valid,true,JSON.stringify(preview));
  const base=shared.project.revision,routeCid=crypto.randomUUID(),apply={expected_revision:base,preview:previewInput,preview_hash:preview.preview_hash,rule_fingerprint:rules.fingerprint};
  await assert.rejects(native('design.route_apply',apply,'viewer',base),{code:'READ_ONLY'});
  const changed=await native('design.route_apply',apply,'editor',base,routeCid);assert.equal(changed.revision,base+1);
  assert.equal((await native('design.route_apply',apply,'editor',base,routeCid)).revision,changed.revision);
  await assert.rejects(native('design.route_apply',apply,'owner',base),{code:'EDIT_CONFLICT'});
  shared=await call('cloud.open',{id:shared.room.id});assert.equal(shared.project.revision,base+1);
  assert.equal((await native('pvt.status',{study_id:study.id},'viewer')).freshness,'stale');
  const graph=await native('design.connectivity',{},'viewer');assert(graph.nets.length>0);assert.equal(graph.revision,shared.project.revision);
  checks.push('actual rule resource fingerprint and route preview, exactly once revision, viewer/stale protection, result freshness and actual pin-net graph');
  const privateCall=await workerRpc(config,'simulation.run',{project_id:shared.project.id,_pvt:true});assert.equal(privateCall.ok,false);assert.equal(privateCall.error.code,'PRIVATE_PARAMETER');
  checks.push('private execution markers cannot be supplied through public worker RPC');
  const created=await workerRpc(config,'design.create_template',{template_id:'rc_lowpass',name:'Actual local circuit shared as immutable bundle',command_id:crypto.randomUUID()});assert(created.ok,created.error?.message);
  const exported=await workerRpc(config,'project.export_bundle',{project_id:created.result.id,inline:true});assert(exported.ok,exported.error?.message);
  const sharedTemplate=await call('cloud.create',{name:'Shared connected RC template',bundle_base64:exported.result.bundle_base64});
  assert(sharedTemplate.project.design_template);assert.notEqual(sharedTemplate.project.id,created.result.id);
  const templateSources=await native('pvt.sources',{},'owner',sharedTemplate.project.revision,crypto.randomUUID(),sharedTemplate.room.id,sharedTemplate.project.id);
  assert.deepEqual(templateSources.bindings,[{kind:'testbench',source_names:['VIN']}]);assert.deepEqual(templateSources.analyses,['tran']);
  checks.push('actual locally created circuit bundle shares as a separate connected project with verified template PVT stimulus');
  await fs.writeFile('docs/evidence/integrated-cloud.json',JSON.stringify({checked_at:new Date().toISOString(),checks,project_id:shared.project.id,study_id:study.id,points:completed.points.map(p=>({condition:p.condition,run_id:p.run_id,metrics:p.metrics,analysis_result:p.analysis_result})),actual_engine:'ngspice',revision:shared.project.revision,pdk_rule_fingerprint:rules.fingerprint,external_hosting:'deferred'},null,2));
});
