import test from 'node:test';import assert from 'node:assert/strict';import path from 'node:path';import fs from 'node:fs/promises';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {createHash,randomUUID} from 'node:crypto';
import {runtimeConfig,workerRpc} from '../scripts/runtime.mjs';
test('real MCP client handshake, native tool boundary, revision and job references',{timeout:150000},async t=>{
  const entry=path.resolve(process.env.REGISTER_MCP_ENTRY||'scripts/mcp.mjs');
  const entryHash=createHash('sha256').update(await fs.readFile(entry)).digest('hex');
  const transport=new StdioClientTransport({command:process.execPath,args:[entry],env:{MOS_WORKSPACE:process.cwd()},stderr:'pipe'});
  const client=new Client({name:'register-verification',version:'1.0.0'});t.after(()=>client.close());await client.connect(transport);
  const tools=await client.listTools();assert.equal(tools.tools.length,41);assert.equal(tools.tools.some(x=>/shell|exec|password|secret|pdk.modify|backend.register|database.register/.test(x.name)),false);
  const invoke=async(name,args={})=>{const r=await client.callTool({name,arguments:args});if(r.isError)throw Object.assign(new Error(r.content[0].text),{result:r});return r.structuredContent.result;};
  const doctor=await invoke('register_doctor');assert.equal(doctor.pdk.available,true);assert.equal(doctor.tools.every(t=>t.available),true);
  const p=await invoke('register_create',{name:'MCP actual native transaction',example:'fixture'});const before=await invoke('register_snapshot',{project_id:p.id,max_shapes:10});
  const changed=await invoke('register_layout_command',{project_id:p.id,expected_revision:p.revision,command_id:'mcp-integrity-one',command:{type:'add_box',layer_id:p.layers[0].id,box:['4000','4000','5000','5000']}});assert.equal(changed.revision,p.revision+1);
  const replay=await invoke('register_layout_command',{project_id:p.id,expected_revision:p.revision,command_id:'mcp-integrity-one',command:{type:'add_box',layer_id:p.layers[0].id,box:['4000','4000','5000','5000']}});assert.equal(replay.revision,changed.revision);
  const after=await invoke('register_snapshot',{project_id:p.id,max_shapes:10});assert.equal(after.scene.shapes.length,before.scene.shapes.length+1);
  await assert.rejects(invoke('register_layout_command',{project_id:p.id,expected_revision:p.revision,command_id:'mcp-stale-reject',command:{type:'undo'}}));
  const bad=await client.callTool({name:'register_layout_command',arguments:{project_id:p.id,expected_revision:changed.revision,command_id:'bad-script',command:{type:'shell',command:'echo unsafe'}}});assert.equal(bad.isError,true);
  const catalogue=await invoke('register_backend_catalog');assert.equal(catalogue.tools.length,18);assert(catalogue.tools.some(tool=>tool.id==='custom_compiler'));
  const validated=await invoke('register_backend_validate',{profile_id:'ngspice-calibration-v1'});assert.equal(validated.valid,true);
  const configured=await invoke('register_backend_configure',{project_id:p.id,expected_revision:changed.revision,command_id:'mcp-backend-configure',settings:{profile_id:'ngspice-calibration-v1',profile_hash:validated.fingerprint,operation:'simulation',top_cell:changed.cell,parameters:{}}});
  let run=await invoke('register_backend_run',{project_id:p.id,expected_revision:configured.revision,command_id:'mcp-native-calibration'});
  const deadline=Date.now()+20000;while(['queued','running'].includes(run.execution_status)&&Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,100));run=await invoke('register_job',{run_id:run.id});}
  assert.equal(run.execution_status,'completed',run.message);assert.equal(run.analysis_result,'pass',run.message);assert.equal(run.tool,'ngspice');assert.deepEqual(run.current_flow.branches.map(branch=>branch.values_A[0]),[-.001,.001]);
  const sourceId=`mcp_public_${randomUUID().replaceAll('-','')}`;
  const registered=await workerRpc(await runtimeConfig(),'database.register',{manifest:{schema_version:1,id:sourceId,name:'MCP public KLayout calibration',adapter:'klayout-file',layout_file:'/workspace/examples/sky130/wire.gds',library:'wire',view:'layout',layer_map:[]}});
  assert.equal(registered.ok,true,registered.error?.message);
  const sources=await invoke('register_database_sources');assert(sources.sources.some(source=>source.id===sourceId));
  assert(sources.catalog.adapters.some(adapter=>adapter.id==='cadence-skill'));
  const probe=await invoke('register_database_probe',{source_id:sourceId});assert.equal(probe.vendor_execution_verified,false);
  const cells=await invoke('register_database_cells',{source_id:sourceId});assert(cells.cells.length>0);
  const read=await invoke('register_database_read',{source_id:sourceId,cell:cells.cells[0].cell,view:cells.cells[0].view});assert.equal(read.can_import,true);assert.equal(read.vendor_execution_verified,false);
  const imported=await invoke('register_database_import',{project_id:p.id,read_id:read.id,expected_revision:configured.revision,command_id:`mcp-import-${randomUUID()}`});assert.equal(imported.project.revision,configured.revision+1);
  const scene=await invoke('register_snapshot',{project_id:p.id,max_shapes:100});assert(scene.scene.shapes.length>0);
  const designCatalog=await invoke('register_design_catalog');assert(designCatalog.templates.length>=4);
  const starterCatalog=await invoke('register_semiconductor_catalog');assert.equal(starterCatalog.presets.length,8);assert.equal(starterCatalog.technologies.filter(item=>item.execution_available).length,1);
  const starterCommand=randomUUID();const starter=await invoke('register_semiconductor_start',{preset_id:'signal_filter',name:'MCP semiconductor preset',command_id:starterCommand});
  const starterReplay=await invoke('register_semiconductor_start',{preset_id:'signal_filter',name:'MCP semiconductor preset',command_id:starterCommand});assert.equal(starterReplay.id,starter.id);assert.equal(starter.testbench.analysis,'tran');assert.equal(starter.semiconductor_starter.id,'signal_filter');
  const mos=await invoke('register_create',{name:'MCP immutable PVT',example:'mosfet'});
  const bindings=await invoke('register_pvt_sources',{project_id:mos.id});assert(bindings.bindings.length>0);
  let pvt=await invoke('register_pvt_create',{project_id:mos.id,expected_revision:mos.revision,command_id:randomUUID(),config:{analysis:'dc',corners:['tt'],temperatures_C:[27],supplies_V:[1.8],supply:bindings.bindings[0],metrics:[{name:'Id',source:'measurement',key:'Id_max'}],max_parallel:1}});
  const studyId=pvt.id;assert.equal(pvt.points.length,1);
  await invoke('register_pvt_start',{project_id:mos.id,study_id:studyId,expected_revision:mos.revision,command_id:randomUUID()});
  const pvtDeadline=Date.now()+75000;do{pvt=await invoke('register_pvt_study',{project_id:mos.id,study_id:studyId});if(['completed','failed','canceled'].includes(pvt.execution_status))break;await new Promise(r=>setTimeout(r,200));}while(Date.now()<pvtDeadline);
  assert.equal(pvt.execution_status,'completed',JSON.stringify(pvt.points));assert.equal(pvt.points[0].analysis_result,'pass');assert(Number.isFinite(pvt.points[0].metrics.Id));
  assert.equal((await invoke('register_snapshot',{project_id:mos.id,max_shapes:100})).project.revision,mos.revision);
  const routing=await invoke('register_route_rules',{project_id:mos.id});assert(routing.resources.length>0);
  const route={layer_id:routing.layers[0].layer_id,start:['50000','50000'],end:['52000','52000'],width:'200',net:'D'};
  const routePreview=await invoke('register_route_preview',{project_id:mos.id,...route});assert.equal(routePreview.valid,true);
  const search=await invoke('register_route_search',{project_id:mos.id,...route});assert.equal(search.preview.valid,true);assert.equal(search.project_id,mos.id);assert(search.searched_candidates>0);
  const routed=await invoke('register_route_apply',{project_id:mos.id,expected_revision:mos.revision,command_id:randomUUID(),preview:route,preview_hash:routePreview.preview_hash,rule_fingerprint:routing.fingerprint});assert.equal(routed.revision,mos.revision+1);
  assert.equal((await invoke('register_pvt_study',{project_id:mos.id,study_id:studyId})).freshness,'stale');
  const connections=await invoke('register_connectivity',{project_id:mos.id});assert(connections.nets.length>0);
  const malicious=await client.callTool({name:'register_pvt_create',arguments:{project_id:mos.id,expected_revision:routed.revision,command_id:randomUUID(),config:{analysis:'op',corners:['tt'],temperatures_C:[27],supplies_V:[1.8],supply:{kind:'testbench',source_names:['VD\n.control']},metrics:[{name:'Id',source:'measurement',key:'Id'}]}}});assert.equal(malicious.isError,true);
  const templates=await invoke('register_design_template',{template_id:designCatalog.templates[0].id,name:'MCP connected circuit template',command_id:randomUUID()});assert(templates.design_template);assert.equal((await invoke('register_connectivity',{project_id:templates.id})).issues.some(issue=>issue.severity==='error'),false);
  await fs.writeFile('docs/evidence/mcp-integration.json',JSON.stringify({checked_at:new Date().toISOString(),entry_path:entry,entry_sha256:entryHash,tools:tools.tools.map(t=>t.name),actual_worker:true,project_id:p.id,revision:imported.project.revision,checks:21,actual_pvt:{study_id:studyId,run_id:pvt.points[0].run_id,metrics:pvt.points[0].metrics,parent_immutable:true,stale_after_edit:true},actual_route:{revision:routed.revision,rule_fingerprint:routing.fingerprint,preview_hash:routePreview.preview_hash},actual_template:{project_id:templates.id,template:templates.design_template},actual_native_database:{adapter:'klayout-file',read_id:read.id,graph_sha256:read.graph_sha256,vendor_execution_verified:false},actual_native_backend_calibration:{run_id:run.id,source:run.tool,signed_A:run.current_flow.branches.map(branch=>branch.values_A[0]),vendor_execution_verified:false}},null,2));
});
