import test from 'node:test';
import assert from 'node:assert/strict';
import type {Project,Run} from '../packages/contracts/src/index';
import {executeValidation,validationRows,stageOf} from '../packages/ui/src/validation';
const project={id:'p',revision:1,pdk_id:'sky130A',runs:[],testbench:{analysis:'tran',supply_V:1.8}} as unknown as Project;
const run=(kind='simulation',extra:Partial<Run>={}):Run=>({id:'r',project_id:'p',revision:1,kind,execution_status:'completed',analysis_result:'pass',freshness:'current',analysis_stage:kind==='simulation'?'pre-layout':undefined,...extra});
test('stale and imported evidence cannot certify a current revision',()=>{const p={...project,runs:[run('drc',{freshness:'stale'}),run('lvs',{workflow:'imported-results'}),run('pex',{revision:2}),run()]};const rows=validationRows(p);assert.equal(rows.filter(r=>r.passed).length,1);assert(rows.find(r=>r.id==='drc')?.stale);});
test('failed post-layout jobs remain post-layout even without measurements',()=>{assert.equal(stageOf(run('simulation',{analysis_stage:'post-layout',execution_status:'failed',analysis_result:'unknown'})),'post');assert.equal(stageOf(run('simulation',{analysis_stage:undefined,measurements:undefined})),null);});
function transport({fail='',revAt=Infinity,active=false}={}){const calls:{method:string;params:Record<string,unknown>}[]=[];let snapshots=0;return {calls,call:async<T>(method:string,params:Record<string,unknown>={}):Promise<T>=>{calls.push({method,params});if(method==='project.snapshot')return {...project,revision:++snapshots>=revAt?2:1,runs:active?[run('drc',{execution_status:'running'})]:[]} as T;const kind=method==='simulation.run'?'simulation':method.includes('drc')?'drc':method.includes('lvs')?'lvs':'pex';return run(kind,{id:String(calls.length),analysis_result:kind===fail?'fail':'pass',analysis_stage:kind==='simulation'?(params.post_layout?'post-layout':'pre-layout'):undefined}) as T;}};}
test('LVS failure prevents PEX and post-layout requests',async()=>{const t=transport({fail:'lvs'});await assert.rejects(executeValidation(project,t.call,new AbortController().signal,()=>{},async()=>{},()=> 'test'),/LVS/);assert(!t.calls.some(c=>c.method==='extraction.run_pex'));assert(!t.calls.some(c=>c.params.post_layout===true));});
test('revision changes stop before the next native job',async()=>{const t=transport({revAt:2});await assert.rejects(executeValidation(project,t.call,new AbortController().signal,()=>{},async()=>{},()=> 'test'),/revision/);assert.equal(t.calls.filter(c=>c.method!=='project.snapshot').length,1);});
test('existing jobs block another full verification chain',async()=>{const t=transport({active:true});await assert.rejects(executeValidation(project,t.call,new AbortController().signal,()=>{}),/기존 작업/);assert.equal(t.calls.length,1);});
test('canceling the chain preserves received jobs and starts no remaining stages',async()=>{const t=transport(),controller=new AbortController();let received=0;await executeValidation(project,t.call,controller.signal,()=>{received++;controller.abort();},async()=>{},()=> 'test');assert.equal(received,1);assert.equal(t.calls.filter(c=>c.method!=='project.snapshot').length,1);});
test('all five native requests pin the revision and preserve testbench conditions',async()=>{const t=transport();await executeValidation(project,t.call,new AbortController().signal,()=>{},async()=>{},()=> 'test');const jobs=t.calls.filter(c=>c.method!=='project.snapshot');assert.equal(jobs.length,5);assert(jobs.every(c=>c.params.expected_revision===1));assert.equal(jobs[0].params.post_layout,false);assert.equal(jobs[4].params.post_layout,true);assert.equal(jobs[4].params.supply_V,1.8);});
