import { useEffect, useMemo, useRef, useState } from 'react';
import type { CurrentFlow, Scene, Waveform } from '@mos/contracts';
import type { ViewerFocus } from './collaboration';
import type { DecimalPoint } from './geometry';
import { bookmarkStatus,compareLoadedScenes,createReviewBookmarks,exportCurrentCsv,exportReviewSnapshot,exportWaveformCsv,measurePoints,parseReviewBookmarks,parseReviewSnapshot,reviewScope,searchShapes,shapeVertices } from './review';
import type { CsvContext,ReviewBookmarks,ReviewSnapshot } from './review';
import './review.css';

export interface DesignReviewPanelProps {scene:Scene|null;selection?:string|null;onSelect?:(id:string|null)=>void;onFocus?:(focus:ViewerFocus)=>void;currentFlow?:CurrentFlow|null;waveforms?:Waveform[];resultContext?:CsvContext;compact?:boolean}
const message=(cause:unknown)=>cause instanceof Error?cause.message:String(cause);
function download(text:string,name:string,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type})),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const scopeText=(scene:Scene)=>{const s=reviewScope(scene);return `${s.kind==='full'?'전체 shape 응답':s.kind==='roi'?'ROI 응답':s.kind==='partial'?'부분 응답':'완전성 미확인'} · 로드 ${s.loaded.toLocaleString()} / ${s.total===null?'전체 수 미확인':s.total.toLocaleString()}`;};

export function DesignReviewPanel({scene,selection=null,onSelect,onFocus,currentFlow,waveforms=[],resultContext,compact=false}:DesignReviewPanelProps){
  const [tab,setTab]=useState<'search'|'ruler'|'bookmarks'|'compare'|'csv'>('search'),[query,setQuery]=useState(''),[field,setField]=useState<'all'|'id'|'net'|'cell'|'layer'>('all');
  const [a,setA]=useState<DecimalPoint>(['0','0']),[b,setB]=useState<DecimalPoint>(['1000','0']),[vertex,setVertex]=useState('0');
  const [bookmarks,setBookmarks]=useState<ReviewBookmarks|null>(null),[name,setName]=useState('선택 도형'),[baseline,setBaseline]=useState<ReviewSnapshot|null>(null);
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[start,setStart]=useState('0'),[end,setEnd]=useState(''),[stride,setStride]=useState('1');
  const focusSequence=useRef(0);const key=scene?`register-review-bookmarks-v1:${scene.project_id}`:null;
  useEffect(()=>{setError('');setNotice('');if(!scene||!key){setBookmarks(null);return;}try{const stored=localStorage.getItem(key);setBookmarks(stored?parseReviewBookmarks(stored,scene):createReviewBookmarks(scene));}catch(cause){setBookmarks(createReviewBookmarks(scene));setNotice(`저장 북마크 비활성화: ${message(cause)} 새 북마크를 저장하면 현재 범위로 갱신됩니다.`);}},[scene,key]);
  const result=useMemo(()=>scene?searchShapes(scene,query,{field,limit:100}):null,[scene,query,field]);
  const selected=scene?.shapes.find(shape=>shape.id===selection),vertices=useMemo(()=>selected?shapeVertices(selected):[],[selected]);
  const measured=useMemo(()=>{if(!scene)return null;try{return {value:measurePoints(a,b,scene.dbu_um),error:''};}catch(cause){return {value:null,error:message(cause)};}},[scene,a,b]);
  const comparison=useMemo(()=>scene&&baseline?compareLoadedScenes(scene,baseline.scene):null,[scene,baseline]);
  const bookmarkState=useMemo(()=>scene&&bookmarks?bookmarkStatus(bookmarks,scene):null,[scene,bookmarks]);
  const act=(fn:()=>void)=>{setError('');try{fn();}catch(cause){setError(message(cause));}};
  const pick=(id:string)=>{if(!scene?.shapes.some(shape=>shape.id===id)){setError('해당 도형이 현재 로드 범위에 없습니다.');return;}onSelect?.(id);onFocus?.({shapeId:id,sequence:++focusSequence.current});};
  const save=(doc:ReviewBookmarks)=>{if(key)localStorage.setItem(key,JSON.stringify(doc));setBookmarks(doc);};
  const addBookmark=(kind:'shape'|'point')=>{if(!scene)return;if(kind==='shape'&&!selected)throw new Error('로드된 도형을 먼저 선택하세요.');if(!name.trim())throw new Error('북마크 이름을 입력하세요.');const next=createReviewBookmarks(scene,[...(bookmarks&&bookmarkState?.active?bookmarks.bookmarks:[]),{id:crypto.randomUUID(),name:name.trim().slice(0,256),...(kind==='shape'?{shape_id:selected!.id}:{point:measurePoints(a,a,scene.dbu_um).a}),saved_at:new Date().toISOString()}]);save(next);setNotice('이 브라우저에 북마크를 저장했습니다. 프로젝트 원본은 변경하지 않습니다.');};
  const readFile=(file:File|undefined,kind:'bookmarks'|'baseline')=>{if(!file||!scene)return;void file.text().then(text=>act(()=>{if(kind==='bookmarks'){save(parseReviewBookmarks(text,scene));setNotice('현재 프로젝트/revision/로드 범위와 일치하는 북마크를 가져왔습니다.');}else{setBaseline(parseReviewSnapshot(text));setNotice('기준 파일의 실제 로드 범위만 비교합니다.');}})).catch(cause=>setError(message(cause)));};
  const range=()=>({start:Number(start),...(end.trim()?{end:Number(end)}:{}),stride:Number(stride)});
  return <section className={`mos-design-review${compact?' compact':''}`} aria-label="설계 검토" data-testid="design-review-panel">
    <header><strong>설계 검토</strong><small>{scene?scopeText(scene):'로드된 레이아웃이 필요합니다.'}</small></header>
    <nav>{[['search','검색'],['ruler','거리'],['bookmarks','북마크'],['compare','비교'],['csv','CSV']].map(([id,label])=><button key={id} type="button" data-testid={`review-tab-${id}`} className={tab===id?'active':''} onClick={()=>setTab(id as typeof tab)}>{label}</button>)}</nav>
    {error&&<p role="alert" className="mos-review-error" data-testid="review-error">{error}</p>}{notice&&<p className="mos-review-note" data-testid="review-notice">{notice}</p>}
    {tab==='search'&&<><div className="mos-review-row"><input aria-label="로드된 도형 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="shape ID / net / cell path"/><select aria-label="검색 필드" value={field} onChange={e=>setField(e.target.value as typeof field)}><option value="all">전체 필드</option><option value="id">Shape ID</option><option value="net">Net</option><option value="cell">Cell path</option><option value="layer">Layer</option></select></div>{result&&<p className="mos-review-note">로드된 {result.scanned.toLocaleString()}개 검사 · 일치 {result.matched.toLocaleString()}개 · 최대 {result.limit}개 표시. 미로드 영역은 검색하지 않습니다.</p>}<div className="mos-review-list" data-testid="review-search-results">{result?.matches.map(shape=><button key={shape.id} onClick={()=>pick(shape.id)} className={selection===shape.id?'selected':''}><strong>{shape.id}</strong><small>{shape.cell_path} · {shape.layer_id} · {shape.net??'net 미지정'}</small></button>)}</div></>}
    {tab==='ruler'&&<>
      <p className="mos-review-note">두 명시적 좌표/꼭짓점 사이의 거리입니다. 도형 사이 최소 clearance나 bbox 간격을 계산하지 않습니다.</p>
      <div className="mos-review-grid">{(['A','B'] as const).map((label,j)=><fieldset key={label}>
        <legend>점 {label} · DBU</legend>{['X','Y'].map((axis,i)=><label key={axis}>{axis}<input aria-label={`점 ${label} ${axis} DBU`} value={(j?b:a)[i]} onChange={e=>{const next=[...(j?b:a)] as DecimalPoint;next[i]=e.target.value;(j?setB:setA)(next);}}/></label>)}
      </fieldset>)}</div>
      {selected&&<div className="mos-review-row"><select aria-label="선택 도형 꼭짓점" value={vertex} onChange={e=>setVertex(e.target.value)}>{vertices.map((v,i)=><option key={i} value={i}>{v.label}: {v.point.join(', ')}</option>)}</select><button onClick={()=>{const p=vertices[Number(vertex)];if(p)setA(p.point);}}>A에 지정</button><button onClick={()=>{const p=vertices[Number(vertex)];if(p)setB(p.point);}}>B에 지정</button></div>}
      {measured?.error&&<p className="mos-review-error">{measured.error}</p>}
      {measured?.value&&<dl data-testid="review-ruler-result"><dt>ΔX / ΔY</dt><dd>{measured.value.dx_dbu} / {measured.value.dy_dbu} DBU · {measured.value.dx_um} / {measured.value.dy_um} µm</dd><dt>Manhattan</dt><dd>{measured.value.manhattan_dbu} DBU · {measured.value.manhattan_um} µm</dd><dt>직선 거리</dt><dd>{measured.value.euclidean_um_exact!==null?`${measured.value.euclidean_dbu_exact} DBU · ${measured.value.euclidean_um_exact} µm (정수 거리)`:`≈ ${measured.value.euclidean_um_approx.toPrecision(8)} µm (근사)`}</dd></dl>}
    </>}
    {tab==='bookmarks'&&<><p className="mos-review-note">프로젝트 ID, revision, 현재 로드 범위와 도형 fingerprint가 맞아야 복원합니다. 브라우저 저장은 로컬 상태입니다.</p><div className="mos-review-row"><input aria-label="북마크 이름" value={name} onChange={e=>setName(e.target.value)}/><button disabled={!selected} onClick={()=>act(()=>addBookmark('shape'))}>선택 도형 저장</button><button disabled={!scene} onClick={()=>act(()=>addBookmark('point'))}>점 A 저장</button></div><div className="mos-review-actions"><button disabled={!bookmarks} onClick={()=>bookmarks&&download(JSON.stringify(bookmarks,null,2),'register-bookmarks.json')}>북마크 JSON 저장</button><label>북마크 JSON 가져오기<input aria-label="북마크 JSON 가져오기" type="file" accept=".json" onChange={e=>{readFile(e.target.files?.[0],'bookmarks');e.target.value='';}}/></label></div><div className="mos-review-list">{bookmarks?.bookmarks.map(item=><div key={item.id}><button disabled={!bookmarkState?.active} onClick={()=>{if(item.shape_id)pick(item.shape_id);if(item.point){setA(item.point);setTab('ruler');}}}><strong>{item.name}</strong><small>{item.shape_id??`DBU ${item.point?.join(', ')}`}</small></button><button aria-label={`${item.name} 북마크 삭제`} onClick={()=>act(()=>save({...bookmarks,bookmarks:bookmarks.bookmarks.filter(b=>b.id!==item.id)}))}>삭제</button></div>)}</div></>}
    {tab==='compare'&&<><p className="mos-review-note">현재 로드된 정수 polygon/holes와 ID/net/cell 메타데이터를 비교합니다. 모델·공정·DRC/LVS·label 전체 검증은 포함하지 않습니다.</p><div className="mos-review-actions"><button disabled={!scene} onClick={()=>act(()=>scene&&download(exportReviewSnapshot(scene),'register-loaded-scene.json'))}>현재 Scene 기준 파일 저장</button><button disabled={!scene} onClick={()=>act(()=>{if(scene)setBaseline(parseReviewSnapshot(exportReviewSnapshot(scene)));})}>현재 Scene을 기준으로</button><label>기준 Scene JSON 가져오기<input aria-label="기준 Scene JSON 가져오기" type="file" accept=".json" onChange={e=>{readFile(e.target.files?.[0],'baseline');e.target.value='';}}/></label></div>{comparison&&<><p data-testid="review-comparison-summary">{comparison.coverage==='full'?'두 전체 shape 응답 비교':comparison.coverage==='roi'?'같은 ROI 비교':comparison.coverage==='incompatible'?'단위 불일치 · 비교 안 함':'로드된 부분 범위 비교'} · 일치 {comparison.unchanged} · 변경 {comparison.changed.length} · 현재에만 로드 {comparison.only_current.length} · 기준에만 로드 {comparison.only_baseline.length}</p>{comparison.notes.map(note=><p className="mos-review-note" key={note}>{note}</p>)}<div className="mos-review-list">{comparison.changed.slice(0,100).map(item=><button key={item.id} onClick={()=>pick(item.id)}><strong>{item.id}</strong><small>{item.geometry?'정수 윤곽 변경 ':''}{item.metadata?'net/cell 메타데이터 변경':''}</small></button>)}{comparison.only_current.slice(0,100).map(id=><button key={id} onClick={()=>pick(id)}><strong>{id}</strong><small>현재 응답에만 로드됨</small></button>)}</div></>}</>}
    {tab==='csv'&&<><p className="mos-review-note">실제 결과에 포함된 샘플과 단위를 저장합니다. 전류 부호·from/to·출처·revision·stale 상태를 함께 기록하며 경로/밀도를 추정하지 않습니다. 최대 250000행.</p><div className="mos-review-row"><label>시작 sample<input aria-label="CSV 시작 sample" value={start} onChange={e=>setStart(e.target.value)}/></label><label>끝 sample (빈 값=마지막)<input aria-label="CSV 끝 sample" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>sample 간격<input aria-label="CSV sample 간격" value={stride} onChange={e=>setStride(e.target.value)}/></label></div><div className="mos-review-actions"><button disabled={!currentFlow} onClick={()=>act(()=>currentFlow&&download(exportCurrentCsv(currentFlow,scene,range()),'register-current-samples.csv','text/csv;charset=utf-8'))}>전류 CSV 저장</button><button disabled={!waveforms.length} onClick={()=>act(()=>download(exportWaveformCsv(waveforms,resultContext,range()),'register-waveform-samples.csv','text/csv;charset=utf-8'))}>파형 CSV 저장</button></div>{currentFlow&&<p className="mos-review-note">전류: {currentFlow.branches.length} branch × {currentFlow.x.length} sample · {currentFlow.source} · r{currentFlow.revision} · {currentFlow.freshness??'freshness 미지정'}</p>}</>}
  </section>;
}
