import type { CurrentFlow, Scene, SceneShape, Waveform } from '@mos/contracts';
import type { DecimalPoint } from './geometry';
import { flowStatus } from './current';

const MAX_SHAPES=100000,MAX_VERTICES=2000000,MAX_TEXT=32*1024*1024,MAX_CSV_ROWS=250000;
const coordinate=(value:unknown)=>{if(typeof value!=='string'||!/^[-]?\d{1,40}$/.test(value))throw new Error('정수 DBU 좌표 문자열이 필요합니다 (최대 40자리).');return BigInt(value);};
const point=(p:unknown):DecimalPoint=>{if(!Array.isArray(p)||p.length!==2)throw new Error('X,Y DBU 한 쌍이 필요합니다.');return [String(coordinate(p[0])),String(coordinate(p[1]))];};
const validUnit=(dbu:number)=>{if(!Number.isFinite(dbu)||dbu<=0||dbu>1000000)throw new Error('유효한 DBU µm 단위가 필요합니다.');};
const string=(value:unknown,max=1024)=>{if(typeof value!=='string'||value.length>max)throw new Error('메타데이터 문자열 길이/형식 오류');return value;};
function safeJson(text:string,max:number):unknown {if(typeof text!=='string'||text.length>max)throw new Error(`JSON 파일 제한은 ${max/1024/1024} MiB입니다.`);const value:unknown=JSON.parse(text),pending:{value:unknown;depth:number}[]=[{value,depth:0}];let objects=0;while(pending.length){const node=pending.pop()!;if(node.depth>64)throw new Error('JSON 중첩 깊이 제한은 64입니다.');if(node.value&&typeof node.value==='object'){if(++objects>3000000)throw new Error('JSON 객체 수 처리 제한');for(const [key,v] of Object.entries(node.value)){if(['__proto__','prototype','constructor'].includes(key))throw new Error('JSON prototype 관련 키는 허용하지 않습니다.');if(v&&typeof v==='object')pending.push({value:v,depth:node.depth+1});}}}return value;}
function scaledDecimal(value:bigint,unit:number){validUnit(unit);const match=/^(\d+)(?:\.(\d+))?(?:e([+-]?\d+))?$/i.exec(String(unit));if(!match)throw new Error('DBU 단위 오류');const digits=match[1]+(match[2]??''),places=(match[2]?.length??0)-Number(match[3]??0);let scaled=value*BigInt(digits);if(places<=0)return String(scaled*10n**BigInt(-places));const sign=scaled<0n?'-':'';if(scaled<0n)scaled=-scaled;const s=String(scaled).padStart(places+1,'0'),decimal=(s.slice(0,-places)+'.'+s.slice(-places)).replace(/\.?0+$/,'');return sign+decimal;}
function sqrtInteger(n:bigint){if(n<2n)return n;let x=1n<<BigInt(Math.ceil(n.toString(2).length/2)),next=(x+n/x)/2n;while(next<x){x=next;next=(x+n/x)/2n;}return x;}
export interface RulerMeasurement { a:DecimalPoint;b:DecimalPoint;dx_dbu:string;dy_dbu:string;manhattan_dbu:string;squared_distance_dbu:string;dx_um:string;dy_um:string;manhattan_um:string;euclidean_um_approx:number;euclidean_dbu_exact:string|null;euclidean_um_exact:string|null }
/** An explicit endpoint ruler, never a polygon minimum-clearance approximation. */
export function measurePoints(a:DecimalPoint,b:DecimalPoint,dbuUm:number):RulerMeasurement {validUnit(dbuUm);a=point(a);b=point(b);const dx=coordinate(b[0])-coordinate(a[0]),dy=coordinate(b[1])-coordinate(a[1]),abs=(v:bigint)=>v<0n?-v:v,manhattan=abs(dx)+abs(dy),squared=dx*dx+dy*dy,root=sqrtInteger(squared),exact=root*root===squared?String(root):null;return {a,b,dx_dbu:String(dx),dy_dbu:String(dy),manhattan_dbu:String(manhattan),squared_distance_dbu:String(squared),dx_um:scaledDecimal(dx,dbuUm),dy_um:scaledDecimal(dy,dbuUm),manhattan_um:scaledDecimal(manhattan,dbuUm),euclidean_um_approx:Math.hypot(Number(dx),Number(dy))*dbuUm,euclidean_dbu_exact:exact,euclidean_um_exact:exact===null?null:scaledDecimal(root,dbuUm)};}
export function shapeVertices(shape:SceneShape):{label:string;point:DecimalPoint}[]{return [...shape.polygon.map((p,i)=>({label:`outer ${i+1}`,point:point(p)})),...(shape.holes??[]).flatMap((ring,j)=>ring.map((p,i)=>({label:`hole ${j+1} · ${i+1}`,point:point(p)})))];}
export interface ReviewScope { kind:'full'|'roi'|'partial'|'unknown';loaded:number;total:number|null;bounds_filter:[string,string,string,string]|null;complete_within_scope:boolean }
export function reviewScope(scene:Scene):ReviewScope {const bounds=scene.bounds_filter?.map(v=>String(coordinate(v))) as ReviewScope['bounds_filter']??null,total=Number.isSafeInteger(scene.total_shape_count)&&scene.total_shape_count!>=0?scene.total_shape_count!:null,loaded=scene.shapes.length;const complete=scene.truncated===false&&(!bounds?total===loaded:true);return {kind:bounds?'roi':complete?'full':scene.truncated===true||total!==null&&total>loaded?'partial':'unknown',loaded,total,bounds_filter:bounds,complete_within_scope:complete};}

export interface ShapeSearchResult { id:string;layer_id:string;cell_path:string;net:string|null }
export interface ShapeSearch { matches:ShapeSearchResult[];matched:number;scanned:number;limit:number;scope:ReviewScope }
export function searchShapes(scene:Scene,query:string,options:{field?:'all'|'id'|'net'|'cell'|'layer';limit?:number;scanLimit?:number}={}):ShapeSearch {const q=query.trim().toLocaleLowerCase().slice(0,512),field=options.field??'all',limit=Math.max(1,Math.min(500,Math.floor(options.limit??100))),scanLimit=Math.max(1,Math.min(MAX_SHAPES,Math.floor(options.scanLimit??MAX_SHAPES))),layerNames=new Map(scene.layers.map(l=>[l.id,l.name]));const matches:ShapeSearchResult[]=[];let matched=0,scanned=0;for(const shape of scene.shapes){if(scanned>=scanLimit)break;scanned++;const values=field==='id'?[shape.id]:field==='net'?[shape.net??'']:field==='cell'?[shape.cell_path]:field==='layer'?[shape.layer_id,layerNames.get(shape.layer_id)??'']:[shape.id,shape.net??'',shape.cell_path,shape.layer_id,layerNames.get(shape.layer_id)??''];if(!q||values.some(v=>v.toLocaleLowerCase().includes(q))){matched++;if(matches.length<limit)matches.push({id:shape.id,layer_id:shape.layer_id,cell_path:shape.cell_path,net:shape.net??null});}}return {matches,matched,scanned,limit,scope:reviewScope(scene)};}

function minimumRotation(values:string[]):string[]{const n=values.length;if(!n)return [];let i=0,j=1,k=0;while(i<n&&j<n&&k<n){const a=values[(i+k)%n],b=values[(j+k)%n];if(a===b){k++;continue;}if(a>b){i+=k+1;if(i===j)i++;}else {j+=k+1;if(i===j)j++;}k=0;}const start=Math.min(i,j);return [...values.slice(start),...values.slice(0,start)];}
function canonicalRing(ring:DecimalPoint[]){const values=ring.map(p=>point(p).join(','));if(values.length>1&&values[0]===values.at(-1))values.pop();const forward=minimumRotation(values).join(';'),reverse=minimumRotation([...values].reverse()).join(';');return forward<reverse?forward:reverse;}
export function shapeGeometryKey(shape:SceneShape){return JSON.stringify([shape.layer_id,canonicalRing(shape.polygon),(shape.holes??[]).map(canonicalRing).sort()]);}
const shapeMetadataKey=(s:SceneShape)=>JSON.stringify([s.cell_path,s.net??null,s.device_id??null,s.instance_id??null]);
/** Non-cryptographic local identity guard, never an authorization/signoff hash. */
export function reviewFingerprint(scene:Scene){let a=2166136261,b=0x85ebca6b;const update=(text:string)=>{for(let i=0;i<text.length;i++){const code=text.charCodeAt(i);a=Math.imul(a^code,16777619)>>>0;b=Math.imul(b^code,0x5bd1e995)>>>0;}};update(JSON.stringify([scene.project_id,scene.revision,scene.dbu_um,reviewScope(scene)]));for(const s of [...scene.shapes].sort((a,b)=>a.id.localeCompare(b.id))){update(JSON.stringify([s.id,shapeGeometryKey(s),shapeMetadataKey(s)]));}return 'local-hash64-'+a.toString(16).padStart(8,'0')+b.toString(16).padStart(8,'0');}
export interface SceneComparison { coverage:'full'|'roi'|'loaded-only'|'incompatible';complete:boolean;project_mismatch:boolean;baseline_scope:ReviewScope;current_scope:ReviewScope;only_current:string[];only_baseline:string[];changed:{id:string;geometry:boolean;metadata:boolean}[];unchanged:number;notes:string[] }
export function compareLoadedScenes(current:Scene,baseline:Scene):SceneComparison {const a=reviewScope(current),b=reviewScope(baseline),unitsMatch=current.dbu_um===baseline.dbu_um,full=a.kind==='full'&&b.kind==='full',sameRoi=a.kind==='roi'&&b.kind==='roi'&&JSON.stringify(a.bounds_filter)===JSON.stringify(b.bounds_filter)&&a.complete_within_scope&&b.complete_within_scope;const coverage:SceneComparison['coverage']=!unitsMatch?'incompatible':full?'full':sameRoi?'roi':'loaded-only';const result:SceneComparison={coverage,complete:full&&unitsMatch,project_mismatch:current.project_id!==baseline.project_id,baseline_scope:b,current_scope:a,only_current:[],only_baseline:[],changed:[],unchanged:0,notes:[]};if(!unitsMatch){result.notes.push('DBU 단위가 달라 좌표 비교를 수행하지 않습니다.');return result;}if(!full)result.notes.push(sameRoi?'같은 ROI 안에서 로드된 도형을 비교합니다. 전체 설계 차이를 의미하지 않습니다.':'부분/서로 다른 범위입니다. 한쪽에만 로드된 ID를 추가/삭제 판정으로 해석하지 마세요.');if(result.project_mismatch)result.notes.push('서로 다른 프로젝트의 occurrence ID 비교입니다. ID 체계가 다르면 대응 도형을 찾지 못할 수 있습니다.');const before=new Map(baseline.shapes.map(s=>[s.id,s]));for(const shape of current.shapes){const old=before.get(shape.id);if(!old){result.only_current.push(shape.id);continue;}before.delete(shape.id);const geometry=shapeGeometryKey(old)!==shapeGeometryKey(shape),metadata=shapeMetadataKey(old)!==shapeMetadataKey(shape);if(geometry||metadata)result.changed.push({id:shape.id,geometry,metadata});else result.unchanged++;}result.only_baseline=[...before.keys()];return result;}

function validateScene(value:unknown):Scene {if(!value||typeof value!=='object')throw new Error('Scene 객체 필요');const v=value as Scene;string(v.project_id,512);if(!Number.isSafeInteger(v.revision)||v.revision<0)throw new Error('Scene revision 오류');validUnit(v.dbu_um);if(!Array.isArray(v.layers)||v.layers.length>4096||!Array.isArray(v.shapes)||v.shapes.length>MAX_SHAPES)throw new Error('Scene layer/shape 수 제한');const layers=new Set<string>();for(const l of v.layers){string(l.id);if(layers.has(l.id)||!Array.isArray(l.gds)||l.gds.length!==2||!l.gds.every(n=>Number.isInteger(n)&&n>=0&&n<=65535))throw new Error('Scene layer/GDS 오류');layers.add(l.id);}let vertices=0;const ids=new Set<string>();for(const s of v.shapes){string(s.id);string(s.layer_id);string(s.cell_path);if(ids.has(s.id)||!layers.has(s.layer_id)||!Array.isArray(s.polygon)||s.polygon.length<3)throw new Error('Scene shape ID/layer/ring 오류');ids.add(s.id);if(s.holes!==undefined&&!Array.isArray(s.holes))throw new Error('Scene holes 오류');for(const ring of [s.polygon,...(s.holes??[])]){if(!Array.isArray(ring)||ring.length<3)throw new Error('Scene ring 오류');vertices+=ring.length;if(vertices>MAX_VERTICES)throw new Error('Scene 꼭짓점 처리 제한');for(const p of ring)point(p);}if(s.net!==undefined)string(s.net);}if(v.bounds_filter){if(!Array.isArray(v.bounds_filter)||v.bounds_filter.length!==4)throw new Error('Scene ROI 오류');const [x1,y1,x2,y2]=v.bounds_filter.map(coordinate);if(x1>x2||y1>y2)throw new Error('Scene ROI 범위 오류');}if(v.total_shape_count!==undefined&&(!Number.isSafeInteger(v.total_shape_count)||v.total_shape_count<v.shapes.length))throw new Error('Scene shape count 오류');if(v.truncated!==undefined&&typeof v.truncated!=='boolean')throw new Error('Scene truncated 오류');return v;}
export interface ReviewSnapshot {schema_version:1;format:'register-loaded-scene';captured_at:string;scope:ReviewScope;fingerprint:string;scene:Scene}
export function exportReviewSnapshot(scene:Scene):string {validateScene(scene);const text=JSON.stringify({schema_version:1,format:'register-loaded-scene',captured_at:new Date().toISOString(),scope:reviewScope(scene),fingerprint:reviewFingerprint(scene),scene} satisfies ReviewSnapshot);if(text.length>MAX_TEXT)throw new Error('Scene snapshot 제한은 32 MiB입니다. 더 작은 ROI를 내보내세요.');return text;}
export function parseReviewSnapshot(text:string):ReviewSnapshot {const value=safeJson(text,MAX_TEXT) as ReviewSnapshot;if(!value||value.schema_version!==1||value.format!=='register-loaded-scene')throw new Error('Resistor loaded-scene snapshot 필요');const scene=validateScene(value.scene),fingerprint=reviewFingerprint(scene);if(value.fingerprint!==fingerprint)throw new Error('Scene fingerprint 불일치 · 파일이 변경되었습니다.');return {schema_version:1,format:'register-loaded-scene',captured_at:string(value.captured_at,128),scope:reviewScope(scene),fingerprint,scene};}
export interface ReviewBookmark { id:string;name:string;shape_id?:string;point?:DecimalPoint;saved_at:string }
export interface ReviewBookmarks {schema_version:1;project_id:string;revision:number;scene_fingerprint:string;scope:ReviewScope;bookmarks:ReviewBookmark[]}
export function createReviewBookmarks(scene:Scene,bookmarks:ReviewBookmark[]=[]):ReviewBookmarks {if(bookmarks.length>128)throw new Error('북마크 제한은 128개입니다.');return {schema_version:1,project_id:scene.project_id,revision:scene.revision,scene_fingerprint:reviewFingerprint(scene),scope:reviewScope(scene),bookmarks};}
export function bookmarkStatus(doc:ReviewBookmarks,scene:Scene):{active:boolean;reason:string} {if(doc.project_id!==scene.project_id)return {active:false,reason:'다른 프로젝트의 북마크입니다.'};if(doc.revision!==scene.revision)return {active:false,reason:`STALE · 저장 r${doc.revision} / 현재 r${scene.revision}`};if(doc.scene_fingerprint!==reviewFingerprint(scene))return {active:false,reason:'저장 시점과 현재 로드 범위/도형이 다릅니다.'};return {active:true,reason:'현재 프로젝트/revision/로드 범위 대응'};}
export function parseReviewBookmarks(text:string,scene:Scene):ReviewBookmarks {const value=safeJson(text,1024*1024) as ReviewBookmarks;if(!value||value.schema_version!==1||!Array.isArray(value.bookmarks)||value.bookmarks.length>128)throw new Error('Resistor 북마크 v1 필요');const status=bookmarkStatus(value,scene);if(!status.active)throw new Error(status.reason);const ids=new Set<string>(),shapes=new Set(scene.shapes.map(s=>s.id));for(const b of value.bookmarks){if(!b||typeof b!=='object')throw new Error('북마크 객체 필요');string(b.id,128);string(b.name,256);string(b.saved_at,128);if(ids.has(b.id)||!b.shape_id&&!b.point)throw new Error('북마크 ID 중복/대상 없음');ids.add(b.id);if(b.shape_id&&!shapes.has(b.shape_id))throw new Error('북마크 도형이 현재 로드 범위에 없습니다.');if(b.point)b.point=point(b.point);}return {...value,scope:reviewScope(scene)};}

export interface CsvContext {project_id?:string;revision?:number;source?:string;freshness?:'current'|'stale';run_id?:string}
export interface CsvRange {start?:number;end?:number;stride?:number}
function indices(length:number,range:CsvRange){const start=range.start??0,end=range.end??length-1,stride=range.stride??1;if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||!Number.isSafeInteger(stride)||start<0||end<start||end>=length||stride<1)throw new Error('CSV 샘플 범위/간격 오류');const n=Math.floor((end-start)/stride)+1;if(n>MAX_CSV_ROWS)throw new Error('CSV 최대 250000행입니다. 샘플 범위나 간격을 조정하세요.');return {start,end,stride,count:n};}
const csvString=(value:string)=>'"'+(/^[\s]*[=+\-@]/.test(value)?"'"+value:value).replace(/"/g,'""')+'"';
const csvNumber=(n:number)=>{if(typeof n!=='number'||!Number.isFinite(n))throw new Error('CSV에 비유한/누락 결과를 넣을 수 없습니다.');return String(n);};
export function exportCurrentCsv(flow:CurrentFlow,scene:Scene|null=null,range:CsvRange={}):string {if(flow.schema_version!==1||flow.convention!=='conventional'||flow.analysis.trim().toLowerCase()==='ac')throw new Error('스칼라 conventional CurrentFlow만 CSV로 내보냅니다.');const selected=indices(flow.x.length,range);if(selected.count*flow.branches.length>MAX_CSV_ROWS)throw new Error('CSV 최대 250000행입니다. 샘플 범위나 간격을 조정하세요.');const freshness=flow.freshness==='stale'||scene&&!flowStatus(flow,scene).active?'stale':flow.freshness??(scene?'revision-match':'unspecified'),rows=['sample_index,analysis,x_value,x_unit,branch_id,branch_name,from_net,to_net,current_A,source,tool,run_id,project_id,result_revision,scene_revision,freshness,geometry_linkage'];for(let i=selected.start;i<=selected.end;i+=selected.stride)for(const b of flow.branches){if(b.values_A.length!==flow.x.length)throw new Error('전류 샘플 수 불일치');rows.push([String(i),csvString(flow.analysis),csvNumber(flow.x[i]),csvString(flow.x_unit),csvString(b.id),csvString(b.name),csvString(b.from_net),csvString(b.to_net),csvNumber(b.values_A[i]),csvString(flow.source),csvString(flow.tool??''),csvString(flow.run_id??''),csvString(flow.project_id??''),String(flow.revision),scene?String(scene.revision):'',csvString(freshness),csvString(flow.geometry_linkage??'unspecified')].join(','));}return rows.join('\r\n')+'\r\n';}
export function exportWaveformCsv(waveforms:Waveform[],context:CsvContext={},range:CsvRange={}):string {if(!Array.isArray(waveforms)||!waveforms.length||waveforms.length>512)throw new Error('1–512개 파형이 필요합니다.');const rows=['sample_index,waveform,x_value,x_unit,value,value_unit,source,run_id,project_id,result_revision,freshness'];let count=0;for(const w of waveforms){if(w.x.length!==w.y.length)throw new Error('파형 샘플 수 불일치');const selected=indices(w.x.length,range);if((count+=selected.count)>MAX_CSV_ROWS)throw new Error('CSV 최대 250000행입니다.');for(let i=selected.start;i<=selected.end;i+=selected.stride)rows.push([String(i),csvString(w.name),csvNumber(w.x[i]),csvString(w.x_unit??''),csvNumber(w.y[i]),csvString(w.unit),csvString(context.source??''),csvString(context.run_id??''),csvString(context.project_id??''),context.revision===undefined?'':String(context.revision),csvString(context.freshness??'unspecified')].join(','));}return rows.join('\r\n')+'\r\n';}
