import type { CurrentFlow, Layer, Waveform } from '@mos/contracts';
import type { PdkDisplay } from './index';

/** Data-only interchange inspection. Nothing in these inputs is evaluated,
 * expanded as an environment variable, fetched, or used as a filesystem path. */
export interface CompatDiagnostic { severity:'info'|'warning'|'error'; code:string; message:string; line?:number; source_file?:string }
export interface UnsupportedPart { name:string; line:number; raw:string; reason:string; source_file?:string }
export interface StreamLayerMapping { layer:string; purpose:string; gds:[number,number]; line:number; enabled:boolean }
export interface TechName { name:string; number:number; abbreviation?:string }
export interface TechDisplay { layer:string; purpose:string; packet:string; visible?:boolean; selectable?:boolean; valid?:boolean }
export interface DisplayColor { display:string; name:string; rgb:[number,number,number] }
export interface DisplayPacket { display:string; name:string; stipple:string; lineStyle:string; fill:string; outline:string; fillStyle?:string }
export interface TechnologyMetadata { layers:TechName[]; purposes:TechName[]; displays:TechDisplay[]; colors:DisplayColor[]; packets:DisplayPacket[]; units?:Record<string,string>; priorities?:{layer:string;purpose:string}[] }
export interface LibraryDirective { directive:string; name?:string; path?:string; attributes?:string[]; line:number; unresolved:boolean }
export interface LibraryDefinitions { references:LibraryDirective[]; directives:LibraryDirective[] }
export interface SpiceDevice { name:string; kind:string; pins:string[]; model?:string; parameters:string[]; line:number; raw:string }
export interface SpiceSubcircuit { name:string; ports:string[]; parameters:string[]; pinInfo:Record<string,string>; devices:SpiceDevice[]; line:number }
export interface SpiceMetadata { subcircuits:SpiceSubcircuit[]; models:{name:string;type:string;parameters:string[];line:number}[]; devices:SpiceDevice[]; references:{directive:string;path:string;section?:string;line:number}[]; globals:string[] }
export interface ResultColumn { column:number|string; unit:string; name?:string }
export interface ResultCurrentColumn extends ResultColumn { id:string; name:string; from_net:string; to_net:string; source_vector?:string }
export interface ResultTableSchema { delimiter?:'csv'|'tab'|'whitespace'; header:boolean; columns?:string[]; x:ResultColumn; series?:ResultColumn[]; branches?:ResultCurrentColumn[]; convention?:'conventional'; analysis:'op'|'dc'|'tran'; source?:CurrentFlow['source'] }
export interface ResultContext { project_id?:string; revision:number; run_id?:string; tool?:string; freshness?:'current'|'stale' }
export interface MappedResults { waveforms:Waveform[]; currentFlow?:CurrentFlow; native_execution:false; vendor_verified:false }
export interface CompatInspection { schema_version:1; kind:'pdk'|'library'|'netlist'|'results'|'unknown'; format:string; support:'supported'|'partial'|'unsupported'|'needs-mapping'; diagnostics:CompatDiagnostic[]; unsupported:UnsupportedPart[]; source:{filename:string;text:string}; companion_sources?:{filename:string;text:string}[]; pdk?:PdkDisplay; layerMap?:StreamLayerMapping[]; technology?:TechnologyMetadata; libraries?:LibraryDefinitions; spice?:SpiceMetadata; results?:MappedResults }
export interface CompatOptions { streamMap?:string; displayDrf?:string; resultSchema?:ResultTableSchema; resultContext?:ResultContext }

const MAX_TEXT=4*1024*1024, MAX_NODES=200000;
function checkText(text:string,max=MAX_TEXT){if(typeof text!=='string'||text.length>max)throw new Error(`텍스트 처리 제한은 ${max/1024/1024} MiB입니다.`);if(/[\x00-\x08\x0b\x0c\x0e-\x1f]/.test(text))throw new Error('바이너리/제어 문자가 있는 파일은 ASCII 데이터 파일이 아닙니다.');}
const diagnostic=(severity:CompatDiagnostic['severity'],code:string,message:string,line?:number):CompatDiagnostic=>({severity,code,message,...(line?{line}:{})});
function base(text:string,filename:string,kind:CompatInspection['kind'],format:string):CompatInspection {checkText(text);return {schema_version:1,kind,format,support:'supported',diagnostics:[],unsupported:[],source:{filename,text}};}
function finish(out:CompatInspection){out.diagnostics=out.diagnostics.map(d=>({...d,source_file:d.source_file??out.source.filename}));out.support=out.diagnostics.some(d=>d.severity==='error')?'unsupported':out.support!=='supported'?out.support:out.unsupported.length||out.diagnostics.some(d=>d.severity==='warning')?'partial':'supported';return out;}
function unsupported(out:CompatInspection,name:string,line:number,raw:string,reason:string){out.unsupported.push({name,line,raw,reason,source_file:out.source.filename});out.diagnostics.push(diagnostic('warning','unsupported-part',`${name}: ${reason}`,line));}
function words(line:string):string[]{const tokens:string[]=[];let value='',quote='',active=false;for(let i=0;i<line.length;i++){const c=line[i];if(quote){if(c==='\\'&&(line[i+1]===quote||line[i+1]==='\\')){value+=line[++i];}else if(c===quote)quote='';else value+=c;active=true;}else if(c==='"'||c==="'"){quote=c;active=true;}else if(/\s/.test(c)){if(active){tokens.push(value);value='';active=false;}}else if(c==='#'||c===';'||c==='/'&&line[i+1]==='/'){break;}else{value+=c;active=true;}}if(quote)throw new Error('종료되지 않은 인용 문자열');if(active)tokens.push(value);return tokens;}
function gdsNumber(s:string|number):number {const n=typeof s==='number'?s:/^\d+$/.test(s)?Number(s):NaN;if(!Number.isInteger(n)||n<0||n>65535)throw new Error('GDS layer/datatype 범위는 0–65535 정수입니다.');return n;}

/** Cadence four-column LPP → GDS stream map; ranges/special NAME records retained. */
export function parseStreamLayerMap(text:string,filename='stream.layermap'):CompatInspection {
  const out=base(text,filename,'pdk','cadence-stream-map');out.layerMap=[];const seen=new Set<string>();
  text.split(/\r?\n/).forEach((raw,index)=>{const line=index+1;let row:string[];try{row=words(raw);}catch(e){out.diagnostics.push(diagnostic('error','syntax',String(e),line));return;}if(!row.length)return;
    if(row.length!==4||row[0].toUpperCase()==='NAME'){unsupported(out,'stream-map-record',line,raw,'단일 LPP 및 layer/datatype 네 열만 지원합니다. 범위·NAME 레코드는 원문을 보존합니다.');return;}
    try{const mapping:StreamLayerMapping={layer:row[0],purpose:row[1],gds:[gdsNumber(row[2]),gdsNumber(row[3])],line,enabled:true},key=`${mapping.layer}\0${mapping.purpose}\0${mapping.gds}`;if(seen.has(key)){out.diagnostics.push(diagnostic('info','duplicate-record','동일 레이어 맵 레코드',line));return;}seen.add(key);out.layerMap!.push(mapping);}catch(e){unsupported(out,'stream-map-record',line,raw,String(e));}
  });if(!out.layerMap.length)out.diagnostics.push(diagnostic('error','no-layer-map','유효한 명시적 LPP → GDS 맵이 없습니다.'));out.pdk=displayPdk(out.layerMap,emptyTech(),out);return finish(out);
}

type Atom=string|number;interface Node { name?:string; items:(Atom|Node)[]; line:number; start:number; end:number }
interface Token { value:string; quoted:boolean; line:number; start:number; end:number }
/** Small bounded AST for named Lisp data nodes; never SKILL evaluation. */
function dataAst(text:string):Node[]{checkText(text);const tokens:Token[]=[];let line=1;
  for(let i=0;i<text.length;){const start=i,c=text[i];if(c==='\n'){line++;i++;continue;}if(/\s/.test(c)){i++;continue;}if(c===';'){while(i<text.length&&text[i]!=='\n')i++;continue;}if(c==='/'&&text[i+1]==='*'){i+=2;while(i<text.length&&!(text[i]==='*'&&text[i+1]==='/')){if(text[i++]==='\n')line++;}if(i>=text.length)throw new Error('종료되지 않은 블록 주석');i+=2;continue;}
    const at=line;let value='',quoted=false;if(c==='"'){quoted=true;i++;let closed=false;while(i<text.length){const q=text[i++];if(q==='"'){closed=true;break;}if(q==='\\'&&(text[i]==='"'||text[i]==='\\'))value+=text[i++];else {value+=q;if(q==='\n')line++;}if(value.length>65536)throw new Error('AST 문자열 길이 제한');}if(!closed)throw new Error('종료되지 않은 AST 문자열');}
    else if(c==='('||c===')'){value=c;i++;}else{while(i<text.length&&!/[\s();]/.test(text[i]))value+=text[i++];if(!value)throw new Error('AST token 오류');}
    tokens.push({value,quoted,line:at,start,end:i});if(tokens.length>MAX_NODES)throw new Error('AST token 수 제한');
  }
  let cursor=0;const parse=(depth:number):Atom|Node=>{if(depth>64)throw new Error('AST 깊이 제한');const token=tokens[cursor++];if(!token)throw new Error('잘린 AST');if(token.value===')'&&!token.quoted)throw new Error('예상하지 않은 닫는 괄호');let name:string|undefined;
    if(!token.quoted&&token.value!=='('&&tokens[cursor]?.value==='('&&!tokens[cursor]?.quoted){name=token.value;cursor++;}else if(token.value!=='('||token.quoted){return !token.quoted&&/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?$/.test(token.value)?Number(token.value):token.value;}
    const node:Node={name,items:[],line:token.line,start:token.start,end:token.end};while(cursor<tokens.length&&!(tokens[cursor].value===')'&&!tokens[cursor].quoted))node.items.push(parse(depth+1));if(cursor===tokens.length)throw new Error('종료되지 않은 AST 노드');node.end=tokens[cursor++].end;return node;
  };const roots:Node[]=[];while(cursor<tokens.length){const v=parse(0);if(typeof v!=='object')throw new Error('최상위 값은 명명된 데이터 노드여야 합니다.');roots.push(v);}return roots;
}
const emptyTech=():TechnologyMetadata=>({layers:[],purposes:[],displays:[],colors:[],packets:[]});
const str=(v:Atom|Node|undefined):string=>{if(typeof v!=='string'||!v.length||v.length>512)throw new Error('이름/문자열 형식 오류');return v;};
const flag=(v:Atom|Node|undefined):boolean|undefined=>v==='t'?true:v==='nil'?false:undefined;
const rowNodes=(n:Node)=>n.items.filter((v):v is Node=>typeof v==='object'&&!v.name);
function walkNodes(nodes:Node[],visit:(node:Node)=>boolean){for(const n of nodes){if(visit(n))walkNodes(n.items.filter((v):v is Node=>typeof v==='object'&&!!v.name),visit);}}
function parseDrfNodes(nodes:Node[],out:CompatInspection,tech:TechnologyMetadata){walkNodes(nodes,n=>{if(n.name==='drDefineDisplay')return false;if(n.name==='drDefineColor'){for(const row of rowNodes(n)){try{const a=row.items,rgb=a.slice(2,5).map(v=>typeof v==='number'&&Number.isInteger(v)&&v>=0&&v<=255?v:NaN);if(a.length<5||rgb.some(Number.isNaN))throw new Error('RGB 0–255 필요');tech.colors.push({display:str(a[0]),name:str(a[1]),rgb:rgb as [number,number,number]});}catch(e){unsupported(out,n.name!,row.line,out.source.text.slice(row.start,row.end),String(e));}}return false;}
    if(n.name==='drDefinePacket'){for(const row of rowNodes(n)){try{const a=row.items;if(a.length<6||a.length>7)throw new Error('packet 6–7 필드 필요');tech.packets.push({display:str(a[0]),name:str(a[1]),stipple:str(a[2]),lineStyle:str(a[3]),fill:str(a[4]),outline:str(a[5]),...(a[6]===undefined?{}:{fillStyle:str(a[6])})});}catch(e){unsupported(out,n.name!,row.line,out.source.text.slice(row.start,row.end),String(e));}}return false;}
    unsupported(out,n.name??'list',n.line,out.source.text.slice(n.start,n.end),'표시 색상/packet 외 데이터는 보존하며 실행하지 않습니다.');return false;
  });}
export function parseDisplayDrf(text:string,filename='display.drf'):CompatInspection {const out=base(text,filename,'pdk','cadence-display-drf'),tech=emptyTech();parseDrfNodes(dataAst(text),out,tech);out.technology=tech;out.diagnostics.push(diagnostic('info','display-only','DRF는 색상/packet 데이터입니다. LPP와 명시적 GDS 맵이 있어야 도형에 적용할 수 있습니다.'));return finish(out);}

export function parseCadenceTechfile(text:string,filename='techfile.tf',options:CompatOptions={}):CompatInspection {
  const out=base(text,filename,'pdk','cadence-ascii-techfile'),tech=emptyTech();out.technology=tech;out.layerMap=[];
  const containers=new Set(['layerDefinitions','layerRules','controls']);walkNodes(dataAst(text),n=>{if(containers.has(n.name??''))return true;
    if(n.name==='techLayers'||n.name==='techPurposes'){for(const row of rowNodes(n)){try{const a=row.items;if(a.length<2||typeof a[1]!=='number'||!Number.isInteger(a[1])||a[1]<0||a[1]>2147483647)throw new Error('tech 이름/내부 번호 형식 오류');(n.name==='techLayers'?tech.layers:tech.purposes).push({name:str(a[0]),number:a[1],...(a[2]===undefined?{}:{abbreviation:str(a[2])})});if(a.length>3)unsupported(out,n.name!,row.line,text.slice(row.start,row.end),'추가 속성은 메타데이터 원문으로 보존합니다.');}catch(e){unsupported(out,n.name!,row.line,text.slice(row.start,row.end),String(e));}}return false;}
    if(n.name==='techLayerPurposePriorities'){tech.priorities=[];for(const row of rowNodes(n)){try{if(row.items.length!==2)throw new Error('LPP 두 필드 필요');tech.priorities.push({layer:str(row.items[0]),purpose:str(row.items[1])});}catch(e){unsupported(out,n.name,row.line,text.slice(row.start,row.end),String(e));}}return false;}
    if(n.name==='techDisplays'){for(const row of rowNodes(n)){try{const a=row.items;if(a.length<3)throw new Error('LPP/packet 필요');tech.displays.push({layer:str(a[0]),purpose:str(a[1]),packet:str(a[2]),visible:flag(a[3]),selectable:flag(a[4]),valid:flag(a[7])});if(a.slice(3).some(v=>flag(v)===undefined))unsupported(out,n.name!,row.line,text.slice(row.start,row.end),'t/nil 이외 표시 플래그는 적용하지 않습니다.');}catch(e){unsupported(out,n.name!,row.line,text.slice(row.start,row.end),String(e));}}return false;}
    if(n.name==='streamLayers'){for(const row of rowNodes(n)){try{const a=row.items;if(a.length!==4)throw new Error('5.x streamLayers (layer number datatype translate)만 지원');const mapping:StreamLayerMapping={layer:str(a[0]),purpose:'drawing',gds:[gdsNumber(a[1] as Atom),gdsNumber(a[2] as Atom)],enabled:flag(a[3])===true,line:row.line};if(flag(a[3])===undefined)throw new Error('translate t/nil 필요');out.layerMap!.push(mapping);}catch(e){unsupported(out,n.name!,row.line,text.slice(row.start,row.end),String(e));}}return false;}
    unsupported(out,n.name??'list',n.line,text.slice(n.start,n.end),'표시/LPP/스트림 맵 외 기술 데이터·규칙·함수는 보존하며 실행하지 않습니다.');return false;
  });
  if(options.displayDrf){const drf=parseDisplayDrf(options.displayDrf);tech.colors=drf.technology!.colors;tech.packets=drf.technology!.packets;out.companion_sources=[{filename:'display.drf',text:options.displayDrf}];out.diagnostics.push(...drf.diagnostics);out.unsupported.push(...drf.unsupported);}
  if(options.streamMap){const map=parseStreamLayerMap(options.streamMap);const old=out.layerMap;out.layerMap=map.layerMap;out.diagnostics.push(...map.diagnostics);out.unsupported.push(...map.unsupported);out.companion_sources=[...(out.companion_sources??[]),{filename:'stream.layermap',text:options.streamMap}];if(old.length)out.diagnostics.push(diagnostic('warning','external-stream-map','별도 stream map이 기술 파일의 5.x streamLayers보다 우선합니다. 원래 맵은 기술 파일 원문에 보존됩니다.'));}
  out.diagnostics.push(diagnostic('info','internal-layer-number','techLayers의 내부 번호는 GDS 번호가 아닙니다. 명시적 stream map만 표시 변환에 사용합니다.'));
  if(!out.layerMap?.some(m=>m.enabled))out.diagnostics.push(diagnostic('warning','missing-stream-map','명시적 stream map이 없어 PDK 색상을 GDS에 적용하지 않습니다.'));else out.pdk=displayPdk(out.layerMap,tech,out);return finish(out);
}

interface BraceBlock {name:string;label?:string;line:number;start:number;end:number;fields:{name:string;value:string;line:number;raw:string}[]}
/** Verified subset from a public PDK author's ICC2 .tf: scalar assignments in
 * Technology, Color and Layer blocks. All rules and other blocks stay raw. */
function braceBlocks(text:string):BraceBlock[]{checkText(text);const tokens:Token[]=[];let line=1;
  for(let i=0;i<text.length;){const start=i,c=text[i];if(c==='\n'){tokens.push({value:'\n',quoted:false,line,start,end:i+1});line++;i++;continue;}if(/\s/.test(c)){i++;continue;}if(c==='#'||c==='/'&&text[i+1]==='/'){while(i<text.length&&text[i]!=='\n')i++;continue;}if(c==='/'&&text[i+1]==='*'){i+=2;while(i<text.length&&!(text[i]==='*'&&text[i+1]==='/')){if(text[i++]==='\n')line++;}if(i>=text.length)throw new Error('종료되지 않은 brace 주석');i+=2;continue;}
    const at=line;let value='',quoted=false;if(c==='"'){quoted=true;i++;let closed=false;while(i<text.length){const ch=text[i++];if(ch==='"'){closed=true;break;}if(ch==='\\'&&(text[i]==='"'||text[i]==='\\'))value+=text[i++];else {value+=ch;if(ch==='\n')line++;}if(value.length>65536)throw new Error('brace 문자열 제한');}if(!closed)throw new Error('종료되지 않은 brace 문자열');}else if('{}=();'.includes(c)){value=c;i++;}else{while(i<text.length&&!/[\s{}=();]/.test(text[i]))value+=text[i++];}
    tokens.push({value,quoted,line:at,start,end:i});if(tokens.length>MAX_NODES)throw new Error('brace token 제한');
  }const blocks:BraceBlock[]=[];let cursor=0;const skip=()=>{while(tokens[cursor]?.value==='\n'||tokens[cursor]?.value===';')cursor++;};
  while(cursor<tokens.length){skip();if(cursor>=tokens.length)break;const name=tokens[cursor++];if(!/^[A-Za-z][\w]*$/.test(name.value)||name.quoted)throw new Error('brace block 이름 오류');skip();let label:string|undefined;if(tokens[cursor]?.value!=='{'){label=tokens[cursor++]?.value;skip();}if(tokens[cursor++]?.value!=='{')throw new Error('brace block 시작 오류');const block:BraceBlock={name:name.value,label,line:name.line,start:name.start,end:name.end,fields:[]};let depth=1;
    while(cursor<tokens.length){skip();const key=tokens[cursor];if(!key)break;if(key.value==='}'){cursor++;depth--;if(!depth){block.end=key.end;break;}}if(!depth)break;cursor++;
      if(!/^[A-Za-z][\w]*$/.test(key.value)||tokens[cursor]?.value!=='='){let level=0;while(cursor<tokens.length){const t=tokens[cursor++];if(t.value==='{'){if(++level>64)throw new Error('brace 깊이 제한');}if(t.value==='}') {if(level>0){level--;continue;}cursor--;break;}if(t.value==='\n'&&level===0)break;}block.fields.push({name:key.value,value:'',line:key.line,raw:text.slice(key.start,tokens[Math.max(0,cursor-1)].end)});continue;}
      cursor++;const values:Token[]=[];let parens=0;while(cursor<tokens.length){const t=tokens[cursor];if(!t.quoted&&((t.value==='\n'||t.value===';'||t.value==='}')&&parens===0))break;if(!t.quoted&&t.value==='=')throw new Error('brace scalar assignment 사이에 줄바꿈/구분자가 필요합니다.');if(!t.quoted&&t.value==='('&&++parens>64)throw new Error('brace tuple 깊이 제한');if(!t.quoted&&t.value===')'&&--parens<0)throw new Error('brace tuple 오류');if(!t.quoted&&t.value==='{')throw new Error('scalar assignment 안의 중첩 brace 미지원');values.push(t);cursor++;}if(parens||!values.length)throw new Error('brace assignment 값 오류');const scalar=values.length===1?values[0].value:undefined;block.fields.push({name:key.value,value:scalar??'',line:key.line,raw:text.slice(key.start,values.at(-1)!.end)});
    }if(depth)throw new Error('종료되지 않은 brace block');blocks.push(block);
  }return blocks;
}
export function parseSynopsysTechnology(text:string,filename='technology.tf',options:CompatOptions={}):CompatInspection {
  const out=base(text,filename,'pdk','synopsys-ascii-technology'),tech=emptyTech();out.technology=tech;tech.units={};out.layerMap=[];
  for(const block of braceBlocks(text)){const fields=new Map(block.fields.map(f=>[f.name,f.value]));if(block.name==='Technology'){for(const f of block.fields){if(/^unit\w+Name$/.test(f.name)&&f.value)tech.units[f.name]=f.value;else unsupported(out,`Technology.${f.name}`,f.line,f.raw,'라이브러리/precision/공정 규칙 속성은 메타데이터 원문만 보존합니다.');}continue;}
    if(block.name==='Color'){try{const rgb=['redIntensity','greenIntensity','blueIntensity'].map(k=>Number(fields.get(k)));if(fields.get('rgbDefined')!=='1'||rgb.some(v=>!Number.isInteger(v)||v<0||v>255))throw new Error('명시적 rgbDefined=1 및 RGB 0–255 필요');tech.colors.push({display:'display',name:fields.get('name')??block.label??'',rgb:rgb as [number,number,number]});}catch(e){unsupported(out,'Color',block.line,text.slice(block.start,block.end),String(e));}for(const f of block.fields)if(!['name','rgbDefined','redIntensity','greenIntensity','blueIntensity'].includes(f.name))unsupported(out,`Color.${f.name}`,f.line,f.raw,'미지원 color 속성 보존');continue;}
    if(block.name==='Layer'){try{const name=block.label;if(!name)throw new Error('명시적 Layer 이름 필요');const number=Number(fields.get('layerNumber'));if(!Number.isInteger(number)||number<0||number>2147483647)throw new Error('내부 layerNumber 정수 필요');tech.layers.push({name,number});const packet=`synopsys:${name}`;tech.displays.push({layer:name,purpose:'drawing',packet,visible:fields.get('visible')==='1'?true:fields.get('visible')==='0'?false:undefined,selectable:fields.get('selectable')==='1'?true:fields.get('selectable')==='0'?false:undefined});if(fields.get('color'))tech.packets.push({display:'display',name:packet,stipple:fields.get('pattern')??'unknown',lineStyle:fields.get('lineStyle')??'unknown',fill:fields.get('color')!,outline:fields.get('color')!});}catch(e){unsupported(out,'Layer',block.line,text.slice(block.start,block.end),String(e));}for(const f of block.fields)if(!['layerNumber','visible','selectable','color','lineStyle','pattern'].includes(f.name))unsupported(out,`Layer.${f.name}`,f.line,f.raw,'규칙/모델/물리 속성은 표시 변환에 적용하지 않고 원문으로 보존합니다.');continue;}
    unsupported(out,block.name,block.line,text.slice(block.start,block.end),'Technology 단위, RGB Color, Layer 표시 속성 외 block은 보존하며 실행하지 않습니다.');
  }
  if(options.streamMap){const map=parseStreamLayerMap(options.streamMap);out.layerMap=map.layerMap;out.companion_sources=[{filename:'stream.layermap',text:options.streamMap}];out.diagnostics.push(...map.diagnostics);out.unsupported.push(...map.unsupported);out.pdk=displayPdk(out.layerMap??[],tech,out);}else out.diagnostics.push(diagnostic('warning','missing-stream-map','Synopsys 내부 layerNumber는 GDS stream 번호로 추정하지 않습니다. 명시적 companion LPP map이 필요합니다.'));
  out.diagnostics.push(diagnostic('info','verified-subset','공개 PDK author의 ICC2 ASCII .tf에서 확인한 scalar block만 읽습니다. Synopsys rule/database 전체 호환성 또는 signoff 검증을 의미하지 않습니다.'));return finish(out);
}

function displayPdk(mappings:StreamLayerMapping[],tech:TechnologyMetadata,out:CompatInspection):PdkDisplay|undefined {
  const layers:Layer[]=[],groups=new Map<string,StreamLayerMapping[]>();for(const m of mappings.filter(m=>m.enabled)){const id=m.gds.join('/');groups.set(id,[...(groups.get(id)??[]),m]);}
  if(groups.size>4096){out.diagnostics.push(diagnostic('error','pdk-layer-limit','PDK 표시 layer/datatype 수 제한은 4096입니다. 원본 맵은 보존합니다.'));return undefined;}
  for(const [id,rows] of groups){const packets=rows.map(m=>tech.displays.find(d=>d.layer===m.layer&&d.purpose===m.purpose)).map(d=>d?tech.packets.find(p=>p.display==='display'&&p.name===d.packet):undefined);const colors=packets.map(p=>p?tech.colors.find(c=>c.display===p.display&&c.name===p.fill)?.rgb:undefined);const known=colors.filter((v):v is [number,number,number]=>!!v).map(rgb=>'#'+rgb.map(v=>v.toString(16).padStart(2,'0')).join(''));
    if(new Set(known).size>1){out.diagnostics.push(diagnostic('warning','ambiguous-gds-display',`${id}: 같은 GDS에 서로 다른 LPP 색상이 있어 적용하지 않습니다.`));continue;}
    const color=known[0]??'#8999b0';if(!known.length&&tech.displays.length)out.diagnostics.push(diagnostic('warning','missing-display-packet',`${id}: packet/fill 색상 대응이 없어 중립 표시 색상만 사용합니다.`));
    layers.push({id,name:[...new Set(rows.map(r=>`${r.layer}/${r.purpose}`))].join(', '),gds:rows[0].gds,color,opacity:.65,z_display_um:layers.length*.3,thickness_display_um:.12,source:'user',physical_z_um:null,physical_thickness_um:null,material:'mask'});
  }if(!layers.length)return undefined;return {id:out.source.filename.replace(/\.[^.]*$/,''),name:out.source.filename,layers,compact_default_stack:true,notes:['명시적 LPP → GDS 맵과 DRF 색상 데이터만 적용합니다.','3D 높이/두께는 표시용입니다. 기술 파일의 DRC·모델·공정 물리 stack은 실행하거나 추정하지 않습니다.']};
}

export function parseLibraryDefinitions(text:string,filename='cds.lib'):CompatInspection {
  const out=base(text,filename,'library',/lib\.defs$/i.test(filename)?'openaccess-lib-defs':'cadence-cds-lib'),directives:LibraryDirective[]=[],active=new Map<string,LibraryDirective>();
  text.split(/\r?\n/).forEach((raw,index)=>{const line=index+1;let a:string[];try{a=words(raw);}catch(e){out.diagnostics.push(diagnostic('error','syntax',String(e),line));return;}if(!a.length)return;const command=a[0].toUpperCase(),unresolved=(path:string)=>/\$|~|\(|\)|`/.test(path);
    if(out.format==='openaccess-lib-defs'&&['SOFTINCLUDE','SOFTDEFINE','UNDEFINE'].includes(command)){unsupported(out,command,line,raw,'lib.defs의 지원 데이터 지시문이 아닙니다.');return;}
    if(['DEFINE','SOFTDEFINE'].includes(command)&&a.length===3){const v:LibraryDirective={directive:command,name:a[1],path:a[2],line,unresolved:unresolved(a[2])};directives.push(v);if(command==='DEFINE'||!active.has(a[1]))active.set(a[1],v);}
    else if(command==='UNDEFINE'&&a.length===2){directives.push({directive:command,name:a[1],line,unresolved:false});active.delete(a[1]);}
    else if(['INCLUDE','SOFTINCLUDE'].includes(command)&&a.length===2){directives.push({directive:command,path:a[1],line,unresolved:true});out.diagnostics.push(diagnostic('warning','unresolved-include','include 참조는 자동으로 열거나 실행하지 않습니다.',line));}
    else if(command==='ASSIGN'&&a.length>=4)directives.push({directive:command,name:a[1],attributes:a.slice(2),line,unresolved:false});
    else unsupported(out,command,line,raw,'알 수 없는 라이브러리 지시문 또는 필드 수입니다.');
  });out.libraries={references:[...active.values()],directives};out.diagnostics.push(diagnostic('info','references-only','라이브러리 경로는 문자열 메타데이터입니다. 환경 확장·외부 파일 접근·OA 데이터베이스 로드는 수행하지 않습니다.'));return finish(out);
}

function spiceLines(text:string){const rows:{text:string;line:number}[]=[];text.split(/\r?\n/).forEach((raw,i)=>{if(raw.trimStart().startsWith('+')){if(!rows.length)throw new Error('선행 SPICE continuation');rows.at(-1)!.text+=' '+raw.trimStart().slice(1).trim();}else rows.push({text:raw,line:i+1});});return rows;}
export function parseSpiceMetadata(text:string,filename='design.cdl'):CompatInspection {
  const out=base(text,filename,'netlist',/\.cdl$/i.test(filename)?'cdl-spice-metadata':'spice-metadata'),meta:SpiceMetadata={subcircuits:[],models:[],devices:[],references:[],globals:[]};out.spice=meta;const stack:SpiceSubcircuit[]=[];let control=false;
  for(const row of spiceLines(text)){const raw=row.text.trim();if(!raw)continue;if(/^\*\.PININFO\b/i.test(raw)){const cell=stack.at(-1);if(cell)for(const item of raw.replace(/^\*\.PININFO\s*/i,'').split(/\s+/)){const match=/^(.+):([IOBPG])$/i.exec(item);if(match)cell.pinInfo[match[1]]=match[2].toUpperCase();else unsupported(out,'PININFO',row.line,row.text,'명시적 pin:direction 필드만 지원합니다.');}continue;}if(raw.startsWith('*'))continue;
    const a=raw.replace(/\s+\$.*$/,'').split(/\s+/),command=a[0].toUpperCase();if(command==='.CONTROL'){control=true;unsupported(out,command,row.line,row.text,'제어 스크립트는 실행하거나 해석하지 않습니다.');continue;}if(command==='.ENDC'){control=false;continue;}if(control){unsupported(out,'control-command',row.line,row.text,'제어 스크립트 원문 보존');continue;}
    if(command==='.SUBCKT'){if(a.length<2){out.diagnostics.push(diagnostic('error','subckt','subckt 이름 필요',row.line));continue;}if(stack.length)unsupported(out,'nested-subckt',row.line,row.text,'중첩 subckt는 이름/포트 메타데이터만 보존합니다. 벤더 scope/호출 의미는 지원하지 않습니다.');const pivot=a.findIndex((v,i)=>i>1&&(v.includes('=')||/^params:$/i.test(v))),stop=pivot<0?a.length:pivot;const cell:SpiceSubcircuit={name:a[1],ports:a.slice(2,stop),parameters:a.slice(stop),pinInfo:{},devices:[],line:row.line};if(meta.subcircuits.some(c=>c.name.toLowerCase()===cell.name.toLowerCase()))out.diagnostics.push(diagnostic('error','duplicate-subckt',`중복 subckt ${cell.name}`,row.line));meta.subcircuits.push(cell);stack.push(cell);continue;}
    if(command==='.ENDS'){const cell=stack.pop();if(!cell||a[1]&&a[1].toLowerCase()!==cell.name.toLowerCase())out.diagnostics.push(diagnostic('error','ends','subckt 종료 이름/위치 오류',row.line));continue;}
    if(command==='.MODEL'){if(a.length<3)out.diagnostics.push(diagnostic('error','model','model 이름/type 필요',row.line));else meta.models.push({name:a[1],type:a[2].split('(')[0],parameters:a.slice(2).join(' ').slice(a[2].split('(')[0].length).trim().split(/\s+/).filter(Boolean),line:row.line});continue;}
    if(['.INCLUDE','.INC','.LIB'].includes(command)){let parts:string[];try{parts=words(raw);}catch{parts=[];}if(parts.length>=2)meta.references.push({directive:command,path:parts[1],...(parts[2]?{section:parts[2]}:{}),line:row.line});out.diagnostics.push(diagnostic('warning','unresolved-model-reference','모델/라이브러리 참조는 자동 로드하지 않습니다.',row.line));continue;}
    if(command==='.GLOBAL'){meta.globals.push(...a.slice(1));continue;}if(command==='.END'||command==='.TITLE')continue;
    if(command.startsWith('.')){unsupported(out,command,row.line,row.text,'분석/표현식/벤더 지시문은 메타데이터 원문으로 보존합니다.');continue;}
    const kind=command[0],pinCounts:Record<string,number>={R:2,C:2,L:2,V:2,I:2,D:2,M:4,Q:3};let pins:string[],model:string|undefined,parameters:string[];
    if(kind==='X'){const pivot=a.findIndex((v,i)=>i>0&&(v.includes('=')||/^params:$/i.test(v))),stop=pivot<0?a.length:pivot;if(stop<3){unsupported(out,'X',row.line,row.text,'subckt 호출 핀/모델 부족');continue;}pins=a.slice(1,stop-1);model=a[stop-1];parameters=a.slice(stop);}
    else if(kind==='Q'){const isBjt=(name:string|undefined)=>!!name&&meta.models.some(m=>m.name.toLowerCase()===name.toLowerCase()&&['NPN','PNP'].includes(m.type.toUpperCase()));const three=isBjt(a[4]),four=isBjt(a[5]);if(three===four){unsupported(out,'Q',row.line,row.text,'BJT 3/4 핀을 구분할 명시적 앞선 NPN/PNP 모델 선언이 필요합니다. 추정하지 않습니다.');continue;}const n=three?3:4;pins=a.slice(1,n+1);model=a[n+1];parameters=a.slice(n+2);}
    else if(pinCounts[kind]!==undefined){const n=pinCounts[kind];if(a.length<n+2){unsupported(out,kind,row.line,row.text,'소자 필드 수 부족');continue;}pins=a.slice(1,n+1);model=['M','D'].includes(kind)?a[n+1]:undefined;parameters=a.slice(n+1+(model?1:0));}
    else{unsupported(out,'netlist-line',row.line,row.text,'지원 소자 R/C/L/V/I/D/M/Q/X 이외 구문');continue;}
    const device:SpiceDevice={name:a[0],kind,pins,...(model?{model}:{}),parameters,line:row.line,raw:row.text};(stack.at(-1)?.devices??meta.devices).push(device);
  }if(stack.length||control)out.diagnostics.push(diagnostic('error','unterminated','종료되지 않은 subckt/control 구문'));meta.globals=[...new Set(meta.globals)];out.diagnostics.push(diagnostic('info','metadata-only','명시적인 subckt 포트 순서와 소자 토큰만 읽습니다. 모델 실행·접지/바이어스 추정·시뮬레이션 검증은 수행하지 않습니다.'));return finish(out);
}

function csvRows(text:string,delimiter:string):string[][] {const rows:string[][]=[];let row:string[]=[],value='',quoted=false,afterQuote=false,cells=0;const push=()=>{if(++cells>4000000||row.length>=4096)throw new Error('결과 원본 셀/열 수 제한');row.push(value.trim());value='';afterQuote=false;};for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){value+='"';i++;}else if(c==='"'){quoted=false;afterQuote=true;}else value+=c;}else if(c==='"'){if(value.trim()||afterQuote)throw new Error('잘못된 CSV 인용');quoted=true;}else if(c===delimiter){push();}else if(c==='\n'){push();if(row.some(v=>v))rows.push(row);row=[];}else if(c!=='\r'){if(afterQuote&&!/\s/.test(c))throw new Error('CSV 닫는 인용 이후 문자');value+=c;}if(value.length>65536)throw new Error('결과 셀 문자열 길이 제한');if(rows.length>200001)throw new Error('결과 샘플 수 제한');}if(quoted)throw new Error('종료되지 않은 CSV 인용');push();if(row.some(v=>v))rows.push(row);return rows;}
const unitScale:Record<string,[number,string]>={A:[1,'A'],mA:[1e-3,'A'],uA:[1e-6,'A'],'µA':[1e-6,'A'],nA:[1e-9,'A'],pA:[1e-12,'A'],V:[1,'V'],mV:[1e-3,'V'],uV:[1e-6,'V'],s:[1,'s'],ms:[1e-3,'s'],us:[1e-6,'s'],ns:[1e-9,'s'],ps:[1e-12,'s'],Hz:[1,'Hz'],'1':[1,'1']};
export function parseMappedResultText(text:string,schema:ResultTableSchema,context:ResultContext):MappedResults {
  checkText(text,16*1024*1024);if(!schema||!['op','dc','tran'].includes(schema.analysis))throw new Error('OP/DC/tran 스칼라 분석을 명시하세요. AC 복소 방향은 지원하지 않습니다.');if(!context||!Number.isInteger(context.revision)||context.revision<0)throw new Error('결과 revision 필요');if(context.freshness!==undefined&&!['current','stale'].includes(context.freshness))throw new Error('결과 freshness 형식 오류');for(const key of ['project_id','run_id','tool'] as const)if(context[key]!==undefined&&(typeof context[key]!=='string'||context[key]!.length>512))throw new Error('결과 provenance 문자열 형식 오류');if(typeof schema.header!=='boolean')throw new Error('결과 header 유무를 명시하세요.');
  const delimiter=schema.delimiter??'csv';if(!['csv','tab','whitespace'].includes(delimiter))throw new Error('결과 delimiter 형식 오류');let rows:string[][]=[];if(delimiter==='whitespace'){let cells=0;for(const raw of text.split(/\r?\n/)){const s=raw.trim();if(!s||s.startsWith('#'))continue;const row=s.split(/\s+/);cells+=row.length;if(cells>4000000||row.length>4096||row.some(v=>v.length>65536)||rows.length>200000)throw new Error('결과 원본 셀/열/샘플 수 제한');rows.push(row);}}else rows=csvRows(text,delimiter==='tab'?'\t':',');let headers=schema.columns;if(schema.header)headers=rows.shift();if(headers&&(!Array.isArray(headers)||!headers.length||headers.some(h=>typeof h!=='string'||!h.length)||new Set(headers).size!==headers.length))throw new Error('결과 header/columns 중복/누락');if(!rows.length||rows.length>200000)throw new Error('결과 샘플 수 1–200000 필요');const width=rows[0].length;if(rows.some(r=>r.length!==width))throw new Error('결과 열 수 불일치');if(headers&&headers.length!==width)throw new Error('결과 columns/실제 열 수 불일치');
  const select=(column:ResultColumn,allowed?:string)=>{if(!column||typeof column.unit!=='string'||!unitScale[column.unit])throw new Error('명시적 SI 단위가 필요합니다. 지원: A/mA/uA/nA/pA, V/mV/uV, s/ms/us/ns/ps, Hz, 1');const [scale,unit]=unitScale[column.unit];if(allowed&&unit!==allowed)throw new Error(`전류 단위는 ${allowed} 또는 접두 단위여야 합니다.`);const index=typeof column.column==='number'?column.column:headers?.indexOf(column.column)??-1;if(!Number.isInteger(index)||index<0||index>=width)throw new Error('결과 column 선택 오류');const values=rows.map(r=>{const token=r[index];if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eEdD][+-]?\d+)?$/.test(token))throw new Error('결과 셀은 유한한 숫자여야 합니다.');const n=Number(token.replace(/[dD]/,'e'))*scale;if(!Number.isFinite(n))throw new Error('비유한 결과 값');return n;});return {values,unit};};
  const x=select(schema.x),series=schema.series??[],branches=schema.branches??[];if(!Array.isArray(series)||!Array.isArray(branches))throw new Error('결과 series/branches는 배열이어야 합니다.');if(series.length+branches.length>512||(series.length+branches.length)*rows.length>2000000)throw new Error('결과 선택 벡터/샘플 제한');if(!series.length&&!branches.length)throw new Error('적어도 하나의 결과 열을 명시하세요.');const names=new Set<string>();const waveforms=series.map(s=>{if(typeof s?.name!=='string'||!s.name||s.name.length>512||names.has(s.name))throw new Error('파형 name 중복/누락');names.add(s.name);const y=select(s);return {name:s.name,unit:y.unit,x:x.values,y:y.values,x_unit:x.unit};});let currentFlow:CurrentFlow|undefined;
  if(branches.length){if(schema.convention!=='conventional')throw new Error('전류의 conventional 부호 규약을 명시하세요.');const ids=new Set<string>();const normalized=branches.map(b=>{if(!b||['id','name','from_net','to_net'].some(k=>typeof b[k as keyof ResultCurrentColumn]!=='string'||!(b[k as keyof ResultCurrentColumn] as string).length||(b[k as keyof ResultCurrentColumn] as string).length>512)||ids.has(b.id))throw new Error('전류 id/name/from_net/to_net 문자열 필요 및 ID 중복 금지');if(b.source_vector!==undefined&&(typeof b.source_vector!=='string'||b.source_vector.length>512))throw new Error('전류 source_vector 문자열 형식 오류');ids.add(b.id);return {id:b.id,name:b.name,from_net:b.from_net,to_net:b.to_net,values_A:select(b,'A').values,mapping:'unmapped' as const,source_vector:b.source_vector??String(b.column)};});const declaredSource=schema.source??'imported';if(!['ngspice','imported','spectre','hspice','primesim','commercial'].includes(declaredSource))throw new Error('전류 source 형식 오류');const tool=context.tool??(declaredSource==='imported'?undefined:declaredSource);currentFlow={schema_version:1,source:'imported',analysis:schema.analysis,x:x.values,x_unit:x.unit,branches:normalized,convention:'conventional',revision:context.revision,...(context.project_id?{project_id:context.project_id}:{}),...(context.run_id?{run_id:context.run_id}:{}),...(tool?{tool}:{}),...(context.freshness?{freshness:context.freshness}:{}),geometry_linkage:'unverified',input_origin:'imported-file',notes:['업로드한 결과 열과 단위/부호 규약으로 가져왔습니다. 선언된 tool은 파일 메타데이터이며 Native/vendor 실행은 검증하지 않았습니다. GDS 위치 대응은 미검증입니다.']};}
  return {waveforms,...(currentFlow?{currentFlow}:{}),native_execution:false,vendor_verified:false};
}

export function inspectCompatText(text:string,filename:string,options:CompatOptions={}):CompatInspection {
  try{checkText(text,16*1024*1024);const lower=filename.toLowerCase();if(options.resultSchema){const out=base('',filename,'results','mapped-scalar-table');out.source.text=text;out.results=parseMappedResultText(text,options.resultSchema,options.resultContext??{revision:0});return out;}
    if(/(?:^|[\\/])(?:cds\.lib|lib\.defs)$/i.test(filename))return parseLibraryDefinitions(text,filename);
    if(/drDefine(?:Color|Packet|Display)\s*\(/.test(text)&&!/(?:layerDefinitions|techLayers)\s*\(/.test(text)||lower.endsWith('.drf'))return parseDisplayDrf(text,filename);
    if(/(?:layerDefinitions|techLayers|streamLayers)\s*\(/.test(text))return parseCadenceTechfile(text,filename,options);
    if(/^\s*Technology\s*\{/m.test(text))return parseSynopsysTechnology(text,filename,options);
    if(/\.(?:layermap|map)$/.test(lower)||/^\s*[^#;\s]+\s+[^\s]+\s+\d+\s+\d+\s*(?:[#;].*)?$/m.test(text))return parseStreamLayerMap(text,filename);
    if(/\.(?:cdl|sp|spice|cir|spi)$/.test(lower)||/^\s*\.SUBCKT\b/im.test(text))return parseSpiceMetadata(text,filename);
    const out=base(text,filename,/\.(?:csv|dat|tsv)$/.test(lower)?'results':'unknown',/\.(?:csv|dat|tsv)$/.test(lower)?'unmapped-table':'unknown');if(out.kind==='results'){out.support='needs-mapping';out.diagnostics.push(diagnostic('warning','explicit-column-map','결과 열, SI 단위, 분석 종류와 전류 from/to 및 부호 규약을 지정해야 합니다.'));}else {out.support='unsupported';out.diagnostics.push(diagnostic('warning','unsupported-format','지원 구문이 확인되지 않은 파일입니다. 바이너리/암호화/OA/벤더 기술 데이터는 자동 변환하거나 실행하지 않습니다.'));}return finish(out);
  }catch(e){return {schema_version:1,kind:'unknown',format:'invalid-text',support:'unsupported',diagnostics:[{...diagnostic('error','parse-error',e instanceof Error?e.message:String(e)),source_file:filename}],unsupported:[],source:{filename,text:text.length<=16*1024*1024?text:''}};}
}
export function exportCadenceLayerMap(value:CompatInspection|StreamLayerMapping[]):string {const mappings=Array.isArray(value)?value:value.layerMap??[];const lines=['# Resistor explicit Cadence LPP to GDS map. Unsupported original data stays in the compatibility bundle.'];for(const row of mappings){if(!row.enabled)continue;const quoted=(s:string)=>{if(/[\r\n\x00]/.test(s))throw new Error('레이어 이름 개행/제어 문자 금지');return /^[^\s#;"']+$/.test(s)?s:'"'+s.replace(/\\/g,'\\\\').replace(/"/g,'\\"')+'"';};lines.push(`${quoted(row.layer)} ${quoted(row.purpose)} ${gdsNumber(row.gds[0])} ${gdsNumber(row.gds[1])}`);}return lines.join('\n')+'\n';}
export function exportCompatBundle(inspection:CompatInspection):string {return JSON.stringify({schema_version:1,format:'register-compatibility-bundle',inspection,pdk:inspection.pdk??null,losses:inspection.unsupported,execution:{native:false,vendor_verified:false}},null,2)+'\n';}
/** Existing parsePdkLayers can consume the top-level layers. The original source
 * and ignored data stay embedded so display normalization is not a silent loss. */
export function exportNormalizedPdk(inspection:CompatInspection):string {if(!inspection.pdk)throw new Error('명시적 GDS 대응이 있는 PDK 표시 데이터가 필요합니다.');return JSON.stringify({...inspection.pdk,schema_version:1,format:'register-normalized-pdk-display',compatibility:{format:inspection.format,support:inspection.support,source:inspection.source,companion_sources:inspection.companion_sources??[],diagnostics:inspection.diagnostics,unsupported:inspection.unsupported},native_execution:false,vendor_verified:false},null,2)+'\n';}
