import {spawn} from 'node:child_process';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const p=spawn('docker',['exec','mos-studio-eda','python3','/workspace/workers/eda/test_cpu16.py'],{stdio:'inherit',windowsHide:true});
const code=await new Promise((resolve,reject)=>{p.once('error',reject);p.once('exit',resolve);});
if(code!==0)process.exit(code??1);
const r=JSON.parse(await readFile('docs/evidence/cpu16-native.json','utf8'));
if(r.case_count!==8||r.passed!==8)throw Error('Incomplete CPU16 evidence');
for(const [file,hash] of Object.entries(r.source_sha256))if(createHash('sha256').update(await readFile(file)).digest('hex')!==hash)throw Error('Evidence source differs: '+file);
console.log('16-bit structure / known values / actual ngspice / corruption regression: 8/8.');
