import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const config=JSON.parse(await fs.readFile('.runtime/worker.json','utf8'));
async function rpc(method,params={}) {const b=await (await fetch(config.url+'/rpc',{method:'POST',headers:{'content-type':'application/json','X-MOS-Token':config.token},body:JSON.stringify({method,params})})).json();assert.equal(b.ok,true,JSON.stringify(b.error));return b.result;}
async function wait(e) {for(let i=0;i<6000;i++){const r=await rpc('experiment.status',{experiment_id:e.id});if(!['queued','running'].includes(r.execution_status))return r;await new Promise(r=>setTimeout(r,200));}throw new Error('Experiment timeout');}
async function jobwait(r){for(let i=0;i<2000;i++){r=await rpc('job.status',{run_id:r.id});if(!['queued','running'].includes(r.execution_status))return r;await new Promise(r=>setTimeout(r,100));}}
const p=await rpc('project.create',{example:'mosfet',name:'Bounded real optimizer regression'});const evidence=[];
for(const [algorithm,trial_budget] of [['grid',3],['random',2],['tpe',4]]) {
  let e=await rpc('experiment.create',{project_id:p.id,algorithm,trial_budget,seed:47,variables:[{device_id:'mn1',parameter:'w_um',min:.65,max:1.3,steps:3}],objective:{metric:'Id_max',goal:'maximize'}});
  e=await wait(await rpc('experiment.evaluate',{experiment_id:e.id}));assert.equal(e.execution_status,'completed',e.message);assert.equal(e.trials.length,trial_budget);
  for(const trial of e.trials){assert.equal(trial.execution_status,'completed',trial.reason);assert.equal(trial.feasible,true,trial.reason);assert.ok(trial.score>0);assert.equal(trial.runs.length,3);assert.ok(trial.runs.every(r=>r.execution_status==='completed'&&r.analysis_result==='pass'));assert.equal(trial.measurements.Id_max,trial.score);assert.equal(trial.candidate_project_id,trial.project_id);}
  const compare=await rpc('experiment.compare',{experiment_id:e.id});assert.equal(compare.trials.length,trial_budget);assert.equal(compare.best_trial_id,e.best_trial_id);assert.ok(compare.trials[0].score>=compare.trials.at(-1).score);
  if(algorithm==='grid'){assert.equal(compare.trials[0].parameters.w_um,1.3);assert.ok(compare.trials[0].score>compare.trials.at(-1).score*1.5);}
  assert.equal((await rpc('project.open',{project_id:p.id})).revision,1);
  evidence.push({case:algorithm,result:'pass',experiment:e,comparison:compare});console.log(algorithm+': '+trial_budget+' actual gated trials PASS');
}
let e=await rpc('experiment.create',{project_id:p.id,algorithm:'grid',trial_budget:1,variables:[{device_id:'mn1',parameter:'w_um',min:.65,max:1.3}],objective:{metric:'Id_max',goal:'maximize'},constraints:[{metric:'Id_max',op:'<=',value:0}]});e=await wait(await rpc('experiment.evaluate',{experiment_id:e.id}));assert.equal(e.trials[0].feasible,false);assert.equal(e.trials[0].score,null);assert.equal((await rpc('experiment.compare',{experiment_id:e.id})).best_trial_id,null);evidence.push({case:'failed actual objective constraint is infeasible',result:'pass',experiment:e});
const canceled=await rpc('experiment.create',{project_id:p.id,algorithm:'random',trial_budget:16,variables:[{device_id:'mn1',parameter:'w_um',min:.65,max:1.3}],objective:{metric:'Id_max',goal:'maximize'}});assert.equal((await rpc('experiment.cancel',{experiment_id:canceled.id})).execution_status,'canceled');assert.equal((await rpc('experiment.evaluate',{experiment_id:canceled.id})).execution_status,'canceled');assert.equal((await rpc('experiment.status',{experiment_id:canceled.id})).trials.length,0);evidence.push({case:'queued experiment cancel runs no engines',result:'pass'});
const inverter=await rpc('project.create',{example:'inverter',name:'Actual Xschem simulation bridge'});const x=await rpc('schematic.netlist_xschem',{project_id:inverter.id});assert.match(x.text,/sky130_fd_pr__nfet_01v8/);let r=await jobwait(await rpc('simulation.run',{project_id:inverter.id,analysis:'tran',netlister:'xschem'}));assert.equal(r.execution_status,'completed',r.message);assert.equal(r.analysis_result,'pass');assert.ok(r.artifacts.xschem_manifest);evidence.push({case:'actual Xschem output simulated in ngspice',result:'pass',run_id:r.id,manifest_path:r.manifest_path,xschem_manifest:x.manifest_path});
r=await jobwait(await rpc('extraction.run_pex',{project_id:inverter.id}));assert.equal(r.execution_status,'completed',r.message);const mapping=await rpc('extraction.get_net_mapping',{project_id:inverter.id,run_id:r.id});assert.equal(mapping.elements.filter(e=>e.kind==='R').length,r.parasitics.resistors);assert.equal(mapping.elements.filter(e=>e.kind==='C').length,r.parasitics.capacitors);assert.ok(mapping.elements.every(e=>Number.isFinite(e.value)&&e.value>=0&&!e.shape_ids));evidence.push({case:'actual native RC table counts and SI units',result:'pass',run_id:r.id,elements:mapping.elements.length});
await fs.writeFile('.runtime/evidence/optimizer.json',JSON.stringify(evidence,null,2));console.log('optimizer/Xschem/RC regressions PASS');
