import { test, expect } from '@playwright/test';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import type { BackendManifest, Project, Run } from '../../packages/contracts/src/index';

test.setTimeout(180000);
const qa = 'packages/ui/qa';
const missingManifest = (id: string): BackendManifest => ({ schema_version: 1, id, name: '설치 대기 Spectre', version: 'operator-install-later', tool_id: 'spectre', runner: { kind: 'local', executable: '/opt/register-not-installed/bin/spectre', env_names: ['CDS_LIC_FILE'], resources: {}, recipes: { simulation: { argv: ['{input.netlist}'], outputs: {}, requires_netlist: true, timeout_s: 30 } } } });
const loadManifest = async (page: import('@playwright/test').Page, manifest: BackendManifest, name: string) => { await page.getByTestId('backend-step-1').click(); await page.getByTestId('backend-new-profile').click(); await page.getByTestId('backend-manifest-file').setInputFiles({ name, mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(manifest)) }); await expect(page.getByTestId('backend-manifest-filename')).toHaveText(name); };
const projectAction = async (page: import('@playwright/test').Page, method: string, testId: string) => {
  const pending = page.waitForResponse(response => response.url().includes('/api/rpc') && response.request().postDataJSON()?.method === method);
  await page.getByTestId(testId).click(); const body = await (await pending).json(); expect(body.ok).toBe(true); const project = body.result as Project;
  expect(Number.isInteger(project.revision)).toBe(true); await expect(page.getByTestId('backend-project')).toContainText(`${project.id} · r${project.revision}`); return project;
};

test('zero-RPC local GDS → actual commercial catalogue → unavailable vendor profile and native inputs', async ({ page }) => {
  await mkdir(qa, { recursive: true }); const requests: { method: string; params: Record<string, unknown> }[] = [], errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message)); page.on('request', request => { if (request.url().includes('/api/rpc')) requests.push(JSON.parse(request.postData() || '{}')); });
  await page.goto('/?mode=viewer'); await page.getByTestId('viewer-gds-input').setInputFiles('examples/sky130/mosfet.gds'); await expect(page.getByTestId('viewer-export')).toBeEnabled(); expect(requests).toHaveLength(0);
  await page.getByTestId('viewer-commercial-backend').click(); await expect(page.locator('.cb-catalog article')).toHaveCount(18, { timeout: 45000 });
  const toolIds = await page.locator('.cb-catalog article').evaluateAll(entries => entries.map(entry => entry.getAttribute('data-tool-id')));
  expect(toolIds).toEqual(expect.arrayContaining(['virtuoso', 'spectre', 'assura', 'pegasus', 'quantus', 'custom_compiler', 'primesim', 'hspice', 'icv', 'starrc', 'icc', 'icc2', 'fusion_compiler', 'calibre_drc', 'calibre_lvs', 'calibre_xact', 'innovus', 'ngspice']));
  const id = `ui-unavailable-spectre-${Date.now()}`; await loadManifest(page, missingManifest(id), 'site-spectre.backend-manifest.json'); await expect(page.getByTestId('backend-executable')).toHaveValue('/opt/register-not-installed/bin/spectre'); await page.getByTestId('backend-register').click();
  await expect(page.getByTestId('backend-profile-status')).toContainText('실행 불가', { timeout: 45000 }); await expect(page.locator('.cb-checks [data-check-status=fail]')).toHaveCount(1); await page.getByTestId('backend-validate').click(); await expect(page.getByTestId('backend-state')).toContainText('실행 불가', { timeout: 30000 });
  await page.screenshot({ path: `${qa}/register-commercial-profile-unavailable.png` });
  await page.getByTestId('backend-step-2').click(); await projectAction(page, 'layout.import', 'backend-import-source');
  const netlist = 'simulator lang=spectre\n// User-supplied proprietary native data; never converted to ngspice\nV1 (in 0) vsource dc=1.2\nR1 (in 0) resistor r=1000\n';
  await page.getByTestId('backend-netlist-file').setInputFiles({ name: 'actual-user-input.scs', mimeType: 'text/plain', buffer: Buffer.from(netlist) }); await expect(page.getByTestId('backend-netlist')).toHaveValue(netlist); await page.getByTestId('backend-parameters').fill('{"threads":2}'); await expect(page.getByTestId('backend-save')).toBeDisabled();
  const pending = page.waitForEvent('download'); await page.getByTestId('backend-setup-export').click(); await (await pending).saveAs(`${qa}/unavailable-spectre.backend-setup.json`); const setup = JSON.parse(await readFile(`${qa}/unavailable-spectre.backend-setup.json`, 'utf8')); expect(setup.settings.netlist_text).toBe(netlist); expect(setup.settings.parameters).toEqual({ threads: 2 }); expect(setup.settings).not.toHaveProperty('backend_fingerprint');
  await page.getByTestId('backend-step-3').click(); await expect(page.getByTestId('backend-run')).toBeDisabled(); await expect(page.getByTestId('backend-job-row')).toHaveCount(0); expect(requests.some(request => ['backend.run', 'simulation.run', 'analysis.run'].includes(request.method))).toBe(false);
  await page.setViewportSize({ width: 1280, height: 640 }); await expect.poll(async () => { const footer = await page.locator('.cb-footer').boundingBox(); return !!footer && footer.y >= 0 && footer.y + footer.height <= 640; }).toBe(true); await page.screenshot({ path: `${qa}/register-commercial-unavailable.png` }); expect(errors).toEqual([]);
  await writeFile(`${qa}/commercial-backend-ui.json`, JSON.stringify({ evidence: 'actual-worker-unavailable-vendor-profile', zero_rpc_before_explicit_action: true, catalogue_tool_ids: toolIds, registered_unavailable_profile: id, nonexistent_executable_rejected_by_live_validation: true, original_GDS_explicit_separate_upload: true, native_spectre_text_preserved_without_conversion: true, unavailable_save_and_run_disabled: true, no_vendor_job_launched: true, footer_visible_at_1280x640: true, browser_errors: errors }, null, 2));
});

test('operator local runner rejects shell binaries and raw credential fields; agent uses token file reference', async ({ page }) => {
  await page.goto('/?mode=viewer'); await page.getByTestId('viewer-commercial-backend').click(); await expect(page.locator('.cb-catalog article')).toHaveCount(18, { timeout: 45000 });
  const wrong = missingManifest(`ui-wrong-binary-${Date.now()}`); wrong.runner.executable = '/usr/bin/bash'; await loadManifest(page, wrong, 'wrong-binary.json'); await page.getByTestId('backend-register').click(); await expect(page.getByTestId('backend-error')).toContainText('UNSUPPORTED_EXECUTABLE', { timeout: 30000 });
  await page.getByTestId('backend-manifest-json').fill(JSON.stringify({ ...wrong, runner: { kind: 'agent', url: 'https://licensed-host.invalid', token: '', profile_id: 'site-profile' } })); await page.getByTestId('backend-register').click(); await expect(page.getByTestId('backend-error')).toContainText('비밀 값');
  const agent: BackendManifest = { schema_version: 1, id: `ui-unavailable-agent-${Date.now()}`, name: '설치 대기 licensed agent', version: 'operator-install-later', tool_id: 'spectre', runner: { kind: 'agent', url: 'https://licensed-host.invalid', token_file: '/workspace/private/register-not-configured.token', profile_id: 'site-profile' } };
  await page.getByTestId('backend-manifest-json').fill(JSON.stringify(agent, null, 2)); await expect(page.getByTestId('backend-agent-token_file')).toHaveValue('/workspace/private/register-not-configured.token'); await expect(page.locator('input[type=password]')).toHaveCount(0); await page.getByTestId('backend-register').click(); await expect(page.getByTestId('backend-profile-status')).toContainText('실행 불가', { timeout: 30000 }); await expect(page.locator('.cb-checks')).toContainText('token file'); await page.getByTestId('backend-step-3').click(); await expect(page.getByTestId('backend-run')).toBeDisabled();
  const evidence = JSON.parse(await readFile(`${qa}/commercial-backend-ui.json`, 'utf8')); evidence.operator_rejection = { live_shell_executable_rejected: true, raw_credential_field_rejected_before_RPC: true, missing_agent_token_file_unavailable: true, secret_value_inputs: 0 }; await writeFile(`${qa}/commercial-backend-ui.json`, JSON.stringify(evidence, null, 2));
});

// A proven open-source transport calibration profile may be supplied by native QA.
// This never stands in for a licensed Spectre/HSPICE run.
test('actual open-source calibration saves/reopens input and downloads the exact completed run', async ({ page }) => {
  const file = process.env.REGISTER_UI_CALIBRATION_MANIFEST; test.skip(!file, 'Native calibration manifest not supplied; vendor installation remains unverified.');
  await page.goto('/?mode=viewer'); await page.getByTestId('viewer-commercial-backend').click(); await expect(page.locator('.cb-catalog article')).toHaveCount(18, { timeout: 45000 });
  const manifest = JSON.parse(await readFile(file!, 'utf8')) as BackendManifest; await loadManifest(page, manifest, 'open-source-calibration.json'); await page.getByTestId('backend-register').click(); await expect(page.getByTestId('backend-profile-status')).toContainText('리소스 사용 가능', { timeout: 45000 });
  await page.getByTestId('backend-step-2').click(); await projectAction(page, 'project.create', 'backend-create-project');
  // This calibration executes its pinned operator resource deck. Do not replay
  // that trusted .control deck through the separate safe user-netlist input.
  await page.getByTestId('backend-save').click(); await expect(page.getByTestId('backend-state')).toContainText('Backend 설정 저장됨', { timeout: 45000 });
  const original = '* User native data retained separately from pinned open-source calibration recipe\n'; await page.getByTestId('backend-netlist').fill(original); await page.getByTestId('backend-save').click(); await expect(page.getByTestId('backend-state')).toContainText('Backend 설정 저장됨', { timeout: 45000 });
  await page.getByTestId('backend-netlist').fill('* unsaved draft\n'); await page.getByTestId('backend-reset').click(); await expect(page.getByTestId('backend-netlist')).toHaveValue(original);
  const setupPending = page.waitForEvent('download'); await page.getByTestId('backend-setup-export').click(); await (await setupPending).saveAs(`${qa}/commercial-calibration.backend-setup.json`); const exported = JSON.parse(await readFile(`${qa}/commercial-calibration.backend-setup.json`, 'utf8')); expect(exported.settings).not.toHaveProperty('backend_fingerprint'); await page.getByTestId('backend-setup-file').setInputFiles(`${qa}/commercial-calibration.backend-setup.json`); await expect(page.getByTestId('backend-state')).toContainText('설정 입력을 가져왔습니다.');
  await page.getByTestId('backend-step-1').click(); await page.getByTestId('backend-validate').click(); await expect(page.getByTestId('backend-state')).toContainText('검증 통과', { timeout: 45000 }); await page.getByTestId('backend-step-2').click(); await page.getByTestId('backend-save').click(); await expect(page.getByTestId('backend-state')).toContainText('Backend 설정 저장됨', { timeout: 45000 });
  await page.getByTestId('backend-step-3').click(); const previous = await page.getByTestId('backend-job-row').count(); await page.getByTestId('backend-run').click(); await expect(page.getByTestId('backend-job-row')).toHaveCount(previous + 1, { timeout: 45000 }); const row = page.getByTestId('backend-job-row').last(), id = await row.getAttribute('data-run-id'); await expect(row).toContainText('completed · pass', { timeout: 90000 }); await row.click(); const pending = page.waitForEvent('download'); await page.getByTestId('backend-result-json').click(); await (await pending).saveAs(`${qa}/commercial-calibration-run.json`); const run = JSON.parse(await readFile(`${qa}/commercial-calibration-run.json`, 'utf8')) as Run; expect(run.id).toBe(id); expect(run.workflow).toBe('commercial-backend'); expect(run.tool).toBe('ngspice'); expect(run.execution_status).toBe('completed'); expect(run.analysis_result).toBe('pass'); expect(run.waveforms?.[0].y[0]).toBeCloseTo(1, 6); expect(run.current_flow?.branches.map(branch => branch.values_A[0])).toEqual([-0.001, 0.001]);
  const artifactPending = page.waitForEvent('download'); await page.getByTestId('backend-artifact-currents').click(); await (await artifactPending).saveAs(`${qa}/commercial-calibration-currents.dat`); expect(await readFile(`${qa}/commercial-calibration-currents.dat`, 'utf8')).toContain('1.00000000e-03');
  await page.screenshot({ path: `${qa}/register-commercial-calibration.png` });
  await page.getByRole('dialog').getByRole('button', { name: '닫기', exact: true }).click(); await expect(page.getByTestId('viewer-geometry-unverified')).toContainText('물리적 대응 미검증'); await page.getByTestId('viewer-commercial-backend').click(); await page.getByTestId('backend-step-2').click(); await expect(page.getByTestId('backend-netlist')).toHaveValue(original); await page.getByTestId('backend-step-3').click(); await expect(page.getByTestId('backend-job-row')).toHaveCount(1);
  const evidence = JSON.parse(await readFile(`${qa}/commercial-backend-ui.json`, 'utf8')); evidence.focused_suite = { passed: 3, failed: 0, verified_at: new Date().toISOString(), calibration_is_not_vendor_execution: true }; evidence.actual_open_source_calibration = { id: run.id, tool: run.tool, result: run.analysis_result, V_out: run.waveforms![0].y[0], branch_currents_A: run.current_flow!.branches.map(branch => branch.values_A[0]), actual_artifact_download: true, saved_input_reset_resave_and_JSON_reimport: true, saved_history_reopened: true, geometry_correspondence_unverified_label: true, vendor_execution: false }; await writeFile(`${qa}/commercial-backend-ui.json`, JSON.stringify(evidence, null, 2));
});
