import {test,expect} from '@playwright/test';
import {mkdir,writeFile,copyFile} from 'node:fs/promises';
import type {Project,Run,Scene} from '../../packages/contracts/src/index';
test.use({video:{mode:'on',size:{width:1600,height:1000}},trace:'on'});
test('recorded real UI: adder, hierarchy clipboard/whole preview/approval/undo, programmable CPU, save/reopen',async({page,request},info)=>{
  test.setTimeout(1080000);const start=Date.now(),steps:{at_s:number;action:string}[]=[],projects:Project[]=[],runs:Run[]=[],errors:string[]=[];
  page.on('pageerror',e=>errors.push(e.message));
  const step=async(action:string,fn:()=>Promise<void>)=>{steps.push({at_s:(Date.now()-start)/1000,action});await test.step(action,fn);await page.screenshot({path:info.outputPath(`step-${steps.length.toString().padStart(2,'0')}.png`)});};
  const call=async<T,>(method:string,params={}):Promise<T>=>{const r=await request.post('/api/rpc',{data:{method,params},timeout:65000});const v=await r.json();expect(v.ok,v.error?.message).toBe(true);return v.result;};
  const response=(method:string)=>page.waitForResponse(r=>new URL(r.url()).pathname==='/api/rpc'&&r.request().postDataJSON()?.method===method,{timeout:65000});
  const waitRun=async(id:string)=>{let r:Run;const deadline=Date.now()+360000;do{r=await call<Run>('job.status',{run_id:id});if(!['queued','running'].includes(r.execution_status))break;await page.waitForTimeout(800);}while(Date.now()<deadline);expect(r!.execution_status,r!.message).toBe('completed');expect(r!.analysis_result,r!.message).toBe('pass');runs.push(r!);};
  const create=async(kind:string,name:string)=>{await page.getByTestId('open-digital-workbench').click();await page.getByTestId(`digital-${kind}`).click();await page.getByLabel('디지털 설계 이름').fill(name);const p=response('digital.create'),r=response('simulation.run');await page.getByTestId('digital-create').click();const result=await(await p).json();expect(result.ok,result.error?.message).toBe(true);projects.push(result.result);const run=await(await r).json();expect(run.ok,run.error?.message).toBe(true);await expect(page.getByTestId('digital-workbench')).not.toBeVisible({timeout:65000});await waitRun(run.result.id);};
  try{
    await page.goto('/');await expect(page.getByTestId('app-ready')).toBeVisible();
    await step('1-bit full adder: create native transistor schematic + physical layout and simulate all 8 inputs',async()=>{await create('full_adder','내 전가산기 · 녹화 설계');await page.getByTestId('tab-simulation').click();await expect(page.getByTestId('unit-verification')).toContainText('8/8');});
    await step('Copy the actual hierarchy to the app clipboard',async()=>{await page.getByTestId('tab-schematic').click();await page.getByTestId('hierarchy-copy').click();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('register.hierarchy.clipboard')||'{}').cell)).toBe('full_adder');});
    await step('Parent wrapper: complete before/after preview; mask unchanged; approval required',async()=>{await page.getByTestId('open-hierarchy-transfer').click();await page.getByTestId('hierarchy-wrap').click();await page.getByLabel('상위 셀 이름').fill('MY_ADDER_CHIP');await expect(page.getByTestId('hierarchy-apply')).toBeDisabled();await page.getByTestId('hierarchy-preview').click();await expect(page.getByTestId('hierarchy-preview-result')).toContainText('유지');await expect(page.getByTestId('hierarchy-canvas-delta')).toBeVisible();await page.getByRole('button',{name:'현재',exact:true}).click();await page.getByRole('button',{name:'적용 후',exact:true}).click();await page.getByRole('button',{name:'변경 겹쳐 보기',exact:true}).click();});
    await step('Changing a parent name invalidates the old preview and approval',async()=>{await page.getByTestId('hierarchy-approve').check();await page.getByLabel('상위 셀 이름').fill('MY_ADDER_TOP');await expect(page.getByTestId('hierarchy-preview-result')).not.toBeVisible();await expect(page.getByTestId('hierarchy-apply')).toBeDisabled();await page.getByTestId('hierarchy-preview').click();await expect(page.getByTestId('hierarchy-preview-result')).toBeVisible();});
    await step('Approve the displayed parent and commit one revision',async()=>{await page.getByTestId('hierarchy-approve').check();await page.getByTestId('hierarchy-apply').click();await expect(page.getByTestId('hierarchy-transfer')).not.toBeVisible();await expect(page.locator('.project-breadcrumb')).toContainText('MY_ADDER_TOP');});
    await step('Undo and redo the approved hierarchy; original circuit and mask preserved',async()=>{await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.locator('.project-breadcrumb')).toContainText('full_adder');await page.getByRole('button',{name:'Redo',exact:true}).click();await expect(page.locator('.project-breadcrumb')).toContainText('MY_ADDER_TOP');});
    await step('Paste copied root as a separated child with explicit pin mapping and show whole native impact',async()=>{await page.getByTestId('tab-schematic').click();await page.getByTestId('open-hierarchy-transfer').click();await page.getByRole('button',{name:'복사한 계층 붙여넣기'}).click();await page.getByLabel('원본 셀').selectOption('full_adder');await page.getByLabel('복사 계층 이름').fill('SECOND_FA');await page.getByLabel('계층 X DBU').fill('1000000');await page.getByTestId('hierarchy-preview').click();await expect(page.getByTestId('hierarchy-preview-result')).toContainText('변화 있음');await page.getByTestId('hierarchy-approve').check();await page.getByTestId('hierarchy-apply').click();await expect(page.getByTestId('hierarchy-transfer')).not.toBeVisible();});
    await step('Four-bit ripple adder: real 512 combinations and reusable FA child cells',async()=>{await create('adder4','내 4비트 가산기 · 녹화 설계');await page.getByTestId('tab-simulation').click();await expect(page.getByTestId('unit-verification')).toContainText('512/512');expect(projects[1].schematic.devices.filter(d=>d.kind==='block')).toHaveLength(4);});
    await step('Programmable four-bit CPU: native physical reference and all 16 clocked instructions',async()=>{await create('cpu4','내 4비트 CPU · 녹화 설계');await page.getByTestId('tab-simulation').click();await expect(page.getByTestId('unit-verification')).toContainText('16/16');await expect(page.getByTestId('unit-verification')).toContainText('LOAD 3');});
    await step('Inspect full CPU schematic, layout 2D and native batched 3D viewer',async()=>{await page.getByTestId('tab-schematic').click();await page.getByTestId('tab-layout2d').click();await expect(page.getByTestId('layout-viewer-2d')).toBeVisible();const count=Number(await page.getByTestId('scene-loaded-count').getAttribute('data-count'));expect(count).toBeGreaterThan(1000);await page.getByTestId('tab-layout3d').click();await expect(page.getByTestId('layout-viewer-3d')).toBeVisible();await expect(page.getByTestId('layout-viewer-3d').locator('canvas')).toHaveAttribute('data-visible-shapes',String(count),{timeout:90000});});
    await step('Save CPU, reload the app and verify the real execution is retained',async()=>{await page.getByTestId('project-save').click();await page.reload();await expect(page.getByTestId('app-ready')).toBeVisible();await expect(page.locator('.project-breadcrumb strong')).toHaveText(projects[2].name);await page.getByTestId('tab-simulation').click();await expect(page.getByTestId('unit-verification')).toContainText('16/16');});
    const scene=await call<Scene>('view.get_scene',{project_id:projects[2].id,max_shapes:100000});expect(scene.truncated).toBe(false);expect(scene.total_shape_count).toBeGreaterThan(1000);expect(errors).toEqual([]);
    await mkdir('examples/cpu4',{recursive:true});
    for(const p of projects){const bundle=await call<{bundle_base64:string}>('project.export_bundle',{project_id:p.id,revision:p.revision,inline:true});await writeFile(`examples/cpu4/${p.digital_unit!.kind}.register-project.zip`,Buffer.from(bundle.bundle_base64,'base64'));}
    await writeFile('examples/cpu4/ui-workflow.json',JSON.stringify({started_at:new Date(start).toISOString(),steps,project_ids:projects.map(p=>p.id),runs:runs.map(r=>({id:r.id,kind:r.kind,verification:r.unit_verification,status:r.execution_status,result:r.analysis_result})),cpu_scene_shapes:scene.total_shape_count,whole_scene:true,browser_errors:errors,video_scope:'Actual local app UI actions; development terminal commands are not screen captured; old pre-disconnection frames are separate.'},null,2));
  }finally{await mkdir('examples/cpu4/recording',{recursive:true});await writeFile('examples/cpu4/recording/chapters.json',JSON.stringify({start:new Date(start).toISOString(),steps,errors},null,2));const video=page.video();await page.close();if(video)await video.saveAs('examples/cpu4/recording/design-workflow.webm');}
});
