import { test, expect, type Page } from '@playwright/test';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import type { CompatibilityImportResult, CompatibilityReport, Run } from '../../packages/contracts/src/index';

test.setTimeout(180000);
const qa = 'packages/ui/qa', fixtures = 'tests/commercial/interchange';
const select = (page: Page, name: string) => page.getByTestId('interchange-file-row').filter({ hasText: name }).click();
const response = (page: Page, method: string) => page.waitForResponse(value => value.url().includes('/api/rpc') && value.request().postDataJSON()?.method === method);
async function download(page: Page, testId: string, name: string) { const pending = page.waitForEvent('download'); await page.getByTestId(testId).click(); await (await pending).saveAs(`${qa}/${name}`); return await readFile(`${qa}/${name}`); }
async function openResults(page: Page) { const summary = page.locator('.ix-native > details').filter({ has: page.locator('summary', { hasText: '외부 해석 / DRC / LVS / PEX 결과 파일' }) }).locator(':scope > summary'); if (!await page.getByTestId('interchange-result-file').isVisible()) await summary.click(); }
async function configureCsv(page: Page) {
  await page.getByTestId('interchange-result-file').selectOption('currents.csv'); await page.getByTestId('interchange-result-role').selectOption('currents'); await page.getByTestId('interchange-result-analysis').selectOption('dc'); await page.getByLabel('결과 X열', { exact: true }).selectOption('sweep_V'); await page.getByLabel('결과 X단위', { exact: true }).selectOption('V');
  await page.getByTestId('interchange-add-signal').click(); await page.getByLabel('Signal 1 column').selectOption('voltage_mV'); await page.getByLabel('Signal 1 name').fill('OUT'); await page.getByLabel('Signal 1 unit').selectOption('mV'); await page.getByTestId('interchange-add-current').click(); await page.getByLabel('전류 1 column').selectOption('current_mA'); await page.getByLabel('전류 1 name').fill('ID'); await page.getByLabel('전류 1 from_net').fill('D'); await page.getByLabel('전류 1 to_net').fill('S'); await page.getByLabel('전류 1 unit').selectOption('mA');
}

test('local technology, stream map, DRF, libraries and editable CDL inspect without RPC', async ({ page }) => {
  await mkdir(qa, { recursive: true }); const requests: string[] = [], errors: string[] = []; page.on('request', request => { if (/\/api\/rpc|\/rpc\/events|\/auth\//.test(request.url())) requests.push(request.url()); }); page.on('pageerror', error => errors.push(error.message));
  await page.goto('/?mode=viewer'); await page.getByTestId('viewer-gds-input').setInputFiles('examples/sky130/wire.gds'); await expect(page.getByTestId('viewer-export')).toBeEnabled(); await page.getByTestId('viewer-interchange').click(); await page.getByTestId('interchange-source').selectOption('virtuoso');
  const mapping = (await readFile(`${fixtures}/fixture.layermap`, 'utf8')).replace('17 0', '68 20').replace('17 16', '68 16');
  const metadataFiles = await Promise.all(['fixture.tf', 'display.drf', 'cds.lib', 'lib.defs', 'fixture.cdl'].map(async name => ({ name, mimeType: 'text/plain', buffer: await readFile(`${fixtures}/${name}`) })));
  await page.getByTestId('interchange-files').setInputFiles([...metadataFiles, { name: 'explicit-wire.layermap', mimeType: 'text/plain', buffer: Buffer.from(mapping) }]);
  await expect(page.getByTestId('interchange-file-row')).toHaveCount(6); await select(page, 'fixture.tf'); await page.getByTestId('interchange-tab-metadata').click(); await expect(page.getByTestId('interchange-tech-layers')).toContainText('metal1'); await expect(page.getByTestId('interchange-tech-layers')).toContainText('100'); await expect(page.getByTestId('interchange-stream-map')).toContainText('68 / 20'); await expect(page.getByTestId('interchange-unsupported')).toContainText('include');
  const normalized = JSON.parse((await download(page, 'interchange-export-layers', 'interchange-pdk.layers.json')).toString()); expect(normalized.layers.find((layer: { id: string }) => layer.id === '68/20').color).toBe('#ff0000'); expect(normalized.compatibility.unsupported.length).toBeGreaterThan(0); await page.getByTestId('interchange-apply-layers').click();
  await select(page, 'cds.lib'); await expect(page.getByTestId('interchange-library-refs')).toContainText('$PDK_ROOT/libs/demo'); await expect(page.getByTestId('interchange-library-refs')).not.toContainText('discarded'); await select(page, 'fixture.cdl'); await expect(page.getByTestId('interchange-subcircuits')).toContainText('OUT · IN · VDD · VSS');
  const original = await readFile(`${fixtures}/fixture.cdl`); await page.getByTestId('interchange-edit-text').fill(original.toString().replace('R1 OUT VSS 1k', 'R1 OUT VSS 2k')); await page.getByTestId('interchange-reinspect-text').click(); await expect(page.getByTestId('interchange-edit-text')).toContainText('R1 OUT VSS 2k'); await page.getByTestId('interchange-tab-files').click(); const restored = await download(page, 'interchange-original-download', 'interchange-original.cdl'); expect(createHash('sha256').update(restored).digest('hex')).toBe(createHash('sha256').update(original).digest('hex')); expect((await download(page, 'interchange-working-download', 'interchange-edited.cdl')).toString()).toContain('R1 OUT VSS 2k');
  await page.getByTestId('interchange-tab-metadata').click(); const metadata = JSON.parse((await download(page, 'interchange-export-metadata', 'interchange-cdl.register-compat.json')).toString()); expect(metadata.inspection.source.text).toContain('shell echo never-executed'); expect(metadata.execution).toEqual({ native: false, vendor_verified: false }); await page.screenshot({ path: `${qa}/register-interchange-metadata.png` });
  await page.getByTestId('interchange-files').setInputFiles(`${fixtures}/currents.csv`); await select(page, 'currents.csv'); await page.getByTestId('interchange-tab-native').click(); await openResults(page); await configureCsv(page); await page.getByTestId('interchange-preview-results').click(); await expect(page.getByTestId('interchange-result')).toContainText('브라우저에서 읽은 외부 파일 수치');
  await page.getByRole('dialog').getByRole('button', { name: '닫기', exact: true }).click(); const viewerBundle = JSON.parse((await download(page, 'viewer-export', 'interchange-wire.register-view.json')).toString()); expect(viewerBundle.scene.layers.find((layer: { id: string }) => layer.id === '68/20').color).toBe('#ff0000'); expect(viewerBundle.currentFlow.branches[0].values_A).toEqual([-.001,0,.001]); expect(viewerBundle.currentFlow.geometry_linkage).toBe('unverified'); await page.getByTestId('viewer-bundle-input').setInputFiles(`${qa}/interchange-wire.register-view.json`); await expect(page.getByTestId('viewer-geometry-unverified')).toContainText('물리적 대응 미검증'); expect(requests).toEqual([]); expect(errors).toEqual([]);
  await writeFile(`${qa}/interchange-ui.json`, JSON.stringify({ local_inspection_without_rpc: true, native_import_export: false, external_current_samples: false, browser_errors: errors, metadata_grammar_fixture: true, public_GDS_source: 'examples/sky130/wire.gds', explicit_layer_color_applied: true, internal_layer_numbers_not_GDS: true, unsupported_source_preserved: true, original_CDL_sha256_preserved_after_edit: true, local_signed_current_and_portable_bundle_reopened: true, vendor_execution_verified: false }, null, 2));
});

test('actual native LEF DEF geometry and editable CDL import/export in new revisions', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); const source = await readFile('workers/eda/test_interchange.py', 'utf8'); const lef = /LEF='''([\s\S]*?)'''/.exec(source)![1], def = /DEF='''([\s\S]*?)'''/.exec(source)![1];
  const map = /^MAP=(\[[^\r\n]*\])/m.exec(source)![1]; const rows = JSON.parse(map.replaceAll("'", '"'));
  await page.goto('/?mode=viewer'); await page.getByTestId('viewer-interchange').click(); await page.getByTestId('interchange-source').selectOption('icc'); await page.getByTestId('interchange-files').setInputFiles([{ name: 'tech.lef', mimeType: 'text/plain', buffer: Buffer.from(lef) }, { name: 'design.def', mimeType: 'text/plain', buffer: Buffer.from(def) }]); await page.getByTestId('interchange-tab-native').click();
  await page.locator('.ix-layer-editor > details > summary').click(); await page.getByTestId('interchange-layer-map').fill(JSON.stringify(rows)); const inspectionResponse = response(page, 'compat.inspect'); await page.getByTestId('interchange-inspect-native').click(); const inspectionBody = await (await inspectionResponse).json(); expect(inspectionBody.ok).toBe(true); const inspection = inspectionBody.result as CompatibilityReport; expect(inspection.supported).toBe(true); await expect(page.getByTestId('interchange-import-native')).toBeEnabled();
  const importedResponse = response(page, 'compat.import'); await page.getByTestId('interchange-import-native').click(); const imported = (await (await importedResponse).json()).result as CompatibilityImportResult; await expect(page.getByTestId('interchange-project')).toContainText(`r${imported.project.revision}`); expect(imported.project.cell).toBe('CHIP'); const layout = imported.report.layout as { pins: { name: string }[]; instances: { name: string }[]; dbu_um: number }; expect(layout.dbu_um).toBe(.001); expect(layout.pins.map(pin => pin.name)).toEqual(expect.arrayContaining(['A', 'Y', 'IN', 'OUT']));
  await page.locator('.ix-native > details').filter({ has: page.locator('summary', { hasText: '프로젝트 표준 파일 / roundtrip 내보내기' }) }).locator(':scope > summary').click(); const gds = await download(page, 'interchange-export-gds', 'interchange-native.gds'); expect(gds.length).toBeGreaterThan(100); await expect(page.getByTestId('interchange-export-report')).toContainText('gds');
  await page.getByTestId('interchange-clear-files').click(); const cdl = '* User circuit data\n.SUBCKT TOP IN OUT VDD VSS\nR1 IN OUT 1k\n.ENDS TOP\n'; await page.getByTestId('interchange-files').setInputFiles({ name: 'design.cdl', mimeType: 'text/plain', buffer: Buffer.from(cdl) }); await page.getByTestId('interchange-tab-metadata').click(); await page.getByTestId('interchange-edit-text').fill(cdl.replace('1k', '2k')); await page.getByTestId('interchange-reinspect-text').click(); await page.getByTestId('interchange-tab-native').click(); await page.getByTestId('interchange-netlist-file').selectOption('design.cdl'); await page.getByTestId('interchange-netlist-top').fill('TOP'); const nextInspection = response(page, 'compat.inspect'); await page.getByTestId('interchange-inspect-native').click(); expect((await (await nextInspection).json()).ok).toBe(true); const nextImport = response(page, 'compat.import'); await page.getByTestId('interchange-import-native').click(); const next = (await (await nextImport).json()).result as CompatibilityImportResult; expect(next.project.id).toBe(imported.project.id); expect(next.project.revision).toBe(imported.project.revision + 1); expect(next.project.cell).toBe('CHIP');
  await page.locator('.ix-native > details').filter({ has: page.locator('summary', { hasText: '프로젝트 표준 파일 / roundtrip 내보내기' }) }).locator(':scope > summary').click(); expect((await download(page, 'interchange-export-cdl', 'interchange-native.cdl')).toString()).toContain('R1 IN OUT 2k'); const oas = await download(page, 'interchange-export-oas', 'interchange-native.oas'); expect(oas.length).toBeGreaterThan(100); await page.screenshot({ path: `${qa}/register-interchange-native.png` }); expect(errors).toEqual([]);
  const evidence = JSON.parse(await readFile(`${qa}/interchange-ui.json`, 'utf8')); Object.assign(evidence, { native_import_export: true, native_project_id: next.project.id, native_revision: next.project.revision, actual_LEF_DEF_pins: layout.pins.map(pin => pin.name), actual_layout_top: next.project.cell, actual_GDS_bytes: gds.length, actual_OAS_bytes: oas.length, safe_CDL_edit_apply_export: true }); await writeFile(`${qa}/interchange-ui.json`, JSON.stringify(evidence, null, 2));
});

test('explicit CSV units and signed currents preview locally and persist imported history', async ({ page }) => {
  const requests: string[] = [], errors: string[] = []; page.on('request', request => { if (request.url().includes('/api/rpc')) requests.push(request.url()); }); page.on('pageerror', error => errors.push(error.message)); await page.goto('/?mode=viewer'); await page.getByTestId('viewer-gds-input').setInputFiles('examples/sky130/wire.gds'); await page.getByTestId('viewer-interchange').click(); await page.getByTestId('interchange-source').selectOption('spectre'); await page.getByTestId('interchange-files').setInputFiles(`${fixtures}/currents.csv`); await page.getByTestId('interchange-tab-native').click(); await openResults(page); await configureCsv(page); await page.getByTestId('interchange-preview-results').click(); await expect(page.getByTestId('interchange-result')).toContainText('브라우저에서 읽은 외부 파일 수치'); const local = JSON.parse((await download(page, 'interchange-result-download', 'interchange-local-current.json')).toString()) as Run; expect(local.current_flow?.branches[0].values_A).toEqual([-.001, 0, .001]); expect(local.waveforms?.[0].y).toEqual([-1, 0, 1]); expect(requests).toEqual([]);
  const pending = response(page, 'compat.import_results'); await page.getByTestId('interchange-import-results').click(); const body = await (await pending).json(); expect(body.ok).toBe(true); const imported = body.result as Run; expect(imported.workflow).toBe('imported-results'); expect(imported.analysis_result).toBe('pass'); expect(imported.current_flow?.source).toBe('imported'); expect(imported.current_flow?.geometry_linkage).toBe('unverified'); expect(imported.current_flow?.branches[0].mapping).toBe('unmapped'); expect(imported.current_flow?.branches[0].values_A).toEqual([-.001, 0, .001]); await expect(page.getByTestId('interchange-history-row')).toHaveCount(1);
  await page.getByRole('dialog').getByRole('button', { name: '닫기', exact: true }).click(); await expect(page.getByTestId('viewer-geometry-unverified')).toContainText('물리적 대응 미검증'); await expect(page.getByTestId('viewer-current-source')).toContainText('외부 파일 · 엔진 실행 없음'); await expect(page.locator('canvas').first()).toHaveAttribute('data-current-arrow-count', '0'); await page.screenshot({ path: `${qa}/register-interchange-current.png` }); await page.getByTestId('viewer-interchange').click(); await page.getByTestId('interchange-tab-native').click(); await openResults(page); await expect(page.getByTestId('interchange-history-row')).toHaveCount(1); await page.getByTestId('interchange-history-row').click(); await expect(page.getByTestId('interchange-result')).toContainText(imported.id); expect(errors).toEqual([]);
  const evidence = JSON.parse(await readFile(`${qa}/interchange-ui.json`, 'utf8')); Object.assign(evidence, { external_current_samples: true, native_imported_run_id: imported.id, external_signed_A: [-.001, 0, .001], external_zero_preserved: true, explicit_mA_to_A_and_mV_to_V: true, local_current_preview_zero_rpc: true, imported_history_reopened: true, unmapped_physical_arrows_disabled: true, browser_errors: errors, focused_suite: { passed: 3, failed: 0 }, checked_at: new Date().toISOString() }); await writeFile(`${qa}/interchange-ui.json`, JSON.stringify(evidence, null, 2));
});
