import { clickWorkbenchAction } from './helpers/workbench';
import { test, expect, type Page, type APIRequestContext, type Request } from '@playwright/test';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import type { Project, Scene, PvtStudy, PvtSources, RoutingRules, RoutePreview, Run, DesignCatalog, DesignConnectivity } from '../../packages/contracts/src/index';

test.setTimeout(180000);
const qa = 'packages/ui/qa';
const response = (page: Page, method: string) => page.waitForResponse(item => item.url().includes('/api/rpc') && item.request().postDataJSON()?.method === method);
async function call<T>(request: APIRequestContext, method: string, params: Record<string, unknown>): Promise<T> { const result = await request.post('/api/rpc', { data: { method, params } }); const body = await result.json(); expect(body.ok, JSON.stringify(body.error)).toBe(true); return body.result as T; }
async function openProject(page: Page, request: APIRequestContext, example: string, name: string) { const project = await call<Project>(request, 'project.create', { name, example }); await page.addInitScript(id => localStorage.setItem('mos.last_project', id), project.id); await page.goto('/eda'); await expect(page.getByTestId('app-ready')).toBeVisible(); await expect(page.locator('.project-breadcrumb strong')).toHaveText(name); await expect(page.getByTestId('scene-loaded-count')).toBeVisible(); return project; }
async function download(page: Page, button: ReturnType<Page['getByRole']>, name: string) { const pending = page.waitForEvent('download'); await button.click(); const result = await pending; await result.saveAs(`${qa}/${name}`); return readFile(`${qa}/${name}`); }
async function evidence(values: Record<string, unknown>) { let saved: Record<string, unknown> = {}; try { saved = JSON.parse(await readFile(`${qa}/integrated-tools-ui.json`, 'utf8')); } catch {} await writeFile(`${qa}/integrated-tools-ui.json`, JSON.stringify({ ...saved, ...values, checked_at: new Date().toISOString() }, null, 2)); }
const close = (page: Page) => page.getByRole('dialog').getByRole('button', { name: '닫기', exact: true }).click();
function parseCsv(text: string) { const rows: string[][] = []; let row: string[] = [], cell = '', quoted = false; for (let index = 0; index < text.length; index++) { const char = text[index]; if (char === '"') { if (quoted && text[index + 1] === '"') { cell += '"'; index++; } else quoted = !quoted; } else if (char === ',' && !quoted) { row.push(cell); cell = ''; } else if ((char === '\n' || char === '\r') && !quoted) { if (char === '\r' && text[index + 1] === '\n') index++; row.push(cell); rows.push(row); row = []; cell = ''; } else cell += char; } if (cell || row.length) { row.push(cell); rows.push(row); } return rows; }

test('PVT stores exact native supply binding, executes two actual MOS corners, exports values and guards stale source', async ({ page, request }) => {
  test.setTimeout(360000); // Two native corner jobs, exports and revision guards share this budget.
  await mkdir(qa, { recursive: true }); const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const source = await openProject(page, request, 'mosfet', 'Integrated actual PVT MOS'); const calls: string[] = []; const track = (item: Request) => { if (item.url().includes('/api/rpc')) calls.push(item.postDataJSON()?.method); }; page.on('request', track);
  await clickWorkbenchAction(page, "open-integrated-tools"); await expect(page.getByTestId('integrated-tools')).toBeVisible(); const modalBounds = await page.getByRole('dialog').boundingBox(); expect(modalBounds!.width).toBeGreaterThan(1000); expect(modalBounds!.height).toBeLessThanOrEqual(950); await page.getByTestId('integrated-tab-routing').click(); await page.getByTestId('integrated-tab-design').click(); await page.getByTestId('integrated-tab-pvt').click(); expect(calls).toEqual([]); page.off('request', track);
  await page.getByTestId('pvt-create').click(); await expect(page.getByTestId('pvt-error')).toContainText('실제 공급원을 명시');
  const sourceRequest = response(page, 'pvt.sources'); await page.getByTestId('pvt-read-sources').click(); const sourceBody = await (await sourceRequest).json(); expect(sourceBody.ok).toBe(true); const bindings = sourceBody.result as PvtSources; expect(bindings.bindings).toContainEqual({ kind: 'testbench', source_names: ['VD'] }); await page.getByLabel('검증된 PVT 공급원').selectOption(String(bindings.bindings.findIndex(binding => binding.kind === 'testbench')));
  await page.getByLabel('PVT corners').fill('tt, ff'); await page.getByLabel('PVT temperatures').fill('27'); await page.getByLabel('PVT supplies').fill('1.8'); await page.getByLabel('PVT constraint metric').selectOption('Id_max'); await page.getByLabel('PVT constraint value').fill('0');
  const createRequest = response(page, 'pvt.create'); await page.getByTestId('pvt-create').click(); const saved = (await (await createRequest).json()).result as PvtStudy; expect(saved.execution_status).toBe('created'); expect(saved.source_revision).toBe(source.revision); expect(saved.config.supply).toEqual({ kind: 'testbench', source_names: ['VD'] }); await expect(page.getByTestId('pvt-point')).toHaveCount(2);
  await page.getByLabel('PVT temperatures').fill('28'); await expect(page.getByTestId('pvt-start')).toBeDisabled(); await page.getByRole('button', { name: '저장된 입력 복원', exact: true }).click(); await expect(page.getByTestId('pvt-start')).toBeEnabled();
  await page.getByTestId('pvt-start').click(); await page.getByTestId('integrated-tab-routing').click(); await page.getByTestId('integrated-tab-pvt').click(); await expect(page.getByTestId('pvt-point')).toHaveCount(2); for (let index = 0; index < 2; index++) { await expect(page.getByTestId('pvt-point').nth(index)).toContainText('completed', { timeout: 120000 }); await expect(page.getByTestId('pvt-point').nth(index)).toContainText('pass'); }
  const actual = JSON.parse((await download(page, page.getByRole('button', { name: '원본 결과 JSON', exact: true }), 'actual-mos.pvt.json')).toString()) as PvtStudy; expect(actual.execution_status).toBe('completed'); expect(actual.points.every(point => point.run_id && typeof point.metrics.Id_max === 'number')).toBe(true); expect(actual.points.map(point => point.condition.corner)).toEqual(['tt', 'ff']); const values = actual.points.map(point => point.metrics.Id_max as number); expect(values.every(value => value > 0)).toBe(true); expect((actual.summary!.Id_max as { min: number }).min).toBe(Math.min(...values)); expect((actual.summary!.Id_max as { max: number }).max).toBe(Math.max(...values)); await expect(page.getByTestId('pvt-summary')).toContainText('Id_max'); await expect(page.getByTestId('pvt-constraint-results')).toContainText('실제 모든 조건 수치 확인됨');
  const csv = (await download(page, page.getByTestId('pvt-export-csv'), 'actual-mos.pvt.csv')).toString(); const rows = parseCsv(csv); const metricIndex = rows[0].indexOf('Id_max'); expect(rows.slice(1).map(row => Number(row[metricIndex]))).toEqual(values);
  await page.getByTestId('pvt-point').first().getByRole('button').click(); await expect(page.getByTestId('pvt-run-detail')).toContainText(actual.points[0].run_id!); const run = JSON.parse((await download(page, page.getByRole('button', { name: 'Run JSON', exact: true }), 'actual-pvt-point.run.json')).toString()) as Run; expect(run.id).toBe(actual.points[0].run_id); expect(run.tool).toContain('ngspice'); expect(run.execution_status).toBe('completed'); await page.getByRole('button', { name: '실제 로그 읽기', exact: true }).click(); await expect(page.getByTestId('pvt-run-detail')).toContainText(/ngspice|Circuit|Title/); await page.screenshot({ path: `${qa}/register-integrated-pvt.png` });
  await close(page); const moved = await call<Project>(request, 'schematic.apply_command', { project_id: source.id, command: { type: 'move_device', id: source.schematic.devices[0].id, x: source.schematic.devices[0].x + 10, y: source.schematic.devices[0].y } }); expect(moved.revision).toBeGreaterThan(source.revision); await page.reload(); await expect(page.getByTestId('current-revision')).toContainText(String(moved.revision)); await clickWorkbenchAction(page, "open-integrated-tools"); await page.getByTestId('pvt-load').click(); await page.getByLabel('저장된 PVT 조건표').selectOption(actual.id); await expect(page.getByTestId('integrated-pvt').locator('.it-status.bad')).toContainText('stale'); await expect(page.getByTestId('pvt-start')).toBeDisabled(); expect(errors).toEqual([]);
  await evidence({ zero_rpc_before_explicit_action: true, actual_pvt: true, actual_pvt_study_id: actual.id, actual_pvt_source_revision: actual.source_revision, actual_pvt_point_run_ids: actual.points.map(point => point.run_id), actual_metric_Id_max_A: values, csv_matches_actual_values: true, actual_native_binding: actual.config.supply, dirty_and_stale_source_start_blocked: true, tabs_preserve_started_study: true, modal_width_px: modalBounds!.width, modal_height_px: modalBounds!.height, browser_errors: errors });
});

test('PDK route preview shows actual collision IDs and only applies unchanged explicit path before real DRC', async ({ page, request }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); const project = await openProject(page, request, 'wire', 'Integrated actual route wire'); const before = await call<Scene>(request, 'view.get_scene', { project_id: project.id, max_shapes: 2000 }); await clickWorkbenchAction(page, "open-integrated-tools"); await page.getByTestId('integrated-tab-routing').click();
  const rulesRequest = response(page, 'design.routing_rules'); await page.getByTestId('routing-load-rules').click(); const ruleBody = await (await rulesRequest).json(); expect(ruleBody.ok).toBe(true); const rules = ruleBody.result as RoutingRules; expect(rules.resources.every(resource => /^[0-9a-f]{64}$/.test(resource.sha256))).toBe(true); const layer = project.layers.find(item => item.gds[0] === 68 && item.gds[1] === 20)!; const rule = rules.layers.find(item => item.layer_id === layer.id)!; expect(rule).toBeTruthy(); await page.getByTestId('routing-layer').selectOption(layer.id);
  const polygon = before.shapes.find(shape => shape.layer_id === layer.id)!; const xs = polygon.polygon.map(point => BigInt(point[0])), ys = polygon.polygon.map(point => BigInt(point[1])); const min = (values: bigint[]) => values.reduce((a, b) => a < b ? a : b), max = (values: bigint[]) => values.reduce((a, b) => a > b ? a : b); const grid = BigInt(rule.grid_dbu), snap = (value: bigint) => value / grid * grid; const x = snap((min(xs) + max(xs)) / 2n), y = snap((min(ys) + max(ys)) / 2n);
  await page.getByLabel('시작 X DBU').fill(String(x)); await page.getByLabel('시작 Y DBU').fill(String(y)); await page.getByLabel('끝 X DBU').fill(String(x + 1000n)); await page.getByLabel('끝 Y DBU').fill(String(y + 1000n)); const collisionRequest = response(page, 'design.route_preview'); await page.getByTestId('routing-preview').click(); const collisionBody = await (await collisionRequest).json(); expect(collisionBody.ok).toBe(true); const collision = collisionBody.result as RoutePreview; expect(collision.valid).toBe(false); expect(collision.collisions.some(item => before.shapes.some(shape => shape.id === item.shape_id))).toBe(true); await expect(page.getByTestId('routing-collisions')).toContainText(collision.collisions[0].shape_id); await expect(page.getByTestId('routing-apply')).toBeDisabled();
  const sceneX = max(before.shapes.flatMap(shape => shape.polygon.map(point => BigInt(point[0])))), sceneY = max(before.shapes.flatMap(shape => shape.polygon.map(point => BigInt(point[1])))); const outsideX = snap(sceneX + 5000n), outsideY = snap(sceneY + 5000n); await page.getByLabel('시작 X DBU').fill(String(outsideX)); await page.getByLabel('시작 Y DBU').fill(String(outsideY)); await page.getByLabel('끝 X DBU').fill(String(outsideX + 1000n)); await page.getByLabel('끝 Y DBU').fill(String(outsideY + 1000n)); const previewRequest = response(page, 'design.route_preview'); await page.getByTestId('routing-preview').click(); const previewBody = await (await previewRequest).json(); expect(previewBody.ok).toBe(true); const preview = previewBody.result as RoutePreview; expect(preview.valid).toBe(true); expect(preview.rule_fingerprint).toBe(rules.fingerprint); await expect(page.getByTestId('routing-diagram')).toBeVisible(); await page.getByTestId('routing-apply-confirm').check(); await expect(page.getByTestId('routing-apply')).toBeEnabled(); await page.getByLabel('끝 X DBU').fill(String(outsideX + 1500n)); await expect(page.getByTestId('routing-apply')).toBeDisabled(); await page.getByLabel('끝 X DBU').fill(String(outsideX + 1000n)); await page.getByTestId('routing-apply-confirm').check(); const applyRequest = response(page, 'design.route_apply'); await page.getByTestId('routing-apply').click(); const applied = (await (await applyRequest).json()).result as Project; expect(applied.revision).toBeGreaterThan(project.revision); await expect(page.getByTestId('routing-notice')).toContainText(`r${applied.revision}`); const after = await call<Scene>(request, 'view.get_scene', { project_id: project.id, max_shapes: 2000 }); expect(after.shapes.length).toBeGreaterThan(before.shapes.length); await page.screenshot({ path: `${qa}/register-integrated-routing.png` }); await close(page);
  const drcRequest = response(page, 'verification.run_drc'); await page.getByTestId('run-drc').click(); const initialDrc = (await (await drcRequest).json()).result as Run; const row = page.getByTestId('job-row').filter({ hasText: 'drc' }).first(); await expect(row).toContainText('PASS', { timeout: 90000 }); const drc = await call<Run>(request, 'job.status', { run_id: initialDrc.id }); expect(drc.analysis_result).toBe('pass'); expect(drc.revision).toBe(applied.revision); expect(errors).toEqual([]);
  await writeFile(`${qa}/actual-route-preview.json`, JSON.stringify(preview, null, 2)); await evidence({ actual_route: true, actual_route_project_id: project.id, actual_route_revision: applied.revision, actual_PDK_rule_hash: rules.fingerprint, actual_collision_shape_ids: collision.collisions.map(item => item.shape_id), route_draft_change_apply_blocked: true, explicit_route_confirm_required: true, route_applied_geometry_count: after.shapes.length, actual_route_DRC_run_id: drc.id, actual_route_DRC: drc.analysis_result, browser_errors: errors });
});

test('RC template creates actual editable circuit, reports unmapped physical binding and executes native transient', async ({ page, request }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); await openProject(page, request, 'fixture', 'Integrated source preserved'); await clickWorkbenchAction(page, "open-integrated-tools"); await page.getByTestId('integrated-tab-design').click(); const catalogRequest = response(page, 'design.catalog'); await page.getByTestId('design-load-catalog').click(); const catalog = (await (await catalogRequest).json()).result as DesignCatalog; expect(catalog.templates.map(item => item.id)).toEqual(expect.arrayContaining(['rc_lowpass', 'common_source', 'common_source_bias', 'current_mirror', 'differential_pair'])); await page.getByTestId('design-template').selectOption('rc_lowpass'); await page.getByLabel('Template 프로젝트 이름').fill('Integrated actual RC lowpass'); await expect(page.getByTestId('design-create')).toBeDisabled(); await page.getByTestId('design-create-confirm').check(); const createRequest = response(page, 'design.create_template'); await page.getByTestId('design-create').click(); const resultBody = await (await createRequest).json(); expect(resultBody.ok).toBe(true); const project = resultBody.result as Project; expect(project.schematic.devices.some(device => device.kind === 'resistor')).toBe(true); expect(project.schematic.devices.some(device => device.kind === 'capacitor')).toBe(true); await expect(page.locator('.project-breadcrumb strong')).toHaveText(project.name); const geometry = await call<Scene>(request, 'view.get_scene', { project_id: project.id, max_shapes: 2000 }); expect(geometry.shapes).toHaveLength(0);
  const connectionRequest = response(page, 'design.connectivity'); await page.getByTestId('design-read-connectivity').click(); const connectionBody = await (await connectionRequest).json(); expect(connectionBody.ok).toBe(true); const connection = connectionBody.result as DesignConnectivity; expect(connection.nets.some(net => net.name === 'OUT')).toBe(true); await page.getByTestId('design-net-list').getByRole('button', { name: /OUT/ }).click(); await expect(page.getByTestId('design-pin-list')).toContainText('resistor'); await expect(page.getByTestId('design-pin-list')).toContainText('capacitor'); await expect(page.getByTestId('design-shape-list').getByRole('button')).toHaveCount(0); await expect(page.getByTestId('design-layout-binding')).toContainText(connection.layout_binding.status); await page.getByTestId('design-check').click(); await expect(page.getByTestId('design-issues')).toBeVisible(); await page.screenshot({ path: `${qa}/register-integrated-connectivity.png` });
  const pin = connection.nets.find(net => net.name === 'OUT')!.pins[0]; await page.getByTestId('design-pin-list').getByRole('button', { name: pin.device_name, exact: true }).click(); await expect(page.getByRole('dialog')).not.toBeVisible(); await expect(page.getByTestId('tab-schematic')).toHaveClass(/active/);
  const simulationRequest = response(page, 'simulation.run'); await page.getByTestId('run-simulation').click(); const started = (await (await simulationRequest).json()).result as Run; await expect(page.getByTestId('job-row').filter({ hasText: 'simulation' }).first()).toContainText('PASS', { timeout: 90000 }); const run = await call<Run>(request, 'job.status', { run_id: started.id }); expect(run.tool).toContain('ngspice'); expect(run.execution_status).toBe('completed'); expect(run.waveforms?.some(waveform => waveform.y.length > 1)).toBe(true); expect(errors).toEqual([]);
  await writeFile(`${qa}/actual-rc-template.run.json`, JSON.stringify(run, null, 2));
  await clickWorkbenchAction(page, "open-integrated-tools"); const sourcesRequest = response(page, 'pvt.sources'); await page.getByTestId('pvt-read-sources').click(); const sourceBody = await (await sourcesRequest).json(); expect(sourceBody.ok).toBe(true); const sources = sourceBody.result as PvtSources; expect(sources.analyses).toEqual(['tran']); expect(sources.bindings).toContainEqual({ kind: 'testbench', source_names: ['VIN'] }); await expect(page.getByLabel('PVT 해석')).toHaveValue('tran'); await page.getByLabel('검증된 PVT 공급원').selectOption(String(sources.bindings.findIndex(binding => binding.kind === 'testbench'))); await page.getByLabel('PVT corners').fill('tt'); await page.getByLabel('PVT supplies').fill('1.2, 1.8'); await page.getByLabel('PVT metric 1 이름').fill('tau_s'); await page.getByLabel('PVT metric 1 key').fill('measured_tau_s'); const savedRequest = response(page, 'pvt.create'); await page.getByTestId('pvt-create').click(); const savedBody = await (await savedRequest).json(); expect(savedBody.ok).toBe(true); await page.getByTestId('pvt-start').click(); await expect(page.getByTestId('pvt-point')).toHaveCount(2); for (let index = 0; index < 2; index++) await expect(page.getByTestId('pvt-point').nth(index)).toContainText('completed', { timeout: 120000 }); const pvt = JSON.parse((await download(page, page.getByRole('button', { name: '원본 결과 JSON', exact: true }), 'actual-rc-template.pvt.json')).toString()) as PvtStudy; expect(pvt.points.every(point => point.run_id && typeof point.metrics.tau_s === 'number' && point.metrics.tau_s > 0)).toBe(true); expect(pvt.config.supply).toEqual({ kind: 'testbench', source_names: ['VIN'] }); expect(pvt.config.analysis).toBe('tran'); const pvtCsv = (await download(page, page.getByTestId('pvt-export-csv'), 'actual-rc-template.pvt.csv')).toString(); expect(pvtCsv).toContain('tau_s'); await page.screenshot({ path: `${qa}/register-integrated-template-pvt.png` }); expect(errors).toEqual([]);
  await evidence({ actual_template: true, actual_template_id: 'rc_lowpass', actual_template_project_id: project.id, actual_template_initial_shapes: geometry.shapes.length, no_invented_physical_layout: true, actual_connectivity_net_names: connection.nets.map(net => net.name), actual_layout_binding_status: connection.layout_binding.status, selected_resolved_root_device_id: pin.device_id, actual_RC_ngspice_run_id: run.id, actual_RC_transient_samples: run.waveforms?.[0]?.y.length, actual_template_PVT_study_id: pvt.id, actual_template_PVT_run_ids: pvt.points.map(point => point.run_id), actual_template_PVT_tau_s: pvt.points.map(point => point.metrics.tau_s), actual_template_PVT_supplies_V: pvt.points.map(point => point.condition.supply_V), browser_errors: errors, focused_suite: { passed: 3, failed: 0 } });
});
