import { test, expect, type Page } from '@playwright/test';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { parseMappedResultText } from '../../packages/importer/src/compat';
import { exportReviewSnapshot } from '../../packages/viewer/src/review';
import { createHash } from 'node:crypto';
import type { CurrentFlow, DatabaseCatalog, DatabaseRead, DatabaseImportResult, Scene } from '../../packages/contracts/src/index';

test.setTimeout(150000);
const qa = 'packages/ui/qa';
async function download(page: Page, button: ReturnType<Page['getByRole']>, name: string) { const pending = page.waitForEvent('download'); await button.click(); const item = await pending; await item.saveAs(`${qa}/${name}`); return readFile(`${qa}/${name}`); }
const close = (page: Page) => page.getByRole('dialog').getByRole('button', { name: '닫기', exact: true }).click();
const rpcResponse = (page: Page, method: string) => page.waitForResponse(response => response.url().includes('/api/rpc') && response.request().postDataJSON()?.method === method);
async function sourceFields(page: Page, id: string, name: string, adapter: string) { await page.getByTestId('database-new-source').click(); await page.getByTestId('database-manifest-id').fill(id); await page.getByTestId('database-manifest-name').fill(name); await page.getByTestId('database-manifest-adapter').selectOption(adapter); await page.getByTestId('database-manifest-library').fill('public_library'); await page.getByTestId('database-manifest-view').fill('layout'); }

test('local GDS review searches actual geometry, measures exact DBU, preserves bookmarks and signed CSV without RPC', async ({ page }) => {
  await mkdir(qa, { recursive: true }); const requests: string[] = [], errors: string[] = [];
  page.on('request', request => { if (/\/api\/rpc|\/rpc\/events|\/auth\//.test(request.url())) requests.push(request.url()); }); page.on('pageerror', error => errors.push(error.message));
  await page.goto('/?mode=viewer'); await page.getByTestId('viewer-gds-input').setInputFiles('examples/sky130/wire.gds'); await expect(page.getByTestId('viewer-shape-count')).toContainText('3 / 3');
  await page.getByTestId('viewer-native-database').click(); await expect(page.getByTestId('native-database-panel')).toBeVisible(); await expect(page.getByTestId('database-notice')).toContainText('아직 worker에 요청하지 않았습니다.'); await expect(page.getByTestId('database-import')).toHaveCount(0); expect(requests).toEqual([]); await close(page);
  const bundle = JSON.parse((await download(page, page.getByTestId('viewer-export'), 'review-wire.register-view.json')).toString()) as { scene: Scene; [key: string]: unknown };
  const shape = bundle.scene.shapes[0]; await page.getByTestId('viewer-design-review').click(); await page.getByLabel('로드된 도형 검색').fill(shape.id); await expect(page.getByTestId('review-search-results').getByRole('button')).toHaveCount(1); await page.getByTestId('review-search-results').getByRole('button').click(); await expect(page.getByTestId('review-search-results').getByRole('button')).toHaveClass(/selected/); await close(page); await expect(page.locator('.sv-inspector')).toContainText(shape.id);
  await page.getByTestId('viewer-design-review').click(); await page.getByTestId('review-tab-ruler').click(); const ax = 900719925474099300000000n; await page.getByLabel('점 A X DBU').fill(String(ax)); await page.getByLabel('점 A Y DBU').fill('0'); await page.getByLabel('점 B X DBU').fill(String(ax + 300n)); await page.getByLabel('점 B Y DBU').fill('400'); await expect(page.getByTestId('review-ruler-result')).toContainText('500 DBU · 0.5 µm (정수 거리)');
  await page.getByTestId('review-tab-bookmarks').click(); await page.getByLabel('북마크 이름').fill('실제 wire 도형'); await page.getByRole('button', { name: '선택 도형 저장', exact: true }).click(); const bookmarks = JSON.parse((await download(page, page.getByRole('button', { name: '북마크 JSON 저장', exact: true }), 'review-bookmarks.json')).toString()); expect(bookmarks.project_id).toBe(bundle.scene.project_id); expect(bookmarks.bookmarks[0].shape_id).toBe(shape.id); await page.getByLabel('북마크 JSON 가져오기', { exact: true }).setInputFiles(`${qa}/review-bookmarks.json`); await expect(page.getByTestId('review-notice')).toContainText('일치하는 북마크'); const wrong = { ...bookmarks, revision: bookmarks.revision + 1 }; await page.getByLabel('북마크 JSON 가져오기', { exact: true }).setInputFiles({ name: 'wrong-revision.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(wrong)) }); await expect(page.getByTestId('review-error')).toContainText('STALE');
  await page.getByTestId('review-tab-compare').click(); const baseline = JSON.parse((await download(page, page.getByRole('button', { name: '현재 Scene 기준 파일 저장', exact: true }), 'review-baseline.json')).toString()); baseline.scene.shapes[0].polygon[0][0] = String(BigInt(baseline.scene.shapes[0].polygon[0][0]) + 100n); baseline.scene.total_shape_count = baseline.scene.shapes.length + 1; baseline.scene.truncated = true; await page.getByLabel('기준 Scene JSON 가져오기', { exact: true }).setInputFiles({ name: 'partial-changed-baseline.json', mimeType: 'application/json', buffer: Buffer.from(exportReviewSnapshot(baseline.scene)) }); await expect(page.getByTestId('review-comparison-summary')).toContainText('로드된 부분 범위 비교'); await expect(page.getByTestId('review-comparison-summary')).toContainText('변경 1'); await page.screenshot({ path: `${qa}/register-design-review.png` }); await close(page);
  const raw = await readFile('tests/commercial/interchange/currents.csv', 'utf8'); const result = parseMappedResultText(raw, { header: true, delimiter: 'csv', analysis: 'dc', convention: 'conventional', x: { column: 'sweep_V', unit: 'V' }, branches: [{ id: 'id', name: 'ID', column: 'current_mA', unit: 'mA', from_net: 'D', to_net: 'S' }] }, { project_id: bundle.scene.project_id, revision: bundle.scene.revision });
  const flow = { ...result.currentFlow!, freshness: 'stale' as const } satisfies CurrentFlow; await page.getByTestId('viewer-current-input').setInputFiles({ name: 'external-current.csv.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(flow)) }); await page.getByTestId('viewer-design-review').click(); await page.getByTestId('review-tab-csv').click(); const csv = (await download(page, page.getByRole('button', { name: '전류 CSV 저장', exact: true }), 'review-signed-current.csv')).toString(); const lines = csv.trim().split(/\r?\n/), rows = lines.slice(1).map(line => line.split(',')); expect(lines[0]).toContain('current_A,source'); expect(rows.map(row => Number(row[8]))).toEqual([-.001,0,.001]); expect(rows.every(row => JSON.parse(row[15]) === 'stale' && JSON.parse(row[16]) === 'unverified')).toBe(true); expect(requests).toEqual([]); expect(errors).toEqual([]);
  await writeFile(`${qa}/native-database-ui.json`, JSON.stringify({ local_review_without_rpc: true, original_database_panel_without_rpc: true, actual_public_GDS: 'examples/sky130/wire.gds', exact_integer_ruler_DBU: 500, exact_integer_ruler_um: .5, source_unchanged: true, actual_shape_search_selection: true, bookmarks_roundtrip_and_wrong_revision_rejected: true, partial_baseline_integer_geometry_diff: true, external_signed_csv_A: [-.001,0,.001], csv_stale_provenance_preserved: true, vendor_execution_verified: false, native_source_registration_and_diagnostics: false, native_neutral_graph_import: false, browser_errors: errors }, null, 2));
});

test('actual source registry reports missing commercial tool and rejects an unsafe operator path', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); await page.goto('/?mode=viewer'); await page.getByTestId('viewer-native-database').click(); const catalogue = rpcResponse(page, 'database.catalog'); await page.getByTestId('database-load').click(); const catalog = (await (await catalogue).json()).result as DatabaseCatalog; expect(catalog.adapters.map(item => item.id)).toEqual(expect.arrayContaining(['cadence-skill', 'synopsys-ndm', 'klayout-file'])); await expect(page.getByTestId('database-catalog')).toContainText('OA'); await expect(page.getByTestId('database-catalog')).toContainText('NDM');
  const id = `ui_vendor_${Date.now()}`; await sourceFields(page, id, 'UI missing licensed tool diagnosis', 'cadence-skill'); await page.getByTestId('database-executable').fill('/workspace/missing-vendor/virtuoso'); await page.getByTestId('database-native-db').fill('/workspace/examples/sky130'); await page.getByTestId('database-env-names').fill('LM_LICENSE_FILE'); const registration = rpcResponse(page, 'database.register'); await page.getByTestId('database-register').click(); const registered = await (await registration).json(); expect(registered.ok).toBe(true); expect(registered.result.available).toBe(false); expect(registered.result.vendor_execution_verified).toBe(false); await expect(page.getByTestId('database-source-summary')).toContainText('unavailable');
  const diagnosis = rpcResponse(page, 'database.probe'); await page.getByTestId('database-probe').click(); const probed = await (await diagnosis).json(); expect(probed.ok).toBe(true); expect(probed.result.available).toBe(false); expect(probed.result.vendor_execution_verified).toBe(false); await expect(page.getByTestId('database-notice')).toContainText('접근 불가'); await page.getByTestId('database-browse').click(); await expect(page.getByTestId('database-cell-list').locator('tbody tr')).toHaveCount(0); await expect(page.getByTestId('database-read')).toBeDisabled();
  await page.getByTestId('database-step-0').click(); await sourceFields(page, `ui_path_${Date.now()}`, 'Unsafe path rejection fixture', 'klayout-file'); await page.getByTestId('database-layout-file').fill('/etc/forbidden.gds'); const rejected = rpcResponse(page, 'database.register'); await page.getByTestId('database-register').click(); const bad = await (await rejected).json(); expect(bad.ok).toBe(false); await expect(page.getByTestId('database-error')).toContainText(bad.error.code); await page.screenshot({ path: `${qa}/register-native-database-unavailable.png` }); expect(errors).toEqual([]);
  const evidence = JSON.parse(await readFile(`${qa}/native-database-ui.json`, 'utf8')); Object.assign(evidence, { native_source_registration_and_diagnostics: true, actual_missing_vendor_source_id: id, actual_vendor_available: false, vendor_execution_verified: false, unsafe_operator_path_rejected: bad.error.code, readonly_unavailable_has_no_cells: true, fixed_reader_setup_without_recipe: true }); await writeFile(`${qa}/native-database-ui.json`, JSON.stringify(evidence, null, 2));
});

test('real public KLayout graph receipt downloads and imports geometry without claiming OA or NDM verification', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); await page.goto('/?mode=viewer'); await page.getByTestId('viewer-gds-input').setInputFiles('examples/sky130/wire.gds'); await page.getByTestId('viewer-native-database').click(); await page.getByTestId('database-load').click(); await expect(page.getByTestId('database-catalog').locator('article')).toHaveCount(3);
  const sourceId = `ui_file_${Date.now()}`; await sourceFields(page, sourceId, 'Public GDS reader calibration · no commercial execution', 'klayout-file'); await page.getByTestId('database-layout-file').fill('/workspace/examples/sky130/wire.gds'); const registered = rpcResponse(page, 'database.register'); await page.getByTestId('database-register').click(); const body = await (await registered).json(); expect(body.ok).toBe(true); expect(body.result.available).toBe(true); expect(body.result.vendor_execution_verified).toBe(false); await page.getByTestId('database-probe').click(); await expect(page.getByTestId('database-notice')).toContainText('접근 검사 완료'); await page.getByTestId('database-browse').click(); await expect(page.getByTestId('database-cell-list')).toContainText('wire'); await expect(page.getByTestId('database-cell')).toHaveValue('wire');
  const reading = rpcResponse(page, 'database.read'); await page.getByTestId('database-read').click(); const readBody = await (await reading).json(); expect(readBody.ok).toBe(true); const receipt = readBody.result as DatabaseRead; expect(receipt.status).toBe('verified'); expect(receipt.can_import).toBe(true); expect(receipt.vendor_execution_verified).toBe(false); expect(receipt.graph?.top_cell).toBe('wire'); expect(receipt.graph?.cells.length).toBeGreaterThan(0); await expect(page.getByTestId('database-vendor-provenance')).toContainText('상용 vendor 실행 미검증'); const stored = JSON.parse((await download(page, page.getByTestId('database-download-receipt'), 'public-wire.db-read.json')).toString()); expect(stored.id).toBe(receipt.id); const artifact = await download(page, page.getByTestId('database-download-artifact'), 'public-wire.db-graph.json'); expect(createHash('sha256').update(artifact).digest('hex')).toBe(receipt.graph_sha256); await expect(page.getByTestId('database-import')).toBeDisabled(); await page.getByTestId('database-import-confirm').check(); const importResponse = rpcResponse(page, 'database.import'); await page.getByTestId('database-import').click(); const importedBody = await (await importResponse).json(); expect(importedBody.ok).toBe(true); const imported = importedBody.result as DatabaseImportResult; expect(imported.project.cell).toBe('wire'); expect(imported.report.vendor_execution_verified).toBe(false); await expect(page.getByTestId('database-project')).toContainText(`r${imported.project.revision}`); await expect(page.getByTestId('database-import-report')).toContainText(receipt.id); await page.screenshot({ path: `${qa}/register-native-database-graph.png` }); await close(page); await expect(page.getByTestId('viewer-shape-count')).toContainText('3 / 3'); const viewer = JSON.parse((await download(page, page.getByTestId('viewer-export'), 'native-wire.register-view.json')).toString()); expect(viewer.scene.project_id).toBe(imported.project.id); expect(viewer.scene.revision).toBe(imported.project.revision); expect(viewer.scene.shapes.length).toBe(3); expect(viewer.originalInputName).toBe('wire.gds'); expect(viewer.sourceGdsBase64).toBeUndefined(); expect(createHash('sha256').update(Buffer.from(viewer.originalInputGdsBase64, 'base64')).digest('hex')).toBe(createHash('sha256').update(await readFile('examples/sky130/wire.gds')).digest('hex')); expect(errors).toEqual([]);
  const evidence = JSON.parse(await readFile(`${qa}/native-database-ui.json`, 'utf8')); Object.assign(evidence, { native_neutral_graph_import: true, native_reader: 'klayout-file', original_database_vendor_verification: false, actual_read_id: receipt.id, actual_graph_sha256: receipt.graph_sha256, actual_graph_artifact_sha256_verified: true, actual_import_project_id: imported.project.id, actual_import_revision: imported.project.revision, actual_import_shapes: viewer.scene.shapes.length, original_local_GDS_preserved: true, explicit_import_confirm_required: true, browser_errors: errors, focused_suite: { passed: 3, failed: 0 }, checked_at: new Date().toISOString() }); await writeFile(`${qa}/native-database-ui.json`, JSON.stringify(evidence, null, 2));
});



