import {test,expect,type Page} from '@playwright/test';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const dir='packages/ui/qa/process-flow';
const save=async(page:Page,id:string,name:string)=>{const pending=page.waitForEvent('download');await page.getByTestId(id).click();await(await pending).saveAs(`${dir}/${name}`);return readFile(`${dir}/${name}`,'utf8');};
const open=async(page:Page)=>{await page.goto('/?mode=viewer');await page.getByTestId('viewer-process').click();await page.getByTestId('process-recipe-details').locator('summary').first().click();};
const collapse=async(page:Page)=>{if(await page.getByTestId('process-recipe-details').getAttribute('open')!==null)await page.getByTestId('process-recipe-details').locator('summary').first().click();};
const evidence=async(values:Record<string,unknown>)=>{let old={};try{old=JSON.parse(await readFile(`${dir}/process-flow-ui.json`,'utf8'));}catch{}await writeFile(`${dir}/process-flow-ui.json`,JSON.stringify({...old,...values,checked_at:new Date().toISOString()},null,2));};
const planar={schema_version:1,kind:'register-process-recipe',name:'UI analytic planar rate',grid:{origin_um:[0,0,0],spacing_um:.1,shape:[4,4,8]},materials:[{id:0,name:'air',role:'void',color:'#ffffff'},{id:1,name:'bulk',role:'bulk',color:'#777777'},{id:2,name:'film',role:'film',color:'#cc9966',nominal_thickness_um:.2}],initial:[{material_id:1,box_um:[[0,0,0],[.4,.4,.3]]}],steps:[{id:'dep',name:'deposit',kind:'deposit',method:'directional',material_id:2,rate_um_s:.02,time_s:10,angular_spread_deg:0,reemit_fraction:0}],calibration:{kind:'uncalibrated',label:'analytic supplied input'}};
const loadRecipe=async(page:Page,recipe:unknown)=>page.getByTestId('recipe-json-input').setInputFiles({name:'recipe.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(recipe))});

test('real 3D flow executes deposition, shadowing, selective masked etch and Preston CMP; stage mesh and GDS bytes survive portable reopen',async({page})=>{
  test.setTimeout(150000);await mkdir(dir,{recursive:true});const errors:string[]=[],native:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/\/rpc|\/events/.test(new URL(r.url()).pathname))native.push(r.url());});
  await page.goto('/?mode=viewer');await page.getByTestId('viewer-empty-gds-input').setInputFiles('examples/sky130/mosfet.gds');await page.getByTestId('viewer-process').click();await page.getByTestId('process-recipe-details').locator('summary').first().click();await page.getByTestId('recipe-run').click();
  await expect(page.getByTestId('process-timeline')).toBeVisible({timeout:30000});await expect(page.getByTestId('process-inspected')).toHaveText('13824 / 13824',{timeout:30000});await collapse(page);
  await page.getByTestId('process-stage-1').click();await expect(page.getByTestId('process-inspected')).toHaveText('13824 / 13824',{timeout:30000});await expect(page.getByTestId('process-provenance')).toContainText('3D 미보정');await expect(page.getByTestId('process-voids')).toContainText('폐쇄 공극');
  const result=JSON.parse(await save(page,'recipe-result-export','run.json'));expect(result.stages).toHaveLength(5);expect(result.stages[1].closed_voids).toBeGreaterThan(0);expect(result.stages[3].removed_volume_um3).toBeGreaterThan(0);expect(result.stages[4].removed_volume_um3).toBeGreaterThan(0);expect(result.calibrated_physical_prediction).toBe(false);expect(result.recipe_sha256).toMatch(/^[0-9a-f]{64}$/);
  await expect(page.getByTestId('process-coating')).toBeVisible();const coverage=await save(page,'coating-csv','surface-coverage.csv');expect(coverage.split('\n')).toHaveLength(result.stages[1].deposition_coverage.assessed_faces+1);expect(coverage).toContain('resolution_um');if(result.stages[1].deposition_coverage.no_resolved_coating_faces){await page.getByTestId('coating-face').first().click();await expect(page.getByTestId('coating-selection')).toContainText('미해결');}
  await page.getByTestId('process-voids').getByRole('button',{name:/폐쇄 공극/}).first().click();await page.getByTestId('process-material-2').uncheck();await page.getByTestId('process-heat').check();await page.getByTestId('process-panel').evaluate(p=>{p.scrollTop=p.scrollHeight;});await page.screenshot({path:`${dir}/register-process-flow-keyhole.png`});
  const document=JSON.parse(await save(page,'process-export-volume','flow-review.json'));expect(document.selected_stage).toBe(1);expect(document.process_run.stages).toHaveLength(5);
  await page.getByRole('dialog').getByRole('button',{name:'닫기',exact:true}).click();const bundle=JSON.parse(await save(page,'viewer-export','flow-view.json'));expect(createHash('sha256').update(Buffer.from(bundle.sourceGdsBase64,'base64')).digest('hex')).toBe(createHash('sha256').update(await readFile('examples/sky130/mosfet.gds')).digest('hex'));
  await page.getByTestId('viewer-bundle-input').setInputFiles(`${dir}/flow-view.json`);await page.getByTestId('viewer-process').click();await expect(page.getByTestId('process-inspected')).toHaveText('13824 / 13824',{timeout:30000});await expect(page.getByTestId('process-timeline')).toBeVisible();
  await page.getByTestId('process-stage-4').click();await expect(page.getByTestId('process-inspected')).toHaveText('13824 / 13824',{timeout:30000});expect(native).toEqual([]);expect(errors).toEqual([]);
  await evidence({all_four_steps_executed:true,pinch_off_and_closed_void:true,stage_mesh_all_cells:13824,all_stage_history_and_GDS_preserved:true,all_initial_surface_coverage_exported:true,sub_resolution_coating_marked_unresolved:true,no_native_requests:true,browser_errors:errors});
});
test('UI rate fit, real h/2h comparison, complete VTU export/reimport, and continuation from current tetra volume',async({page})=>{
  test.setTimeout(120000);await mkdir(dir,{recursive:true});await open(page);await loadRecipe(page,planar);await page.getByText('실측 평면 두께로 속도 fit',{exact:true}).click();await page.getByTestId('recipe-fit').click();await expect(page.getByTestId('recipe-fit-result')).toContainText('0.0200000 µm/s');
  await page.getByTestId('recipe-convergence').click();await expect(page.getByTestId('recipe-resolution-result')).toBeVisible({timeout:30000});await expect(page.getByTestId('process-inspected')).toHaveText('768 / 768');await collapse(page);await expect(page.getByTestId('process-min-thickness')).toHaveText('200 nm');
  await save(page,'process-export-vtu','generated.vtu');await save(page,'process-export-vtu-settings','generated.vtu-setup.json');await page.getByText('해석·실측 mesh 가져오기 · VTU 설정',{exact:true}).click();await page.getByTestId('process-vtu-input').setInputFiles(`${dir}/generated.vtu`);await page.getByTestId('process-vtu-options').setInputFiles(`${dir}/generated.vtu-setup.json`);await page.getByTestId('process-vtu-import').click();await expect(page.getByTestId('process-min-thickness')).toHaveText('200 nm');await expect(page.getByTestId('process-inspected')).toHaveText('768 / 768');
  await page.getByTestId('process-recipe-details').locator('summary').first().click();await page.getByTestId('recipe-from-volume').click();const recipe=JSON.parse(await save(page,'recipe-save','continued.recipe.json'));expect(recipe.initial_volume.cells).toHaveLength(768);expect(recipe.initial).toEqual([]);
  await page.getByTestId('recipe-run').click();await expect(page.getByTestId('process-timeline')).toBeVisible({timeout:30000});await expect(page.getByTestId('recipe-progress')).toHaveText('모든 공정 단계 계산 완료');const result=JSON.parse(await save(page,'recipe-result-export','continued.run.json'));expect(result.warnings.join(' ')).toContain('resampling');expect(result.recipe.initial_volume.provenance.kind).toBe('simulation');
  await evidence({actual_planar_rate_fit:true,actual_two_resolution_runs:true,full_VTU_roundtrip:true,tetra_volume_continuation:true});
});
test('GDS mask import uses real loaded polygons; bad recipe and cancelled calculation preserve completed result',async({page})=>{
  test.setTimeout(120000);await mkdir(dir,{recursive:true});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?mode=viewer');await page.getByTestId('viewer-empty-gds-input').setInputFiles('examples/sky130/mosfet.gds');await page.getByTestId('viewer-process').click();await page.getByTestId('process-demo').click();await expect(page.getByTestId('process-inspected')).toHaveText('1296 / 1296');await page.getByTestId('process-recipe-details').locator('summary').first().click();
  const options=await page.getByTestId('recipe-mask-layer').locator('option').evaluateAll(o=>o.map(n=>({value:(n as HTMLOptionElement).value,label:n.textContent})));const layer=options.find(o=>o.label?.toLowerCase().includes('met1'))||options.find(o=>o.value);expect(layer).toBeTruthy();await page.getByTestId('recipe-mask-layer').selectOption(layer!.value);await page.getByTestId('recipe-mask-import').click();const recipe=JSON.parse(await save(page,'recipe-save','actual-gds-mask.recipe.json'));expect(recipe.steps[0].mask.source.layer_id).toBe(layer!.value);expect(recipe.steps[0].mask.source.scope).toBe('loaded-scene');expect(recipe.steps[0].mask.polygons_um.length).toBeGreaterThan(0);
  await page.getByText('전체 Recipe JSON · mask / 출처 / 조건 편집',{exact:true}).click();await page.getByTestId('recipe-json-editor').fill('{"steps":[null],"materials":[null],"grid":{}}');await page.getByTestId('recipe-run').click();await expect(page.getByTestId('recipe-error')).toBeVisible();await expect(page.getByTestId('process-inspected')).toHaveText('1296 / 1296');await loadRecipe(page,planar);
  await page.route(/process-run-worker/,async route=>{await new Promise(resolve=>setTimeout(resolve,1000));try{await route.continue();}catch{}});await page.getByTestId('recipe-run').click();await page.getByTestId('recipe-cancel').click();await expect(page.getByTestId('recipe-progress')).toContainText('취소됨');await expect(page.getByTestId('process-inspected')).toHaveText('1296 / 1296');await expect(page.getByTestId('process-timeline')).toHaveCount(0);expect(errors).toEqual([]);
  await evidence({actual_GDS_polygons_mask:true,invalid_recipe_preserves_result:true,cancel_preserves_completed_result:true,malformed_JSON_does_not_crash:true});
});
