import {useEffect,useRef,useState} from 'react';
import {localRpc,type Project} from '@mos/contracts';
import './design-assistant.css';

type Evidence={project:{id:string;revision:number};fingerprint:string;issues:{code:string;severity:string;message:string;kind?:string;net?:string;run_id?:string}[];connectivity:{device_count:number;net_count:number;truncated:boolean;scope:string};evidence_ids:string[];limits:string[]};
type ProviderStatus={openai:{configured:boolean;model:string;budget_usd:number;remaining_usd:number;reserved_usd:number};ollama:{available:boolean;models:string[];selected_model:string|null}};
type Review={id:string;provider:string;model:string;revision:number;freshness:string;review:{summary:string;findings:{severity:string;title:string;explanation:string;evidence_ids:string[];suggested_check:string}[];limitations:string[]};budget_reservation:{reserved_usd:number}|null};
export default function DesignAssistant({project,shared=false,onCheck}:{project:Project|null;shared?:boolean;onCheck:(target:string)=>void}){
  const [status,setStatus]=useState<ProviderStatus>(),[evidence,setEvidence]=useState<Evidence>(),[result,setResult]=useState<Review>(),[history,setHistory]=useState<Review[]>([]);
  const [provider,setProvider]=useState<'ollama'|'openai'>('ollama'),[model,setModel]=useState(''),[approved,setApproved]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState('');
  const generation=useRef(0);useEffect(()=>{generation.current++;setEvidence(undefined);setResult(undefined);setHistory([]);setApproved(false);setBusy('');setError('');return()=>{generation.current++;};},[project?.id,project?.revision]);
  const execute=async(label:string,fn:(version:number)=>Promise<void>)=>{const version=generation.current;setBusy(label);setError('');try{await fn(version);}catch(e){if(generation.current===version)setError(e instanceof Error?e.message:String(e));}finally{if(generation.current===version)setBusy('');}};
  const current=!!project&&evidence?.project.id===project.id&&evidence.project.revision===project.revision;
  const ready=provider==='openai'?status?.openai.configured&&status.openai.remaining_usd>0:status?.ollama.available&&!!model;
  const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({evidence,result},null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`${project?.cell||'design'}-ai-review.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <section className="design-assistant" data-testid="design-assistant" aria-busy={!!busy}>
    <header><span>DESIGN ASSISTANT</span><h3>실제 설계 근거를 읽고, 다음 검사를 제안합니다</h3><p>{project?.name||'프로젝트 없음'} · r{project?.revision??'—'}</p></header>
    {shared&&<p role="status">AI 제공자 연결은 로컬 작업공간에서 사용합니다. 공동 작업 서버의 사용자에게 로컬 키를 공유하지 않습니다.</p>}
    {error&&<p role="alert" className="assistant-error">{error}</p>}
    <div className="assistant-actions"><button data-testid="assistant-preview" disabled={!project||shared||!!busy} onClick={()=>void execute('근거 읽는 중',async version=>{const [s,e]=await Promise.all([localRpc<ProviderStatus>('assistant.status'),localRpc<Evidence>('assistant.evidence',{project_id:project!.id,expected_revision:project!.revision})]);if(generation.current!==version)return;setStatus(s);setEvidence(e);setResult(undefined);setApproved(false);setModel(s.ollama.selected_model||'');})}>설계 근거·연결 상태 읽기</button><button data-testid="assistant-history" disabled={!project||shared||!!busy} onClick={()=>void execute('저장된 검토 읽는 중',async version=>{const rows=await localRpc<Review[]>('assistant.history',{project_id:project!.id,expected_revision:project!.revision});if(generation.current!==version)return;setHistory(rows);setResult(rows[0]);})}>저장된 검토 읽기 · API 호출 없음</button><span role="status">{busy}</span></div>{history.length>0&&<label>이전 검토<select aria-label="저장된 AI 검토" value={result?.id||''} onChange={e=>setResult(history.find(r=>r.id===e.target.value))}>{history.map(r=><option key={r.id} value={r.id}>{r.provider} · r{r.revision} · {r.freshness} · {r.id.slice(0,8)}</option>)}</select></label>}
    {status&&<fieldset disabled={!!busy||shared}><legend>AI 제공자</legend><label>실행 위치<select aria-label="AI 제공자" value={provider} onChange={event=>{setProvider(event.target.value as typeof provider);setApproved(false);}}><option value="ollama">로컬 Ollama</option><option value="openai">OpenAI API</option></select></label>{provider==='ollama'?<><label>설치된 모델<select aria-label="Ollama 모델" value={model} onChange={event=>{setModel(event.target.value);setApproved(false);}}><option value="">모델 선택</option>{status.ollama.models.map(name=><option key={name}>{name}</option>)}</select></label><p>{status.ollama.available?'로컬 서버 연결됨':'로컬 Ollama 서버·모델 미연결'}</p></>:<p>{status.openai.configured?'로컬 키 설정됨':'키 미설정'} · {status.openai.model} · 호출 예약 잔여 US${status.openai.remaining_usd.toFixed(6)} / 승인 한도 US${status.openai.budget_usd}</p>}</fieldset>}
    {evidence&&<><div className="assistant-scope"><strong>검토 범위: {evidence.connectivity.scope}</strong><span>소자 {evidence.connectivity.device_count}개 · 넷 {evidence.connectivity.net_count}개{evidence.connectivity.truncated?' · AI 입력은 일부로 제한됨':''}</span><code>{evidence.fingerprint.slice(0,16)}</code></div><h4>엔진·연결 검사에서 확인한 항목</h4><div className="assistant-findings">{evidence.issues.map((issue,index)=><article key={index} data-severity={issue.severity}><strong>{issue.code}</strong><p>{issue.message}</p><small>{issue.net||issue.run_id||issue.kind}</small></article>)}</div><details><summary>AI에 제공할 근거 보기</summary><pre>{JSON.stringify(evidence,null,2)}</pre></details><p>선택한 프로젝트의 연결 요약·실행 상태·측정값을 전달합니다. AI 판단은 제안이며 실제 DRC/LVS/PEX 결과를 대신하지 않습니다.</p><label className="assistant-consent"><input data-testid="assistant-approve" type="checkbox" checked={approved} disabled={!!busy||!current||!ready} onChange={event=>setApproved(event.target.checked)}/>{provider==='openai'?'위 설계 근거를 OpenAI로 보내고 승인된 예산 안에서 한 번 검토합니다.':'위 설계 근거를 선택한 로컬 모델로 한 번 검토합니다.'}</label><button className="primary" data-testid="assistant-run" disabled={!!busy||!current||!approved||!ready} onClick={()=>void execute('AI 검토 중',async version=>{setApproved(false);const next=await localRpc<Review>('assistant.review',{project_id:project!.id,expected_revision:project!.revision,provider,...(provider==='ollama'?{model}:{}),evidence_hash:evidence.fingerprint,approved:true});if(generation.current!==version)return;setResult(next);setStatus(await localRpc<ProviderStatus>('assistant.status'));})}>AI 설계 검토 실행</button>{!current&&<p>설계가 바뀌었습니다. 근거를 다시 읽으세요.</p>}</>}
    {result&&<div className="assistant-result" data-testid="assistant-result"><header><strong>{result.provider} · {result.model} · {result.freshness.toUpperCase()} · 검토 제안</strong><button onClick={download}>근거·AI 결과 JSON 저장</button></header><p>{result.review.summary}</p>{result.budget_reservation&&<small>이번 호출 비용 예약 US${result.budget_reservation.reserved_usd.toFixed(6)} · 최종 청구액과 구분</small>}<div className="assistant-findings">{result.review.findings.map((finding,index)=><article key={index} data-severity={finding.severity}><strong>{finding.title}</strong><p>{finding.explanation}</p><code>{finding.evidence_ids.join(' · ')}</code><button disabled={!!busy||result.freshness!=='current'} onClick={()=>onCheck(finding.suggested_check)}>제안한 검사 화면 열기</button></article>)}</div>{result.review.limitations.map((limit,index)=><p key={index} className="assistant-limit">{limit}</p>)}</div>}
  </section>;
}
