import {useEffect,useMemo,useRef,useState} from 'react';
import {rpc,type HierarchyPreview,type HierarchyRequest,type HierarchySource,type Project,type Scene,type SceneShape} from '@mos/contracts';
import {LayoutViewer} from '@mos/viewer';
import './hierarchy-transfer.css';
const CLIP='register.hierarchy.clipboard';
export function copyHierarchy(project:Project,cell:string|null){localStorage.setItem(CLIP,JSON.stringify({project_id:project.id,cell:cell||project.cell,revision:project.revision}));}
function clip(){try{return JSON.parse(localStorage.getItem(CLIP)||'null') as {project_id:string;cell:string;revision:number}|null;}catch{return null;}}
const path=(s:SceneShape)=>{const p=new Path2D();for(const ring of [s.polygon,...s.holes||[]]){ring.forEach(([x,y],i)=>i?p.lineTo(Number(x),Number(y)):p.moveTo(Number(x),Number(y)));p.closePath();}return p;};
function ImpactCanvas({preview,view,hidden}:{preview:HierarchyPreview;view:'before'|'after'|'delta';hidden:Set<string>}){
  const canvas=useRef<HTMLCanvasElement>(null),[size,setSize]=useState([700,320]),[zoom,setZoom]=useState(1),[pan,setPan]=useState([0,0]);const drag=useRef<number[]|undefined>(undefined);
  const draw=useMemo(()=>{const before=new Set(preview.before.shapes.map(s=>s.id)),after=new Set(preview.after.shapes.map(s=>s.id));
    const shapes=view==='before'?preview.before.shapes:view==='after'?preview.after.shapes:[...preview.before.shapes,...preview.after.shapes.filter(s=>!before.has(s.id))];
    const colors=new Map(preview.after.layers.map(l=>[l.id,l.color]));return shapes.map(s=>({layer:s.layer_id,path:path(s),color:view!=='delta'?colors.get(s.layer_id)||'#4d9aa7':!before.has(s.id)?'#5bd9bd':!after.has(s.id)?'#ec727d':'#627187'}));},[preview,view]);
  useEffect(()=>{setZoom(1);setPan([0,0]);},[preview.preview_hash]);
  useEffect(()=>{const el=canvas.current;if(!el)return;const o=new ResizeObserver(e=>setSize([e[0].contentRect.width,e[0].contentRect.height]));o.observe(el);return()=>o.disconnect();},[]);
  useEffect(()=>{const el=canvas.current,c=el?.getContext('2d');if(!el||!c)return;const [w,h]=size,dpr=Math.min(devicePixelRatio,2);el.width=w*dpr;el.height=h*dpr;c.scale(dpr,dpr);c.fillStyle='#0c1523';c.fillRect(0,0,w,h);
    const a=preview.before.bounds||['0','0','1','1'],b=preview.after.bounds||a;const bounds=[Math.min(+a[0],+b[0]),Math.min(+a[1],+b[1]),Math.max(+a[2],+b[2]),Math.max(+a[3],+b[3])];const factor=Math.min((w-30)/Math.max(bounds[2]-bounds[0],1),(h-30)/Math.max(bounds[3]-bounds[1],1))*zoom;
    c.translate(w/2+pan[0],h/2+pan[1]);c.scale(factor,-factor);c.translate(-(bounds[0]+bounds[2])/2,-(bounds[1]+bounds[3])/2);c.globalAlpha=.65;
    for(const s of draw)if(!hidden.has(s.layer)){c.fillStyle=s.color;c.fill(s.path,'evenodd');}
    if(view!=='before'){c.globalAlpha=1;c.strokeStyle='#ffd271';c.lineWidth=1.7/factor;for(const o of preview.impact.mask.overlaps)if(!hidden.has(o.layer_id)){const [x,y,r,t]=o.bbox.map(Number);c.strokeRect(x,y,r-x,t-y);}}
  },[draw,size,zoom,pan,hidden,preview,view]);
  return <div className="impact-canvas"><canvas ref={canvas} data-testid={`hierarchy-canvas-${view}`} aria-label={`${view} 전체 레이아웃 미리보기`} onWheel={e=>{e.preventDefault();setZoom(v=>Math.min(64,Math.max(.5,v*(e.deltaY<0?1.2:1/1.2))));}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current=[e.clientX,e.clientY,...pan];}} onPointerMove={e=>{if(drag.current)setPan([drag.current[2]+e.clientX-drag.current[0],drag.current[3]+e.clientY-drag.current[1]]);}} onPointerUp={()=>{drag.current=undefined;}}/><button className="button small" onClick={()=>{setZoom(1);setPan([0,0]);}}>전체 맞춤</button><span>휠 확대 · 드래그 이동 · 핀 주석 포함</span></div>;
}
export default function HierarchyTransfer({project,cellName,disabledReason,onProject}:{project:Project;cellName:string|null;disabledReason?:string;onProject:(p:Project)=>Promise<void>}){
  const saved=clip(),[mode,setMode]=useState<'place'|'wrap'>('place'),[query,setQuery]=useState(''),[sources,setSources]=useState<HierarchySource[]>([]),[sourceId,setSourceId]=useState(saved?.project_id||project.id),[sourceCell,setSourceCell]=useState(saved?.cell||cellName||project.cell);
  const [namespace,setNamespace]=useState('COPY1'),[parent,setParent]=useState('CHIP_TOP'),[scope,setScope]=useState<'both'|'schematic'|'layout'>('both'),[target,setTarget]=useState(cellName||project.cell),[position,setPosition]=useState<[string,string]>(['50000','0']),[rotation,setRotation]=useState<0|90|180|270>(0),[mirror,setMirror]=useState(false),[pins,setPins]=useState<Record<string,string>>({});
  const [preview,setPreview]=useState<HierarchyPreview>(),[approved,setApproved]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[view,setView]=useState<'before'|'delta'|'after'|'3d'>('delta'),[hidden,setHidden]=useState(new Set<string>());
  const live=useRef(true),sequence=useRef(0),receipt=useRef<{hash:string;id:string}|undefined>(undefined);
  const refresh=async()=>{const seq=++sequence.current;try{const r=await rpc<{projects:HierarchySource[]}>('hierarchy.sources',{query});if(live.current&&seq===sequence.current)setSources(r.projects);}catch(e){if(live.current)setError(e instanceof Error?e.message:String(e));}};
  useEffect(()=>{live.current=true;void refresh();return()=>{live.current=false;sequence.current++;};},[]);
  const source=sources.find(v=>v.id===sourceId),selected=source?.cells.find(c=>c.name===sourceCell);
  useEffect(()=>{setPins(Object.fromEntries((selected?.ports||[]).map(p=>[p,p==='VPWR'||p==='VGND'?p:namespace+'_'+p])));},[sourceId,sourceCell,selected?.ports.join('|')]);
  const request:HierarchyRequest=mode==='wrap'?{project_id:project.id,mode,parent_name:parent}:{project_id:project.id,mode,source_project_id:sourceId,source_cell:sourceCell,target_cell:target,namespace,scope,...(scope!=='layout'?{pins}:{}),...(scope!=='schematic'?{position,rotation,mirror}:{})};
  const signature=JSON.stringify(request),current=useRef(signature);current.current=signature;
  const validPreview=preview&&JSON.stringify(preview.request)===signature&&preview.target_revision===project.revision?preview:undefined;
  useEffect(()=>{setApproved(false);setPreview(undefined);},[signature,project.revision]);
  const inspect=async()=>{setBusy(true);setError('');setApproved(false);const sig=signature,rev=project.revision;
    try{const r=await rpc<HierarchyPreview>('hierarchy.preview',{...request});if(live.current&&current.current===sig&&r.target_revision===rev){setPreview(r);setHidden(new Set());setView('delta');}}
    catch(e){if(live.current)setError(e instanceof Error?e.message:String(e));}finally{if(live.current)setBusy(false);}};
  const apply=async()=>{if(!validPreview||!approved)return;setBusy(true);setError('');if(receipt.current?.hash!==validPreview.preview_hash)receipt.current={hash:validPreview.preview_hash,id:crypto.randomUUID()};
    try{const p=await rpc<Project>('hierarchy.apply',{project_id:project.id,request:validPreview.request,preview_hash:validPreview.preview_hash,approved:true,expected_revision:validPreview.target_revision,command_id:receipt.current!.id});if(live.current)await onProject(p);}
    catch(e){if(live.current){setError(e instanceof Error?e.message:String(e));setApproved(false);}}finally{if(live.current)setBusy(false);}};
  return <section className="hierarchy-transfer" data-testid="hierarchy-transfer" aria-busy={busy}><div className="starter-scroll"><header className="starter-intro"><span>HIERARCHY · PREVIEW BEFORE APPLYING</span><h3>현재 배치에 어떤 변화가 생길까요?</h3><p>원본 정의를 복사해 새 이름으로 가져옵니다. 전체 상위 배치에 반복되는 하위 셀의 영향도 펼쳐서 확인합니다.</p></header>
    {error&&<p className="starter-error" role="alert">{error}</p>}<fieldset disabled={busy||!!disabledReason}><div className="hierarchy-modes"><button className={mode==='place'?'selected':''} onClick={()=>setMode('place')}>하위 계층 복사·배치</button><button className={mode==='wrap'?'selected':''} data-testid="hierarchy-wrap" onClick={()=>setMode('wrap')}>현재 설계를 상위 셀로 감싸기</button></div>
    {mode==='wrap'?<label className="modal-field">새 상위 셀 이름<input aria-label="상위 셀 이름" value={parent} onChange={e=>setParent(e.target.value)}/></label>:<>
      <div className="hierarchy-search"><input aria-label="계층 원본 검색" placeholder="설계 이름 또는 ID 검색" value={query} onChange={e=>setQuery(e.target.value)}/><button className="button small" onClick={()=>void refresh()}>원본 검색·새로고침</button><button className="button small" onClick={()=>{const v=clip();if(v){setSourceId(v.project_id);setSourceCell(v.cell);setQuery('');}else setError('회로도에서 계층 복사를 먼저 누르세요.');}}>복사한 계층 붙여넣기</button></div>
      <div className="starter-fields"><label>원본 설계<select aria-label="원본 설계" value={sourceId} onChange={e=>{const s=sources.find(v=>v.id===e.target.value);setSourceId(e.target.value);if(s)setSourceCell(s.cell);}}>{sources.map(s=><option key={s.id} value={s.id}>{s.name} · r{s.revision}</option>)}</select></label><label>원본 셀<select aria-label="원본 셀" value={sourceCell} onChange={e=>setSourceCell(e.target.value)}>{source?.cells.map(c=><option key={c.name} value={c.name}>{c.name}{c.root?' · TOP':''} · {c.ports.length} pins</option>)}</select></label><label>현재 설계의 대상 셀<select aria-label="대상 셀" value={target} onChange={e=>setTarget(e.target.value)}>{[project.cell,...Object.keys(project.schematic.cells||{})].map(n=><option key={n}>{n}</option>)}</select></label><label>가져올 새 이름<input aria-label="복사 계층 이름" value={namespace} onChange={e=>setNamespace(e.target.value)}/></label><label>적용 범위<select aria-label="계층 적용 범위" value={scope} onChange={e=>setScope(e.target.value as typeof scope)}><option value="both">회로도 + 물리 레이아웃</option><option value="schematic">회로도만</option><option value="layout">물리 레이아웃만</option></select></label></div>
      {scope!=='schematic'&&<div className="hierarchy-transform">{['X','Y'].map((axis,i)=><label key={axis}>{axis} (DBU)<input aria-label={`계층 ${axis} DBU`} value={position[i]} onChange={e=>setPosition(i===0?[e.target.value,position[1]]:[position[0],e.target.value])}/></label>)}<label>회전<select aria-label="계층 회전" value={rotation} onChange={e=>setRotation(Number(e.target.value) as typeof rotation)}>{[0,90,180,270].map(n=><option key={n} value={n}>{n}°</option>)}</select></label><label><input type="checkbox" checked={mirror} onChange={e=>setMirror(e.target.checked)}/>미러</label><span>{project.dbu_um} µm / DBU · {project.grid_dbu} DBU grid</span></div>}
      {scope!=='layout'&&<><h4>각 포트의 현재 설계 연결 넷</h4><div className="hierarchy-pins">{selected?.ports.map(p=><label key={p}><code>{p}</code><span>→</span><input aria-label={`계층 핀 ${p}`} value={pins[p]||''} onChange={e=>setPins({...pins,[p]:e.target.value})}/></label>)}</div><p className="starter-scope">전기적 연결은 위 넷 이름으로 명시합니다. 가져온 블록 사이의 물리 배선은 직접 연결한 후 LVS로 확인하세요.</p></>}
    </>}
    <button className="button" data-testid="hierarchy-preview" onClick={()=>void inspect()} disabled={mode==='place'&&!selected}>{busy?'전체 도형 계산 중…':'전체 영향 미리보기'}</button></fieldset>
    {validPreview&&<div className="hierarchy-preview" data-testid="hierarchy-preview-result"><div className="hierarchy-metrics"><div><small>전체 도형</small><strong>{validPreview.impact.before_shapes.toLocaleString()} → {validPreview.impact.after_shapes.toLocaleString()}</strong></div><div><small>마스크 형상</small><strong>{validPreview.impact.mask.mask_changed?'변화 있음':'유지'}</strong></div><div><small>같은 레이어의 겹침 영역</small><strong>{validPreview.impact.mask.overlap_count.toLocaleString()}</strong></div><div><small>오래되는 기존 실행</small><strong>{validPreview.impact.invalidated_runs}</strong></div></div>
      <div className="hierarchy-views" role="group" aria-label="계층 영향 미리보기 방식">{([['before','현재'],['delta','변경 겹쳐 보기'],['after','적용 후'],['3d','적용 후 3D']] as const).map(([v,t])=><button className={view===v?'selected':''} key={v} onClick={()=>setView(v)}>{t}</button>)}</div>
      {view==='3d'?<div className="hierarchy-3d"><LayoutViewer scene={validPreview.after} mode="3d" display={{renderLimit:1000000}} selection={null} onSelect={()=>{}} onCommand={async()=>{}} readOnly sourceLabel="승인 전 전체 배치 미리보기 · 레이어 높이는 표시용"/></div>:<ImpactCanvas preview={validPreview} view={view} hidden={hidden}/>}
      <p className="hierarchy-legend"><b>● 추가</b><span>● 기존</span><em>● 제거</em><mark>□ 겹침 영역</mark> · {validPreview.impact.added_shapes} 추가 / {validPreview.impact.removed_shapes} 제거 (계층 경로 ID 기준)</p>
      <details><summary>레이어 표시·마스크 면적 변화</summary><div className="hierarchy-layer-list">{validPreview.after.layers.map(l=>{const delta=validPreview.impact.mask.layers.find(x=>x.layer_id===l.id);return <label key={l.id}><input type="checkbox" checked={!hidden.has(l.id)} onChange={e=>setHidden(s=>{const n=new Set(s);if(e.target.checked)n.delete(l.id);else n.add(l.id);return n;})}/><span style={{color:l.color}}>{l.name} {l.id}</span><code>+{delta?.added_area_dbu2||0} / −{delta?.removed_area_dbu2||0} DBU²</code></label>;})}</div></details>
      <details><summary>가져올 셀 이름·핀 연결</summary><pre>{JSON.stringify({cells:validPreview.cell_mapping,pins:validPreview.pin_mapping,before_bounds:validPreview.impact.before_bounds,after_bounds:validPreview.impact.after_bounds},null,2)}</pre></details>
      <p className="starter-scope">전체 도형 미리보기 · 생략 없음 · 현재 r{validPreview.target_revision}{validPreview.source_revision?` / 원본 r${validPreview.source_revision}`:''}. 겹침은 실제 폴리곤 교차 검사이며 DRC나 단락 판정은 아닙니다.{validPreview.impact.mask.overlap_display_truncated?' 겹침 표시 상자는 첫 256개이며 총 개수·면적·전체 배치 도형은 전부 계산했습니다.':''}</p>
      <ul className="hierarchy-warnings">{validPreview.warnings.map(w=><li key={w}>{w}</li>)}</ul>
    </div>}
    </div><footer className="starter-footer"><div><label className="hierarchy-approval"><input data-testid="hierarchy-approve" type="checkbox" checked={approved} disabled={!validPreview||busy||!!disabledReason} onChange={e=>setApproved(e.target.checked)}/>전체 영향과 핀 연결을 확인하고 적용을 승인합니다.</label><span>{disabledReason||'입력·원본·현재 revision이 달라지면 다시 미리보기가 필요합니다. 적용은 Undo로 되돌릴 수 있습니다.'}</span></div><button className="button primary" data-testid="hierarchy-apply" disabled={!approved||!validPreview||busy||!!disabledReason} onClick={()=>void apply()}>{busy?'계산·처리 중…':'승인·적용'}</button></footer></section>;
}
