import { exportCadenceLayerMap, exportCompatBundle, type CompatInspection } from '@mos/importer';

function download(text: string, name: string) { const url = URL.createObjectURL(new Blob([text], { type: name.endsWith('.json') ? 'application/json' : 'text/plain' })), anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
export default function InterchangeMetadata({ inspection }: { inspection: CompatInspection }) {
  return <div className="ix-metadata" data-testid="interchange-metadata">
    <div className="ix-actions"><button className="button small" data-testid="interchange-export-metadata" onClick={() => download(exportCompatBundle(inspection), `${inspection.source.filename}.register-compat.json`)}>원문 / metadata / 미지원 항목 보관</button>{inspection.layerMap?.length && <button className="button small" data-testid="interchange-export-map" onClick={() => download(exportCadenceLayerMap(inspection), `${inspection.source.filename}.layermap`)}>명시적 stream map 내보내기</button>}</div>
    {inspection.technology && <><h4>Technology 이름 / 내부 번호</h4><p className="ix-note">내부 layer / purpose 번호는 GDS 번호가 아닙니다. 명시적 stream map에만 GDS layer/datatype 대응을 적용합니다.</p><table className="ix-table" data-testid="interchange-tech-layers"><thead><tr><th>종류</th><th>이름</th><th>내부 번호</th><th>약어</th></tr></thead><tbody>{inspection.technology.layers.map(row => <tr key={`layer-${row.name}`}><td>Layer</td><td>{row.name}</td><td>{row.number}</td><td>{row.abbreviation}</td></tr>)}{inspection.technology.purposes.map(row => <tr key={`purpose-${row.name}`}><td>Purpose</td><td>{row.name}</td><td>{row.number}</td><td>{row.abbreviation}</td></tr>)}</tbody></table><p className="ix-note">실제 display packet {inspection.technology.packets.length}개 · RGB color {inspection.technology.colors.length}개 · LPP display {inspection.technology.displays.length}개</p></>}
    {inspection.layerMap && <><h4>명시적 LPP → GDS</h4><table className="ix-table" data-testid="interchange-stream-map"><thead><tr><th>Layer</th><th>Purpose</th><th>GDS layer/datatype</th><th>상태</th></tr></thead><tbody>{inspection.layerMap.map((row, index) => <tr key={index}><td>{row.layer}</td><td>{row.purpose}</td><td>{row.gds.join(' / ')}</td><td>{row.enabled ? '적용 가능' : 'translate 비활성'}</td></tr>)}</tbody></table></>}
    {inspection.libraries && <><h4>Library 참조</h4><p className="ix-note">파일에 선언된 이름과 경로만 읽습니다. 환경변수 / include를 확장하거나 OA database를 열지 않습니다.</p><table className="ix-table" data-testid="interchange-library-refs"><thead><tr><th>Library</th><th>원본 경로</th><th>상태</th></tr></thead><tbody>{inspection.libraries.references.map((row, index) => <tr key={index}><td>{row.name}</td><td>{row.path}</td><td>{row.unresolved ? '해결되지 않은 참조' : '문자열 참조'}</td></tr>)}</tbody></table><details><summary>원본 library 지시문</summary><pre>{JSON.stringify(inspection.libraries.directives, null, 2)}</pre></details></>}
    {inspection.spice && <><h4>Subcircuit / 명시적 pin 순서</h4><table className="ix-table" data-testid="interchange-subcircuits"><thead><tr><th>Cell</th><th>Ports</th><th>Devices</th><th>Parameters</th></tr></thead><tbody>{inspection.spice.subcircuits.map(cell => <tr key={cell.name}><td>{cell.name}</td><td>{cell.ports.join(' · ')}</td><td>{cell.devices.length}</td><td>{cell.parameters.join(' ')}</td></tr>)}</tbody></table><p className="ix-note">Globals: {inspection.spice.globals.join(' · ') || '없음'} · Model 선언 {inspection.spice.models.length}개 · 외부 참조 {inspection.spice.references.length}개. 읽은 metadata는 모델 실행 / LVS / schematic 재구성 검증과 별도입니다.</p>{inspection.spice.subcircuits.map(cell => <details key={cell.name}><summary>{cell.name} 실제 device / PININFO</summary><pre>{JSON.stringify({ ports: cell.ports, pinInfo: cell.pinInfo, devices: cell.devices }, null, 2)}</pre></details>)}<details><summary>Models / library 참조</summary><pre>{JSON.stringify({ models: inspection.spice.models, references: inspection.spice.references }, null, 2)}</pre></details></>}
    {inspection.unsupported.length > 0 && <details open><summary>미지원 구문 원문 보존 · {inspection.unsupported.length}개</summary><pre data-testid="interchange-unsupported">{inspection.unsupported.map(part => `${part.line}: ${part.name} · ${part.reason}\n${part.raw}`).join('\n\n')}</pre></details>}
    <details><summary>전체 로컬 검사 metadata</summary><pre>{JSON.stringify({ ...inspection, source: { filename: inspection.source.filename }, companion_sources: inspection.companion_sources?.map(source => ({ filename: source.filename })) }, null, 2)}</pre></details>
  </div>;
}
