import { useEffect, useState } from 'react';
import { rpc, type CompatibilityExportResult, type CompatibilityFile, type CompatibilityImportResult, type CompatibilityOptions, type CompatibilityReport, type Project, type Run, type Scene } from '@mos/contracts';
import { parseMappedResultText, type ResultTableSchema } from '@mos/importer';
import LayerMappingEditor from './LayerMappingEditor';

export interface InterchangeSource { id: string; name: string; buffer: ArrayBuffer; }
interface Props {
  files: InterchangeSource[]; preset: string; project?: Project | null; transport: typeof rpc; readOnly?: boolean; shared?: boolean;
  engineUnavailableReason?: string; onOpenWorkspace?: () => void;
  onProject?: (project: Project, scene: Scene, files?: InterchangeSource[]) => void | Promise<void>; onNativeProject?: (project: Project) => void | Promise<void>; onRun?: (run: Run) => void | Promise<void>;
  suggestedLayerMap?: CompatibilityOptions['layer_map']; localScene?: Scene | null;
  onReport?: (report: CompatibilityReport) => void;
}
const encode = (buffer: ArrayBuffer) => { let text = ''; const bytes = new Uint8Array(buffer); for (let offset = 0; offset < bytes.length; offset += 32768) text += String.fromCharCode(...bytes.subarray(offset, offset + 32768)); return btoa(text); };
const decode = (value: string) => Uint8Array.from(atob(value), item => item.charCodeAt(0));
const errorText = (cause: unknown) => cause instanceof Error ? cause.message : String(cause);
function download(file: CompatibilityFile) { const url = URL.createObjectURL(new Blob([decode(file.base64)], { type: file.mime || 'application/octet-stream' })), anchor = document.createElement('a'); anchor.href = url; anchor.download = file.name; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function csvHeaders(buffer: ArrayBuffer | undefined): string[] { if (!buffer) return []; const line = new TextDecoder().decode(buffer.slice(0, 16384)).split(/\r?\n/)[0].replace(/^\uFEFF/, ''); const result: string[] = []; let value = '', quoted = false; for (let i = 0; i < line.length; i++) { const char = line[i]; if (char === '"') { if (quoted && line[i + 1] === '"') { value += '"'; i++; } else quoted = !quoted; } else if (char === ',' && !quoted) { result.push(value.trim()); value = ''; } else value += char; } result.push(value.trim()); return [...new Set(result.filter(Boolean))]; }
interface SignalInput { column: string; name: string; unit: string; }
interface BranchInput extends SignalInput { from_net: string; to_net: string; }

export default function InterchangeNativeActions({ files, preset, project: supplied, transport, readOnly, shared, engineUnavailableReason, onOpenWorkspace, onProject, onNativeProject, onRun, onReport, suggestedLayerMap, localScene }: Props) {
  const [project, setProject] = useState<Project | null>(supplied || null), [busy, setBusy] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState('명시적으로 파일을 전송하고 구조 검사 / 프로젝트 적용을 진행하세요.');
  const [report, setReport] = useState<CompatibilityReport | null>(null), [inspectedStamp, setInspectedStamp] = useState('');
  const [top, setTop] = useState(''), [netlistTop, setNetlistTop] = useState(''), [netlistFile, setNetlistFile] = useState(''), [librarySection, setLibrarySection] = useState(''), [dbu, setDbu] = useState('');
  const [layerMap, setLayerMap] = useState('[]'), [allowUnmapped, setAllowUnmapped] = useState(false);
  const [resultFile, setResultFile] = useState(''), [operation, setOperation] = useState('simulation'), [resultFormat, setResultFormat] = useState('csv'), [resultRole, setResultRole] = useState('waves'), [analysis, setAnalysis] = useState('tran');
  const [xColumn, setXColumn] = useState(''), [xUnit, setXUnit] = useState('s'), [signals, setSignals] = useState<SignalInput[]>([]), [branches, setBranches] = useState<BranchInput[]>([]), [advanced, setAdvanced] = useState('{}');
  const [result, setResult] = useState<Run | null>(null), [exportReport, setExportReport] = useState<CompatibilityReport | null>(null);
  const importedHistory = project?.runs.filter(run => run.workflow === 'imported-results') || [];
  useEffect(() => { if (supplied) setProject(supplied); }, [supplied]);
  const optionsText = JSON.stringify({ preset, top, netlistTop, netlistFile, librarySection, dbu, layerMap, allowUnmapped });
  const stamp = files.map(file => `${file.id}:${file.name}`).join('|') + optionsText;
  const forbidden = !!busy || readOnly || !!engineUnavailableReason;
  const selectedFile = files.find(file => file.name === resultFile), headers = csvHeaders(selectedFile?.buffer);
  const action = async (label: string, work: () => Promise<void>) => { setBusy(label); setError(''); try { await work(); } catch (cause) { setError(errorText(cause)); } finally { setBusy(''); } };
  const payload = (): CompatibilityFile[] => { if (!files.length || files.length > 32) throw new Error('1–32개 파일을 선택하세요.'); if (new Set(files.map(file => file.name)).size !== files.length) throw new Error('같은 이름의 파일이 있습니다. 원본 파일 이름을 구분하세요.'); if (files.some(file => file.buffer.byteLength > 16 * 1024 * 1024) || files.reduce((sum, file) => sum + file.buffer.byteLength, 0) > 32 * 1024 * 1024) throw new Error('Native 전송은 파일당 16 MiB, 전체 32 MiB 제한입니다.'); return files.map(file => ({ name: file.name, base64: encode(file.buffer) })); };
  const options = (): CompatibilityOptions => {
    const mapping = JSON.parse(layerMap); if (!Array.isArray(mapping) || mapping.some(row => !row || typeof row.name !== 'string' || !Number.isInteger(row.layer) || !Number.isInteger(row.datatype) || row.layer < 0 || row.layer > 65535 || row.datatype < 0 || row.datatype > 65535)) throw new Error('Layer map은 [{name,layer,datatype,purpose?}] 배열이며 GDS 번호는 0–65535 정수입니다.');
    if (dbu && (!Number.isFinite(Number(dbu)) || Number(dbu) <= 0)) throw new Error('DBU는 양의 µm 값이어야 합니다.');
    return { source_tool: preset, ...(top ? { top_cell: top } : {}), ...(netlistTop ? { netlist_top: netlistTop } : {}), ...(netlistFile ? { netlist_file: netlistFile } : {}), ...(librarySection ? { library_section: librarySection } : {}), ...(dbu ? { dbu_um: Number(dbu) } : {}), lef_files: files.filter(file => /\.lef$/i.test(file.name)).map(file => file.name), macro_files: files.some(file => /\.def$/i.test(file.name)) ? files.filter(file => /\.(gds(ii)?|oas(is)?)$/i.test(file.name)).map(file => file.name) : [], ...(mapping.length ? { layer_map: mapping } : {}), allow_unmapped_layers: allowUnmapped } as CompatibilityOptions;
  };
  const ensureProject = async () => { if (project) return project; if (shared) throw new Error('공유 프로젝트를 공동 설계에서 먼저 여세요.'); const next = await transport<Project>('project.create', { name: `${files[0]?.name || 'Interchange'} · EDA import`, example: 'fixture' }); setProject(next); return next; };
  const inspect = () => void action('Native 형식 / layout / netlist 구조 검사 중', async () => { const next = await transport<CompatibilityReport>('compat.inspect', { files: payload(), options: options() }); setReport(next); setInspectedStamp(stamp); onReport?.(next); setNotice('실제 native 구조 검사 결과입니다. 형식별 지원 범위와 손실 항목을 확인하세요.'); });
  const apply = () => void action('교환 파일을 프로젝트 새 revision에 적용 중', async () => { if (!report || inspectedStamp !== stamp) throw new Error('현재 파일과 옵션으로 먼저 구조 검사를 진행하세요.'); const target = await ensureProject(); const next = await transport<CompatibilityImportResult>('compat.import', { project_id: target.id, files: payload(), options: options(), expected_revision: target.revision, command_id: crypto.randomUUID() }); setProject(next.project); setReport(next.report); onReport?.(next.report); const nextScene = await transport<Scene>('view.get_scene', { project_id: next.project.id, max_shapes: 2000 }); await onProject?.(next.project, nextScene, files); setNotice(`실제 교환 파일 적용됨 · ${next.project.cell} · r${next.project.revision}`); });
  const exportFiles = (format: string) => void action(`실제 ${format.toUpperCase()} 내보내기 / roundtrip 검사 중`, async () => { if (!project) throw new Error('Native 프로젝트가 필요합니다.'); const next = await transport<CompatibilityExportResult>('compat.export', { project_id: project.id, format }); setExportReport(next.report); for (const file of next.files) download(file); setNotice(`${next.files.length}개 실제 파일을 내보냈습니다. 원본 파일 / metadata 보존과 손실 보고를 확인하세요.`); });
  const importResult = () => void action('외부 결과 파일을 실제 파서로 가져오는 중 · 엔진 실행 없음', async () => {
    if (!selectedFile) throw new Error('실제 결과 파일을 선택하세요.'); const extra = JSON.parse(advanced); if (!extra || typeof extra !== 'object' || Array.isArray(extra)) throw new Error('추가 결과 context는 JSON 객체여야 합니다.');
    const mapped = ['csv', 'table', 'psf-ascii'].includes(resultFormat); const schema = { x: { column: xColumn, unit: xUnit }, signals: signals.map(row => ({ ...row, name: row.name || row.column })), branches: branches.map((row, index) => ({ ...row, id: `branch-${index + 1}`, name: row.name || row.column, source_vector: row.column })) };
    if (mapped && (!xColumn || !signals.length && !branches.length || signals.some(row => !row.column || !row.unit) || branches.some(row => !row.column || !['A', 'mA', 'uA', 'µA', 'nA', 'pA'].includes(row.unit) || !row.from_net || !row.to_net))) throw new Error('X열 / 단위와 적어도 한 개 signal 또는 전류 branch를 지정하세요. 전류 단위와 from / to net 선언이 필요합니다.');
    const target = await ensureProject(); const context = { ...extra, analysis, formats: { [resultRole]: resultFormat }, ...(mapped ? { column_schema: schema, wave_schema: schema, current_schema: schema } : {}) };
    const next = await transport<Run>('compat.import_results', { project_id: target.id, files: payload(), options: { source_tool: preset, results: { operation, outputs: { [resultRole]: resultFile }, context } }, expected_revision: target.revision, command_id: crypto.randomUUID() }); setResult(next); const withRun = { ...target, runs: [...target.runs.filter(run => run.id !== next.id), next] }; setProject(withRun); await onNativeProject?.(withRun); await onRun?.(next); setNotice(`외부 파일 결과 ${next.id.slice(0, 10)} · ${next.analysis_result} · 실제 vendor 실행 확인과 구분합니다.`);
  });
  const previewResult = () => void action('명시적 열 / 단위로 외부 수치를 로컬에서 읽는 중', async () => {
    if (!selectedFile || resultFormat !== 'csv') throw new Error('로컬 표 미리보기는 명시적 CSV 입력을 사용합니다. 다른 형식은 native 파서를 사용하세요.');
    const schema: ResultTableSchema = { delimiter: 'csv', header: true, x: { column: xColumn, unit: xUnit }, series: signals.map(row => ({ ...row, name: row.name || row.column })), branches: branches.map((row, index) => ({ ...row, id: `branch-${index + 1}`, name: row.name || row.column, source_vector: row.column })), convention: 'conventional', analysis: analysis as 'op' | 'dc' | 'tran', source: 'imported' };
    const id = `local-import-${crypto.randomUUID()}`, identity = localScene || project; const parsed = parseMappedResultText(new TextDecoder().decode(selectedFile.buffer), schema, { project_id: identity ? ('project_id' in identity ? identity.project_id : identity.id) : undefined, revision: identity?.revision || 0, run_id: id, tool: preset });
    const next: Run = { id, project_id: identity && ('project_id' in identity ? identity.project_id : identity.id) || 'external-results', revision: identity?.revision || 0, kind: 'simulation', workflow: 'imported-results', execution_status: 'completed', analysis_result: 'pass', freshness: 'current', tool: preset, waveforms: parsed.waveforms, current_flow: parsed.currentFlow, measurements: { analysis, native_execution: 'false', vendor_execution_verified: 'false', source_file: selectedFile.name }, message: '브라우저에서 읽은 외부 파일 수치 · 엔진 실행 없음 · 물리적 대응 미검증' };
    setResult(next); await onRun?.(next); setNotice('원본 CSV를 명시적 단위로 읽었습니다. 서버 전송 / vendor 실행은 없으며 물리적 대응은 미검증입니다.');
  });
  const columnSelect = (value: string, change: (value: string) => void, label: string) => <select aria-label={label} value={value} onChange={event => change(event.target.value)}><option value="">열을 명시적으로 선택</option>{headers.map(header => <option key={header} value={header}>{header}</option>)}</select>;
  return <div className="ix-native" data-testid="interchange-native">
    {engineUnavailableReason && <div className="pdk-engine-required">{engineUnavailableReason}{onOpenWorkspace && <button className="button small" onClick={onOpenWorkspace}>공동 설계 열기</button>}</div>}
    {busy && <p role="status">{busy}</p>}{error && <pre role="alert" data-testid="interchange-native-error" className="inline-error">{error}</pre>}
    <div className="ix-scope"><strong data-testid="interchange-project">{project ? `${project.name} · ${project.id} · r${project.revision}` : '적용할 때 별도 native 프로젝트를 생성합니다.'}</strong><p>{shared ? '인증된 editor / owner가 공유 프로젝트에 적용합니다.' : '파일당 16 MiB · 전체 32 MiB · 최대 32개. 적용은 실제 새 revision이며 원본 파일은 유지합니다.'}</p></div>
    <details open><summary>Layout / library / netlist 입력 조건</summary><div className="ix-fields"><label>Layout top cell<input data-testid="interchange-top" value={top} onChange={event => setTop(event.target.value)} placeholder="파일 구조 검사에서 확인"/></label><label>Netlist top subcircuit<input data-testid="interchange-netlist-top" value={netlistTop} onChange={event => setNetlistTop(event.target.value)}/></label><label>Netlist 원본 파일<select data-testid="interchange-netlist-file" value={netlistFile} onChange={event => setNetlistFile(event.target.value)}><option value="">형식 검사에서 결정</option>{files.map(file => <option key={file.id} value={file.name}>{file.name}</option>)}</select></label><label>SPICE library section<input data-testid="interchange-library-section" value={librarySection} onChange={event => setLibrarySection(event.target.value)}/></label><label>Layout DBU (µm)<input data-testid="interchange-dbu" value={dbu} onChange={event => setDbu(event.target.value)} placeholder="파일 단위 사용"/></label></div><p className="ix-note">LEF 파일은 업로드 순서대로, macro GDS/OAS는 DEF와 함께 전달합니다. LEF/DEF 도형을 공정 레이어에 대응하려면 실제 stream map이 필요합니다.</p>{suggestedLayerMap?.length ? <button className="button small" data-testid="interchange-use-stream-map" onClick={() => setLayerMap(JSON.stringify(suggestedLayerMap, null, 2))}>선택한 파일의 명시적 stream map 사용</button> : null}<LayerMappingEditor value={layerMap} onChange={setLayerMap}/><label className="checkbox-label"><input data-testid="interchange-allow-unmapped" type="checkbox" checked={allowUnmapped} onChange={event => setAllowUnmapped(event.target.checked)}/>미대응 레이어의 제한된 표시를 허용합니다 · 손실 보고 확인 필요</label><div className="ix-actions"><button className="button" data-testid="interchange-inspect-native" disabled={!files.length || !!busy || !!engineUnavailableReason} onClick={inspect}>실제 파일 구조 검사</button><button className="button primary" data-testid="interchange-import-native" disabled={forbidden || !report || inspectedStamp !== stamp || report.supported === false} onClick={apply}>프로젝트에 명시적 적용</button></div>{report && <details open><summary>Native 검사 / 손실 보고{inspectedStamp !== stamp ? ' · 옵션 변경으로 재검사 필요' : ''}</summary><table className="ix-table" data-testid="interchange-native-files"><thead><tr><th>파일</th><th>실제 형식 / 상태</th><th>지원 범위</th></tr></thead><tbody>{report.files.map(entry => <tr key={entry.name}><td>{entry.name}</td><td>{entry.format} · {entry.status}</td><td>{entry.capabilities.join(" / ")}{entry.warnings.map((warning, index) => <p className="ix-note" key={index}>{warning}</p>)}</td></tr>)}</tbody></table>{report.checks?.map((check, index) => <p className="ix-note" key={index}>{check.status} · {check.name}: {check.message}</p>)}{report.losses?.map((loss, index) => <p className="ix-note" key={index}>손실 / 제한 · {loss}</p>)}<details><summary>전체 실제 검사 metadata</summary><pre data-testid="interchange-report">{JSON.stringify(report, null, 2)}</pre></details></details>}</details>
    <details><summary>외부 해석 / DRC / LVS / PEX 결과 파일</summary><p className="ix-note">파일에 저장된 실제 수치를 가져옵니다. 선택한 vendor 도구를 실행하지 않습니다. 열 이름으로 단위·단자·물리 경로를 추정하지 않습니다.</p><div className="ix-fields"><label>실제 결과 파일<select data-testid="interchange-result-file" value={resultFile} onChange={event => setResultFile(event.target.value)}><option value="">파일 선택</option>{files.map(file => <option key={file.id} value={file.name}>{file.name}</option>)}</select></label><label>작업<select data-testid="interchange-result-operation" value={operation} onChange={event => setOperation(event.target.value)}>{['simulation', 'drc', 'lvs', 'pex'].map(value => <option key={value}>{value}</option>)}</select></label><label>결과 역할<select data-testid="interchange-result-role" value={resultRole} onChange={event => setResultRole(event.target.value)}>{['waves', 'currents', 'summary', 'rc', 'exchange'].map(value => <option key={value}>{value}</option>)}</select></label><label>실제 파서 형식<select data-testid="interchange-result-format" value={resultFormat} onChange={event => setResultFormat(event.target.value)}>{['csv', 'table', 'psf-ascii', 'register-exchange-v1', 'hspice-lis', 'calibre-drc-summary', 'calibre-lvs-summary', 'spef', 'dspf', 'spice-rc'].map(value => <option key={value}>{value}</option>)}</select></label><label>해석<select data-testid="interchange-result-analysis" value={analysis} onChange={event => setAnalysis(event.target.value)}>{['op', 'dc', 'tran'].map(value => <option key={value}>{value}</option>)}</select></label></div>
    {['csv', 'table', 'psf-ascii'].includes(resultFormat) && <><div className="ix-fields"><label>X column{resultFormat === 'csv' ? columnSelect(xColumn, setXColumn, '결과 X열') : <input aria-label="결과 X열" value={xColumn} onChange={event => setXColumn(event.target.value)}/>}</label><label>X SI unit<select aria-label="결과 X단위" value={xUnit} onChange={event => setXUnit(event.target.value)}>{['s', 'ms', 'us', 'ns', 'ps', 'V', 'mV', '1'].map(unit => <option key={unit}>{unit}</option>)}</select></label></div><div className="ix-actions"><button className="button small" data-testid="interchange-add-signal" onClick={() => setSignals(current => [...current, { column: '', name: '', unit: 'V' }])}>Signal 열 추가</button><button className="button small" data-testid="interchange-add-current" onClick={() => setBranches(current => [...current, { column: '', name: '', unit: 'A', from_net: '', to_net: '' }])}>전류 branch 열 추가</button></div>{signals.map((row, index) => <div className="ix-mapping-row" key={index}>{columnSelect(row.column, column => setSignals(current => current.map((item, i) => i === index ? { ...item, column } : item)), `Signal ${index + 1} column`)}<input aria-label={`Signal ${index + 1} name`} placeholder="신호 이름" value={row.name} onChange={event => setSignals(current => current.map((item, i) => i === index ? { ...item, name: event.target.value } : item))}/><select aria-label={`Signal ${index + 1} unit`} value={row.unit} onChange={event => setSignals(current => current.map((item, i) => i === index ? { ...item, unit: event.target.value } : item))}>{['V', 'mV', 'uV', 'A', 'mA', 'uA', '1'].map(unit => <option key={unit}>{unit}</option>)}</select><button className="text-button" onClick={() => setSignals(current => current.filter((_, i) => i !== index))}>삭제</button></div>)}{branches.map((row, index) => <div className="ix-mapping-row ix-branch-row" key={index}>{columnSelect(row.column, column => setBranches(current => current.map((item, i) => i === index ? { ...item, column } : item)), `전류 ${index + 1} column`)}{(['name', 'from_net', 'to_net'] as const).map(key => <input key={key} aria-label={`전류 ${index + 1} ${key}`} placeholder={key} value={row[key]} onChange={event => setBranches(current => current.map((item, i) => i === index ? { ...item, [key]: event.target.value } : item))}/>)}<select aria-label={`전류 ${index + 1} unit`} value={row.unit} onChange={event => setBranches(current => current.map((item, i) => i === index ? { ...item, unit:event.target.value } : item))}>{['A', 'mA', 'uA', 'nA', 'pA'].map(unit => <option key={unit}>{unit}</option>)}</select><button className="text-button" onClick={() => setBranches(current => current.filter((_, i) => i !== index))}>삭제</button></div>)}<p className="ix-note">CSV는 header의 실제 열을 선택합니다. 지정한 A/mA/µA 등 단위로 실제 수치를 SI로 정규화하며 원본 파일과 부호를 유지합니다.</p></>}
    <details><summary>추가 결과 context · measurements / completion 등</summary><textarea data-testid="interchange-result-context" value={advanced} onChange={event => setAdvanced(event.target.value)} spellCheck={false}/></details><div className="ix-actions"><button className="button" data-testid="interchange-preview-results" disabled={!!busy || !selectedFile || resultFormat !== "csv"} onClick={previewResult}>수치 로컬 미리보기 · 서버 전송 없음</button><button className="button primary" data-testid="interchange-import-results" disabled={forbidden || !selectedFile} onClick={importResult}>외부 결과 수치 가져오기</button></div>{importedHistory.length > 0 && <div className="ix-result-history" data-testid="interchange-result-history">{importedHistory.map(run => <button key={run.id} className="button small" data-testid="interchange-history-row" data-run-id={run.id} onClick={() => { setResult(run); void onRun?.(run); }}>{run.id.slice(0, 10)} · {run.kind} · {run.analysis_result} · r{run.revision}</button>)}</div>}{result && <div className="ix-scope" data-testid="interchange-result"><strong>{result.id} · {result.analysis_result} · imported result</strong><p>{result.message}</p><pre>{JSON.stringify({ current_flow: result.current_flow, waveforms: result.waveforms, measurements: result.measurements, parasitics: result.parasitics }, null, 2)}</pre><button className="button small" data-testid="interchange-result-download" onClick={() => { const text = JSON.stringify(result, null, 2); download({ name: `imported-result-${result.id}.json`, base64: encode(new TextEncoder().encode(text).buffer), mime: 'application/json' }); }}>가져온 실제 결과 JSON 저장</button></div>}</details>
    <details><summary>프로젝트 표준 파일 / roundtrip 내보내기</summary><div className="ix-actions">{['gds', 'oas', 'cdl', 'spice'].map(format => <button key={format} className="button small" data-testid={`interchange-export-${format}`} disabled={!project || !!busy || !!engineUnavailableReason} onClick={() => exportFiles(format)}>{format.toUpperCase()} 실제 파일 저장</button>)}</div>{exportReport && <pre data-testid="interchange-export-report">{JSON.stringify(exportReport, null, 2)}</pre>}</details>
    <p className="ix-status" data-testid="interchange-native-state">{notice}</p>
  </div>;
}
