import { useEffect, useMemo, useRef, useState } from 'react';
import { centre,depositionCoverage,depositionCoverageCsv, parseVolumeJSON, parseVtu, processCsv, stageVolume,validateRun,validateVolume,volumeVtu,volumeVtuSettings, type DepositionFace,type ProcessRun,type ProcessCriteria, type ProcessInspection, type ProcessVolume, type VtuOptions } from '../../process/src/index';
import type { Scene } from '../../contracts/src/index';
import demo from '../../../examples/process/step-keyhole.process.json';
import ProcessMeshViewer from './ProcessMeshViewer';
import ProcessRecipeEditor from './ProcessRecipeEditor';
import './process.css';

export interface ProcessDocument {volume:ProcessVolume;criteria:ProcessCriteria;process_run?:ProcessRun;selected_stage?:number}
export function readProcessDocument(value:unknown):ProcessDocument {
  if(!value||typeof value!=='object'||!('volume' in value)||!('criteria' in value))throw new Error('공정 체적과 검토 기준이 필요합니다.');
  const doc=value as ProcessDocument;validateVolume(doc.volume);
  if(!doc.criteria||!Number.isFinite(doc.criteria.min_thickness_um)||doc.criteria.min_thickness_um<0||!Number.isFinite(doc.criteria.min_coverage_ratio)||doc.criteria.min_coverage_ratio<0||doc.criteria.min_coverage_ratio>1)throw new Error('공정 검토 기준이 잘못됐습니다.');
  if(doc.process_run){const run=validateRun(doc.process_run);if(!Number.isSafeInteger(doc.selected_stage)||Number(doc.selected_stage)<0||Number(doc.selected_stage)>=run.stages.length)throw new Error('저장된 선택 단계가 잘못됐습니다.');const expected=stageVolume(run,doc.selected_stage!);for(const field of ['points_um','cells','materials'] as const)if(JSON.stringify(doc.volume[field])!==JSON.stringify(expected[field]))throw new Error('저장 체적과 선택된 공정 history 형상이 다릅니다.');return {volume:doc.volume,criteria:doc.criteria,process_run:run,selected_stage:doc.selected_stage};}
  return {volume:doc.volume,criteria:doc.criteria};
}
const defaults:ProcessCriteria={min_thickness_um:.03,min_coverage_ratio:.5};
const issueNames={thin:'박막화','low-coverage':'피복률 부족',uncovered:'두께 0',unknown:'두께 미평가'};
const download=(name:string,text:string,type='application/json')=>{const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const nm=(value:number|null)=>value===null?'미평가':`${(value*1000).toPrecision(5).replace(/0+$/,'').replace(/\.$/,'')} nm`;
export default function ProcessPanel({document:doc,onDocument:saveDocument,context,scene}:{document:ProcessDocument|null;onDocument:(next:ProcessDocument|null)=>void;context?:{project_id:string;revision:number};scene?:Scene|null}) {
  const [report,setReport]=useState<ProcessInspection|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[sha,setSha]=useState<string|null>(null);
  const [vtu,setVtu]=useState(''),[options,setOptions]=useState<VtuOptions|null>(null),[selected,setSelected]=useState<number|null>(null),[visible,setVisible]=useState<number[]>([]),[heat,setHeat]=useState(false);
  const [axis,setAxis]=useState<'none'|'x'|'y'|'z'>('none'),[position,setPosition]=useState(0),[region,setRegion]=useState('all'),[bind,setBind]=useState(false);
  const [selectedCoating,setSelectedCoating]=useState<DepositionFace|null>(null);
  const worker=useRef<Worker|null>(null),importSequences=useRef({json:0,vtu:0,options:0}),volume=doc?.volume;
  const coating=useMemo(()=>{const run=doc?.process_run,index=doc?.selected_stage||0,step=run?.recipe.steps[index-1];return run&&step?.kind==='deposit'?depositionCoverage(run.recipe,run.stages[index-1].material_ids,run.stages[index].material_ids,step):null;},[doc?.process_run,doc?.selected_stage]);
  const coatingRiskCells=useMemo(()=>coating?.faces.filter(f=>!f.thickness_um).flatMap(f=>Array.from({length:6},(_,i)=>f.surface_voxel*6+i)),[coating]);
  const onDocument=(next:ProcessDocument|null)=>{importSequences.current.json++;saveDocument(next);};
  useEffect(()=>{if(!volume)return;setVisible(volume.materials.filter(m=>m.role!=='void').map(m=>m.id));setSelected(null);setSelectedCoating(null);setAxis('none');setPosition(volume.scope.domain_um[0][2]);setRegion('all');setBind(false);setSha(null);
    let current=true;const bytes=new TextEncoder().encode(JSON.stringify(volume));if(crypto.subtle)void crypto.subtle.digest('SHA-256',bytes).then(hash=>{if(current)setSha(Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join(''));});return()=>{current=false;};
  },[volume]);
  useEffect(()=>{
    worker.current?.terminate();setReport(null);setError('');if(!doc){setBusy(false);return;}setBusy(true);
    const next=new Worker(new URL('./process-worker.ts',import.meta.url),{type:'module'});worker.current=next;
    next.onmessage=event=>{setBusy(false);if(event.data.ok)setReport(event.data.report);else setError(event.data.message);next.terminate();};next.onerror=event=>{setBusy(false);setError(`검사 worker: ${event.message}`);next.terminate();};next.postMessage({volume:doc.volume,criteria:doc.criteria});
    return()=>{next.terminate();};
  },[doc]);
  useEffect(()=>()=>{for(const key of ['json','vtu','options'] as const)importSequences.current[key]++;},[]);
  const file=async(file:File,work:(text:string)=>void,slot:'json'|'vtu'|'options'='json')=>{const sequence=++importSequences.current[slot];try{if(!file.size||file.size>32*1024*1024)throw new Error('공정 파일은 0 초과~32 MiB이어야 합니다.');const text=await file.text();if(sequence===importSequences.current[slot]){work(text);setError('');}}catch(error){if(sequence===importSequences.current[slot])setError(error instanceof Error?error.message:String(error));}};
  const loadJSON=(text:string)=>{const value=JSON.parse(text);onDocument(value.kind==='register-process-volume'?{volume:parseVolumeJSON(text),criteria:{...defaults}}:readProcessDocument(value));};
  const choose=(index:number)=>{if(!volume)return;setSelected(index);setSelectedCoating(null);setVisible(ids=>[...new Set([...ids,volume.cells[index].material_id])]);setAxis('z');setPosition(centre(volume,index)[2]);};
  const materialZ=useMemo(()=>{const ranges=new Map<number,[number,number]>();if(volume)for(const cell of volume.cells){const range=ranges.get(cell.material_id)||[Infinity,-Infinity];for(const i of cell.vertices){range[0]=Math.min(range[0],volume.points_um[i][2]);range[1]=Math.max(range[1],volume.points_um[i][2]);}ranges.set(cell.material_id,range);}return ranges;},[volume]);
  const limits=(id:number)=>doc?.criteria.by_material?.[String(id)]||doc?.criteria||defaults;
  const updateLimits=(id:number,field:'min_thickness_um'|'min_coverage_ratio',value:number)=>{if(doc)onDocument({...doc,criteria:{...doc.criteria,by_material:{...doc.criteria.by_material,[String(id)]:{...limits(id),[field]:value}}}});};
  const fresh=volume?.association&&context?volume.association.project_id===context.project_id&&volume.association.revision===context.revision:'independent';
  const axisIndex=axis==='x'?0:axis==='y'?1:2,lo=volume?.scope.domain_um[0][axisIndex]||0,hi=volume?.scope.domain_um[1][axisIndex]||1;
  const activeCell=selected!==null?volume?.cells[selected]:null,material=volume?.materials.find(m=>m.id===activeCell?.material_id);
  const issues=report?.issues.filter(issue=>region==='all'||volume?.cells[issue.cell].region===region)||[];
  const uniqueIssues=[...new Map(issues.map(issue=>[issue.cell,issue])).values()];
  const fields=volume?Array.from(new Set(volume.cells.map(c=>c.region).filter((v):v is string=>!!v))):[];
  return <section className="process-panel" data-testid="process-panel"><div className="process-intro"><div><span className="process-eyebrow">PROCESS TOPOGRAPHY</span><h3>홀·단차·다층 공정의 3D 검토</h3><p>같은 재료가 서로 다른 높이에 놓인 XYZ 체적과 국부 두께를 확인합니다. 제출한 mesh 전체를 검사하며 화면의 숨김·단면은 검사 범위를 줄이지 않습니다.</p></div><div className="process-inputs"><label className="button small">공정 JSON 열기<input type="file" data-testid="process-json-input" accept=".json" onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void file(f,loadJSON);}}/></label><button data-testid="process-demo" onClick={()=>onDocument({volume:validateVolume(demo),criteria:{...defaults}})}>교육용 홀·단차 예제</button></div></div>
    <ProcessRecipeEditor document={doc} onDocument={onDocument} scene={scene}/>
    <details className="process-vtu"><summary>해석·실측 mesh 가져오기 · VTU 설정</summary><p>단일 Piece / ASCII / 사면체 VTU와 별도 단위·재료·두께 array·출처 설정 JSON을 입력하세요. TDR·STR 원본과 binary VTU는 도구의 표준 export가 필요합니다.</p><div className="process-file-row"><label>VTU mesh<input data-testid="process-vtu-input" type="file" accept=".vtu" onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void file(f,setVtu,'vtu');}}/></label><label>설정 JSON<input data-testid="process-vtu-options" type="file" accept=".json" onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void file(f,text=>setOptions(JSON.parse(text)),'options');}}/></label><button data-testid="process-vtu-import" disabled={!vtu||!options} onClick={()=>{try{onDocument({volume:parseVtu(vtu,options!),criteria:{...defaults}});setError('');}catch(error){setError(String(error));}}}>명시한 단위·재료로 반입</button></div></details>
    {error&&<div className="process-error" role="alert" data-testid="process-error">{error}</div>}{busy&&<div className="process-progress">전체 체적의 mesh 중첩·연결·막 두께·공극 검사 중 <button onClick={()=>{worker.current?.terminate();setBusy(false);setReport(null);setError('검사를 취소했습니다. 완료 결과가 없습니다.');}}>취소</button></div>}
    {!volume?<div className="process-empty">공정 해석 결과 또는 실측 mesh를 열어주세요. GDS 레이어 색과 표시 높이만으로 공정 피복률을 만들지 않습니다.</div>:<><div className="process-source"><strong>{volume.name} · {volume.stage}</strong><span data-testid="process-provenance">{volume.provenance.kind==='demo'?'교육용 · 실제 공정 해석/실측 아님':doc?.process_run?'속도 기반 형상 계산 · 3D 미보정':`${volume.provenance.kind} · 입력 출처`}</span><span data-testid="process-freshness">{fresh==='independent'?'독립 체적 데이터 · GDS 대응 미검증':fresh?'입력 revision과 동일 · 물리 대응 미검증':'STALE · 연결된 설계 revision이 변경됨'}</span><p>{volume.provenance.label} · 범위 {volume.scope.kind==='roi'?'부분 ROI':'입력에서 선언한 device domain'} · {volume.points_um.length.toLocaleString()} points / {volume.cells.length.toLocaleString()} cells</p></div>
      <div className="process-body"><aside className="process-controls"><h4>재료와 검토 기준</h4><p>기준은 사용자 검토값입니다. Foundry rule / 물성 모델을 대신하지 않습니다.</p>{volume.materials.map(m=><div className="process-material" key={m.id}><label><input type="checkbox" data-testid={`process-material-${m.id}`} checked={visible.includes(m.id)} onChange={e=>setVisible(ids=>e.target.checked?[...ids,m.id]:ids.filter(id=>id!==m.id))}/><i style={{background:m.color}}/>{m.name}</label><small>{m.family||m.role} · Z {materialZ.has(m.id)?materialZ.get(m.id)![0].toPrecision(4):'cell 없음'}~{materialZ.has(m.id)?materialZ.get(m.id)![1].toPrecision(4):'cell 없음'} µm</small>{m.role==='film'&&<><small>기준막 {nm(m.nominal_thickness_um??null)}</small><label>최소 두께 nm<input aria-label={`${m.name} 최소 두께 nm`} type="number" min="0" value={limits(m.id).min_thickness_um*1000} onChange={e=>updateLimits(m.id,'min_thickness_um',Number(e.target.value)/1000)}/></label><label>최소 피복률 %<input aria-label={`${m.name} 최소 피복률 %`} type="number" min="0" max="100" value={limits(m.id).min_coverage_ratio*100} onChange={e=>updateLimits(m.id,'min_coverage_ratio',Number(e.target.value)/100)}/></label></>}</div>)}
      <label className="process-check"><input data-testid="process-heat" type="checkbox" checked={heat} onChange={e=>setHeat(e.target.checked)}/>검토 위험 색상 · 빨강 위험 / 황색 미평가</label><label>XYZ 단면<select data-testid="process-section-axis" value={axis} onChange={e=>{const a=e.target.value as typeof axis;setAxis(a);setPosition(volume.scope.domain_um[0][a==='x'?0:a==='y'?1:2]);}}><option value="none">전체 3D</option><option value="x">X 단면</option><option value="y">Y 단면</option><option value="z">Z 단면</option></select></label>{axis!=='none'&&<><input aria-label="단면 위치 슬라이더" type="range" min={lo} max={hi} step={(hi-lo)/500} value={position} onChange={e=>setPosition(Number(e.target.value))}/><label>단면 위치 µm<input data-testid="process-section-position" type="number" min={lo} max={hi} step={(hi-lo)/500} value={Number(position.toPrecision(12))} onChange={e=>setPosition(Math.max(lo,Math.min(hi,Number(e.target.value))))}/></label></>}
      {context&&<div className="process-association"><label className="process-check"><input type="checkbox" checked={bind} onChange={e=>setBind(e.target.checked)}/>현재 설계에 수동 표시 연결</label><button disabled={!bind} data-testid="process-bind" onClick={()=>{onDocument({...doc!,volume:{...volume,association:{...context}}});setBind(false);}}>r{context.revision} 연결 표시</button><small>수동 연결은 원본 GDS·공정 결과의 일치 검증이 아닙니다.</small></div>}</aside>
      <div className="process-centre">{report?<ProcessMeshViewer volume={volume} report={report} coatingRiskCells={coatingRiskCells} visible={visible} axis={axis} position={position} heat={heat} selected={selected} onSelect={choose}/>:<div className="process-empty">검사된 체적 형상을 준비 중입니다.</div>}{activeCell&&<div className="process-selection" data-testid="process-selected"><strong>{activeCell.id} · {material?.name}</strong><span>{activeCell.region||'미지정 영역'} · 중심 XYZ {centre(volume,selected!).map(v=>v.toPrecision(5)).join(', ')} µm</span>{selectedCoating&&<span data-testid="coating-selection">시작 표면의 축 법선 피복 {nm(selectedCoating.thickness_um)} (voxel 수치) · {coating?.grid_resolution_um} µm 미만 막 미해결</span>}<span>국부 두께 {nm(activeCell.thickness_um)} · 기준막 대비 {activeCell.thickness_um!==null&&material?.nominal_thickness_um?`${(activeCell.thickness_um/material.nominal_thickness_um*100).toFixed(2)}%`:'미평가'}</span></div>}</div>
      <aside className="process-results">{report&&<><h4 data-testid="process-status">{report.status==='findings'?'검토 위험 발견':report.status==='incomplete'?'검토 입력 보완 필요':'제출 체적 검토 완료'}</h4><dl><dt>전량 검사</dt><dd data-testid="process-inspected">{report.inspected_cells} / {volume.cells.length}</dd><dt>Film 평가</dt><dd>{report.assessed_film_cells} / {report.film_cells}</dd><dt>최소 두께</dt><dd data-testid="process-min-thickness">{nm(report.min_thickness_um)}</dd><dt>최소 피복률</dt><dd>{report.min_coverage_ratio===null?'미평가':`${(report.min_coverage_ratio*100).toFixed(2)}%`}</dd><dt>두께/피복 미평가</dt><dd>{report.unknown_thickness_cells} / {report.unknown_coverage_cells}</dd><dt>미제출 체적</dt><dd data-testid="process-unmeshed">{report.unmeshed_volume_um3.toPrecision(5)} µm³</dd><dt>입력 완전성</dt><dd data-testid="process-completeness">{report.complete_input?'선언 domain 충족':'ROI / 누락 / 미평가 있음'}</dd></dl><p className="process-warning">검토는 입력/계산 mesh 해상도와 두께 정의에 한정됩니다. 속도 기반 공정 계산과 보정된 장비·소자 물리 예측, 전기적 신뢰성·signoff를 구분합니다.</p>
      <label>관심 영역<select data-testid="process-region-filter" value={region} onChange={e=>setRegion(e.target.value)}><option value="all">모든 위험 위치</option>{fields.map(v=><option key={v}>{v}</option>)}</select></label><div className="process-issue-list">{uniqueIssues.slice(0,200).map(issue=><button data-testid="process-issue" key={issue.cell} onClick={()=>choose(issue.cell)}><strong>{issue.cell_id}</strong><span>{report.issues.filter(v=>v.cell===issue.cell).map(v=>issueNames[v.kind]).join(' · ')}</span><small>{volume.cells[issue.cell].region||''} · {nm(issue.thickness_um)}</small></button>)}</div>{uniqueIssues.length>200&&<small>목록 첫 200개 · 전체 {uniqueIssues.length}개는 검토 JSON/CSV에 포함</small>}
      {coating&&<div className="process-coating" data-testid="process-coating"><h4>단계별 표면 피복</h4><p>시작 표면 {coating.faces.length}면 전량 · 완성막 voxel 없음 <strong data-testid="coating-unresolved-count">{coating.faces.filter(f=>!f.thickness_um).length}</strong>면</p><small>격자 {coating.grid_resolution_um} µm 미만의 막은 미해결입니다. 수치 0을 실제 두께 0으로 확정하지 않습니다. 황색은 해당 기준 표면의 피복 미해결 위치도 포함합니다.</small><button data-testid="coating-csv" onClick={()=>download('register-process.surface-coverage.csv',depositionCoverageCsv(doc!.process_run!,doc!.selected_stage!),'text/csv;charset=utf-8')}>모든 시작 표면 피복 CSV</button><div className="process-issue-list">{coating.faces.filter(f=>!f.thickness_um).slice(0,200).map((f,i)=><button key={i} data-testid="coating-face" onClick={()=>{const cell=f.surface_voxel*6;setSelected(cell);setSelectedCoating(f);setVisible(ids=>[...new Set([...ids,volume.cells[cell].material_id])]);setAxis((['x','y','z'] as const)[f.axis]);setPosition(f.plane_um);}}><strong>voxel {f.surface_voxel} · {(['X','Y','Z'] as const)[f.axis]} 법선면</strong><small>XYZ {f.location_um.map(v=>v.toPrecision(4)).join(', ')} µm · 완성 막 미해결</small></button>)}</div>{coating.faces.filter(f=>!f.thickness_um).length>200&&<small>목록 첫 200면 · 전체 CSV 제공</small>}</div>}<h4>공극 연결성</h4><div data-testid="process-voids">{report.voids.map((v,i)=><button className={v.closed?'process-closed-void':''} key={i} onClick={()=>choose(v.cells[0])}>{v.closed?'폐쇄 공극':'외부와 연결된 공간'} · {v.volume_um3.toPrecision(5)} µm³ · {v.cells.length} cells</button>)}</div><small>명시된 void 재료의 face 연결을 검사합니다. 제출되지 않은 빈 영역은 공극으로 추정하지 않습니다.</small></>}</aside></div>
      <footer className="process-footer"><button data-testid="process-export-volume" onClick={()=>download('register-process.review.json',JSON.stringify(doc))}>체적·기준 저장</button><button disabled={!report} data-testid="process-export-report" onClick={()=>download('register-process.inspection.json',JSON.stringify({checked_at:new Date().toISOString(),content_sha256:sha,volume_name:volume.name,stage:volume.stage,provenance:volume.provenance,association:volume.association,association_current:fresh,...report},null,2))}>전량 검토 JSON</button><button disabled={!report} data-testid="process-export-csv" onClick={()=>download('register-process.cells.csv',processCsv(volume,report!),'text/csv;charset=utf-8')}>전량 CSV</button><button data-testid="process-export-vtu" onClick={()=>download('register-process.vtu',volumeVtu(volume),'application/xml')}>VTU 저장</button><button data-testid="process-export-vtu-settings" onClick={()=>download('register-process.vtu-setup.json',JSON.stringify(volumeVtuSettings(volume),null,2))}>VTU 설정 저장</button><span>공정 자료·history는 별도 보존 · 뷰어 bundle에도 포함</span></footer><small className="process-hash">입력 체적 SHA-256 {sha||'계산 중 / secure context 필요'}</small>
    </>}
  </section>;
}
