import { useEffect,useMemo,useRef,useState } from 'react';
import { fitPlanarRate,sceneMask,stageVolume,validateMask,validateRecipe,type ProcessRecipe,type ProcessRun,type ProcessStep } from '../../process/src/index';
import type { Scene } from '../../contracts/src/index';
import type { ProcessDocument } from './ProcessPanel';
import example from '../../../examples/process/hole-flow.recipe.json';

const save=(name:string,value:unknown)=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const NumberField=({label,value,onChange,min=0}:{label:string;value:number;onChange:(n:number)=>void;min?:number})=><label>{label}<input type="number" step="any" min={min} aria-label={label} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>;
const validDraftMask=(step:ProcessStep)=>{try{if(step.kind!=='cmp'&&step.mask!==undefined)validateMask(step.mask);return true;}catch{return false;}};
export default function ProcessRecipeEditor({document:doc,onDocument,scene}:{document:ProcessDocument|null;onDocument:(doc:ProcessDocument)=>void;scene?:Scene|null}){
  const [text,setText]=useState(()=>JSON.stringify(example,null,2)),[error,setError]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[layer,setLayer]=useState(''),[maskStep,setMaskStep]=useState(0);
  const [measurements,setMeasurements]=useState('10,200\n20,400'),[fit,setFit]=useState<ReturnType<typeof fitPlanarRate>|null>(null);
  const worker=useRef<Worker|null>(null),sequence=useRef(0);
  const parsed=useMemo(()=>{try{return JSON.parse(text) as ProcessRecipe;}catch{return null;}},[text]);
  const editable=parsed&&Array.isArray(parsed.steps)&&parsed.steps.every(s=>s&&typeof s==='object'&&typeof s.id==='string'&&typeof s.name==='string'&&Number.isFinite(s.time_s)&&(validDraftMask(s))&&(['deposit','etch','cmp'] as string[]).includes(s.kind)&&(s.kind==='deposit'?Number.isFinite(s.rate_um_s):s.kind==='etch'?!!s.rates_um_s&&typeof s.rates_um_s==='object':!!s.preston_m2_N&&typeof s.preston_m2_N==='object'))&&parsed.grid&&Array.isArray(parsed.grid.shape)&&parsed.grid.shape.length===3&&Array.isArray(parsed.grid.origin_um)&&parsed.grid.origin_um.length===3&&Number.isFinite(parsed.grid.spacing_um)&&Array.isArray(parsed.materials)&&parsed.materials.every(m=>m&&typeof m==='object'&&typeof m.name==='string')&&Array.isArray(parsed.initial)&&parsed.initial.every(b=>b&&Array.isArray(b.box_um)&&b.box_um.length===2&&b.box_um.every(p=>Array.isArray(p)&&p.length===3));
  const change=(work:(recipe:ProcessRecipe)=>void)=>{if(!editable)return;const r=structuredClone(parsed);work(r);setText(JSON.stringify(r,null,2));setError('');};
  const setStep=(index:number,fields:Partial<ProcessStep>)=>change(r=>{r.steps[index]={...r.steps[index],...fields} as ProcessStep;});
  useEffect(()=>()=>{sequence.current++;worker.current?.terminate();},[]);
  const cancel=()=>{worker.current?.terminate();worker.current=null;setBusy(false);setProgress('취소됨 · 이전 완료 결과 유지');};
  const run=(compare=false)=>{
    try{const recipe=validateRecipe(JSON.parse(text));worker.current?.terminate();setBusy(true);setError('');setProgress('공정 순서·영역·계산 예산 검증 중');
      const next=new Worker(new URL('./process-run-worker.ts',import.meta.url),{type:'module'});worker.current=next;
      next.onmessage=event=>{if(event.data.kind==='progress'){setProgress(`${event.data.step+1}/${event.data.total} · ${event.data.name}`);return;}setBusy(false);next.terminate();worker.current=null;if(!event.data.ok){setError(event.data.message);return;}
        const run=event.data.run as ProcessRun,index=run.stages.length-1;
        if(scene)for(const step of run.recipe.steps){const source=step.kind!=='cmp'?step.mask?.source:undefined;if(source&&source.project_id===scene.project_id&&source.revision!==scene.revision)run.warnings.push(`STALE mask ${step.name}: 동결된 r${source.revision}로 계산했습니다. 현재 scene r${scene.revision}와 대응하지 않습니다.`);}
        onDocument({volume:stageVolume(run,index),criteria:{min_thickness_um:.03,min_coverage_ratio:.5},process_run:run,selected_stage:index});setProgress('모든 공정 단계 계산 완료');};
      next.onerror=event=>{next.terminate();worker.current=null;setBusy(false);setError(`공정 계산 worker: ${event.message}`);};next.postMessage({recipe,compare});
    }catch(error){setError(error instanceof Error?error.message:String(error));}
  };
  const load=async(file:File)=>{const current=++sequence.current;try{if(file.size>32*1024*1024)throw new Error('Recipe 파일 상한은 32 MiB입니다.');const text=await file.text();const recipe=validateRecipe(JSON.parse(text));if(sequence.current===current){setText(JSON.stringify(recipe,null,2));setError('');}}catch(error){setError(String(error));}};
  const fromVolume=()=>{try{if(!doc)throw new Error('초기 체적이 필요합니다.');const v=doc.volume,spans=v.scope.domain_um[1].map((hi,a)=>hi-v.scope.domain_um[0][a]),h=Math.max(...spans)/12,shape=spans.map(span=>Math.floor(span/h+1e-9));if(shape.some(n=>n<2))throw new Error('격자 축별 최소 2개가 필요합니다. JSON에서 ROI와 격자를 설정하세요.');const film=v.materials.find(m=>m.role==='film');if(!film)throw new Error('추가 증착할 film 재료 정의가 필요합니다.');
    const recipe:ProcessRecipe={schema_version:1,kind:'register-process-recipe',name:`${v.name} · 후속 공정`,grid:{origin_um:[...v.scope.domain_um[0]],spacing_um:h,shape:shape as [number,number,number]},materials:structuredClone(v.materials),initial:[],initial_volume:structuredClone(v),steps:[{id:'next-deposit',name:'후속 conformal 증착',kind:'deposit',method:'conformal',material_id:film.id,rate_um_s:.01,time_s:10,angular_spread_deg:0,reemit_fraction:0}],calibration:{kind:'uncalibrated',label:'사용자 초기 mesh의 voxel 중심 resampling / 후속 속도 입력 미보정'}};validateRecipe(recipe);setText(JSON.stringify(recipe,null,2));setError('');
  }catch(error){setError(String(error));}};
  const add=(kind:ProcessStep['kind'])=>change(r=>{if(r.steps.length>=16)throw new Error('최대 16단계입니다.');const id=crypto.randomUUID(),film=r.materials.find(m=>m.role==='film')?.id??-1;
    if(kind==='deposit')r.steps.push({id,name:'추가 증착',kind,method:'conformal',material_id:film,rate_um_s:.01,time_s:10,angular_spread_deg:0,reemit_fraction:0});
    if(kind==='etch')r.steps.push({id,name:'추가 식각',kind,method:'isotropic',rates_um_s:Object.fromEntries(r.materials.filter(m=>m.role!=='void').map(m=>[m.id,m.role==='film'?.01:0])),time_s:10,angular_spread_deg:0});
    if(kind==='cmp')r.steps.push({id,name:'추가 CMP',kind,method:'preston',target_z_um:r.grid.origin_um[2],time_s:30,pressure_Pa:10000,velocity_m_s:.5,preston_m2_N:Object.fromEntries(r.materials.filter(m=>m.role!=='void').map(m=>[m.id,m.role==='film'?1e-12:0])),pad_radius_um:r.grid.spacing_um*2,compliance_um:r.grid.spacing_um*2,dishing_factor:0,erosion_factor:0});
  });
  const history=doc?.process_run;
  return <div className="process-flow">
    <details data-testid="process-recipe-details"><summary>공정 시퀀스 계산 · 증착 / 식각 / CMP</summary>
      <p className="process-model-note">속도 입력 기반 3D voxel 형상 계산입니다. 방향성 ray의 가림, 상단 gas 접근성, 재료별 식각 속도와 Preston CMP를 계산합니다. 장비 반응·플라즈마 TCAD / 보정된 foundry 예측을 대신하지 않습니다.</p>
      <div className="process-flow-actions"><button data-testid="recipe-example" disabled={busy} onClick={()=>{setText(JSON.stringify(example,null,2));setError('');}}>홀·단차 공정 예제 불러오기</button><label className="process-upload">Recipe JSON<input type="file" accept=".json" data-testid="recipe-json-input" disabled={busy} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void load(f);}}/></label><button data-testid="recipe-from-volume" disabled={busy||!doc} onClick={fromVolume}>현재 체적에서 후속 공정 시작</button>{history&&<button onClick={()=>setText(JSON.stringify(history.recipe,null,2))}>저장된 계산 recipe 편집</button>}<button data-testid="recipe-save" disabled={busy||!editable} onClick={()=>{try{save('register-process.recipe.json',validateRecipe(JSON.parse(text)));}catch(error){setError(String(error));}}}>Recipe 저장</button></div>
      <fieldset className="process-flow-editor" disabled={busy}>
      {editable&&<>
        <div className="process-grid-fields"><label>계산 이름<input value={parsed.name||''} onChange={e=>change(r=>{r.name=e.target.value;})}/></label><NumberField label="격자 간격 µm" min={1e-6} value={parsed.grid.spacing_um} onChange={n=>change(r=>{r.grid.spacing_um=n;})}/>{(['X','Y','Z'] as const).map((axis,a)=><NumberField key={axis} label={`${axis} voxel 수`} min={2} value={parsed.grid.shape[a]} onChange={n=>change(r=>{r.grid.shape[a]=n;})}/>)}</div>
        <p>전체 {(parsed.grid.shape||[]).reduce((n,v)=>n*v,1).toLocaleString()} voxels · 최대 5,000. 모든 좌표 µm / 속도 µm/s / 시간 s입니다. 초기 구조 좌표는 격자 변경 시 자동 변형하지 않습니다.</p>
        <details><summary>초기 3D box / 재료 / 원점</summary><div className="process-box-editor">{(['X','Y','Z'] as const).map((axis,a)=><NumberField key={axis} label={`원점 ${axis} µm`} min={-1e6} value={parsed.grid.origin_um[a]} onChange={n=>change(r=>{r.grid.origin_um[a]=n;})}/>)}{parsed.initial_volume&&<p>반입 체적 {parsed.initial_volume.name} · 원본 tetra/두께/출처를 recipe에 보존합니다. Grid 중심에서 resampling하며 제출되지 않은 영역은 거부합니다.</p>}
        {parsed.materials.map((m,i)=><div className="process-box-row" key={m.id}><strong>재료 {m.id}</strong><label>이름<input value={m.name} onChange={e=>change(r=>{r.materials[i].name=e.target.value;})}/></label><label>역할<select value={m.role} onChange={e=>change(r=>{r.materials[i].role=e.target.value as 'film'|'bulk'|'void';})}><option value="film">film</option><option value="bulk">bulk</option><option value="void">void</option></select></label>{m.role==='film'&&<NumberField label={`${m.name} 기준막 µm`} value={m.nominal_thickness_um||0} onChange={n=>change(r=>{r.materials[i].nominal_thickness_um=n;})}/>}</div>)}
        {parsed.initial.map((b,i)=><div className="process-box-row" key={i}><label>Box 재료<select value={b.material_id} onChange={e=>change(r=>{r.initial[i].material_id=Number(e.target.value);})}>{parsed.materials.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>{[0,1].flatMap(side=>(['X','Y','Z'] as const).map((axis,a)=><NumberField key={`${side}${axis}`} label={`Box ${i+1} ${side?'상한':'하한'} ${axis}`} min={-1e6} value={b.box_um[side][a]} onChange={n=>change(r=>{r.initial[i].box_um[side][a]=n;})}/>))}<button onClick={()=>change(r=>{r.initial.splice(i,1);})}>Box 삭제</button></div>)}<button onClick={()=>change(r=>{r.initial.push({material_id:r.materials.find(m=>m.role!=='void')?.id??0,box_um:[[...r.grid.origin_um],r.grid.origin_um.map(v=>v+r.grid.spacing_um) as [number,number,number]]});})}>초기 box 추가</button></div></details>
        <div className="process-step-list">{parsed.steps.map((step,i)=><article className="process-step" key={step.id} data-testid={`recipe-step-${i}`}><header><b>{i+1}. {step.kind==='deposit'?'증착':step.kind==='etch'?'식각':'CMP'}</b><input aria-label={`단계 ${i+1} 이름`} value={step.name} onChange={e=>setStep(i,{name:e.target.value})}/><button disabled={!i} onClick={()=>change(r=>{[r.steps[i-1],r.steps[i]]=[r.steps[i],r.steps[i-1]];})}>↑</button><button disabled={i===parsed.steps.length-1} onClick={()=>change(r=>{[r.steps[i+1],r.steps[i]]=[r.steps[i],r.steps[i+1]];})}>↓</button><button onClick={()=>change(r=>{r.steps.splice(i,1);})}>삭제</button></header>
          <div className="process-step-fields"><label>모델<select aria-label={`단계 ${i+1} 모델`} value={step.method} onChange={e=>{const method=e.target.value;if(step.kind==='deposit')setStep(i,{method:method as 'conformal'|'directional',...(method==='conformal'?{angular_spread_deg:0,reemit_fraction:0}:{})});else if(step.kind==='etch')setStep(i,{method:method as 'isotropic'|'directional',...(method==='isotropic'?{angular_spread_deg:0}:{})});else setStep(i,{method:method as 'plane'|'preston'});}}>{(step.kind==='deposit'?['conformal','directional']:step.kind==='etch'?['isotropic','directional']:['preston','plane']).map(m=><option key={m}>{m}</option>)}</select></label>
            <NumberField label={`단계 ${i+1} 시간 s`} value={step.time_s} onChange={n=>setStep(i,{time_s:n})}/>
            {step.kind==='deposit'&&<><label>증착 재료<select value={step.material_id} onChange={e=>setStep(i,{material_id:Number(e.target.value)})}>{parsed.materials.filter(m=>m.role==='film').map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><NumberField label={`단계 ${i+1} 속도 µm/s`} value={step.rate_um_s} onChange={n=>setStep(i,{rate_um_s:n})}/>{step.method==='directional'&&<NumberField label={`단계 ${i+1} 재방출 비율`} value={step.reemit_fraction} onChange={n=>setStep(i,{reemit_fraction:n})}/>}</>}
            {step.kind!=='cmp'&&step.method==='directional'&&<NumberField label={`단계 ${i+1} 입사각 °`} value={step.angular_spread_deg} onChange={n=>setStep(i,{angular_spread_deg:n})}/>}
            {step.kind==='etch'&&parsed.materials.filter(m=>m.role!=='void').map(m=><NumberField key={m.id} label={`단계 ${i+1} ${m.name} 식각 µm/s`} value={step.rates_um_s[m.id]||0} onChange={n=>setStep(i,{rates_um_s:{...step.rates_um_s,[m.id]:n}})}/>)}
            {step.kind==='cmp'&&<><NumberField label={`단계 ${i+1} stop Z µm`} min={-1e6} value={step.target_z_um} onChange={n=>setStep(i,{target_z_um:n})}/>{step.method==='preston'&&<><NumberField label={`단계 ${i+1} 압력 Pa`} value={step.pressure_Pa} onChange={n=>setStep(i,{pressure_Pa:n})}/><NumberField label={`단계 ${i+1} pad 속도 m/s`} value={step.velocity_m_s} onChange={n=>setStep(i,{velocity_m_s:n})}/><NumberField label={`단계 ${i+1} pad 반경 µm`} value={step.pad_radius_um} onChange={n=>setStep(i,{pad_radius_um:n})}/><NumberField label={`단계 ${i+1} pad compliance µm`} value={step.compliance_um} onChange={n=>setStep(i,{compliance_um:n})}/><NumberField label={`단계 ${i+1} dishing 계수`} value={step.dishing_factor} onChange={n=>setStep(i,{dishing_factor:n})}/><NumberField label={`단계 ${i+1} erosion 계수`} value={step.erosion_factor} onChange={n=>setStep(i,{erosion_factor:n})}/>{parsed.materials.filter(m=>m.role!=='void').map(m=><NumberField key={m.id} label={`단계 ${i+1} ${m.name} Preston m²/N`} value={step.preston_m2_N[m.id]||0} onChange={n=>setStep(i,{preston_m2_N:{...step.preston_m2_N,[m.id]:n}})}/>)}</>}</>}
          </div>{step.kind!=='cmp'&&step.mask&&<p>이상적인 평면 mask · {step.mask.mode} · {step.mask.polygons_um.length} polygons {step.mask.source&&`· 로드 scene r${step.mask.source.revision}/${step.mask.source.layer_id}`} <button onClick={()=>setStep(i,{mask:undefined})}>Mask 제거</button></p>}</article>)}</div>
        <div className="process-flow-actions"><button disabled={parsed.steps.length>=16} onClick={()=>add('deposit')}>증착 추가</button><button disabled={parsed.steps.length>=16} onClick={()=>add('etch')}>식각 추가</button><button disabled={parsed.steps.length>=16} onClick={()=>add('cmp')}>CMP 추가</button></div>
        {scene&&<div className="process-mask-import"><b>로드한 GDS / 설계 layer를 XY mask로 사용</b><select data-testid="recipe-mask-layer" aria-label="Mask layer" value={layer} onChange={e=>setLayer(e.target.value)}><option value="">Layer 선택</option>{scene.layers.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><select aria-label="Mask 적용 단계" value={maskStep} onChange={e=>setMaskStep(Number(e.target.value))}>{parsed.steps.map((s,i)=>s.kind!=='cmp'&&<option key={s.id} value={i}>{i+1}. {s.name}</option>)}</select><button data-testid="recipe-mask-import" disabled={!layer||parsed.steps[maskStep]?.kind==='cmp'} onClick={()=>{try{const mask=sceneMask(scene,layer);setStep(maskStep,{mask});}catch(error){setError(String(error));}}}>해당 단계에 mask 연결</button><small>현재 로드된 {scene.shapes.length} shapes 범위만 사용합니다. GDS는 XY mask이며 초기 공정 높이·물성·시간을 제공하지 않습니다. Hole ring도 보존합니다.</small></div>}
      </>}
      <details className="process-rate-fit"><summary>실측 평면 두께로 속도 fit</summary><p>한 행에 시간 s, 두께 nm. 원점을 지나는 thickness=rate×time 최소제곱입니다. 3D 공정 보정으로 표시하지 않습니다.</p><textarea aria-label="평면 속도 측정값" value={measurements} onChange={e=>setMeasurements(e.target.value)}/><button data-testid="recipe-fit" onClick={()=>{try{setFit(fitPlanarRate(measurements.trim().split(/\r?\n/).map(line=>{const values=line.split(',').map(Number);if(values.length!==2)throw new Error('시간 s,두께 nm 형식입니다.');return {time_s:values[0],thickness_um:values[1]/1000};})));setError('');}catch(error){setError(String(error));}}}>속도 계산</button>{fit&&<p data-testid="recipe-fit-result">{fit.rate_um_s.toPrecision(6)} µm/s · RMSE {(fit.rmse_um*1000).toPrecision(4)} nm · {fit.samples}개 <button disabled={!editable||!parsed.steps.some(s=>s.kind==='deposit')} onClick={()=>change(r=>{const s=r.steps.find(s=>s.kind==='deposit')! as Extract<ProcessStep,{kind:'deposit'}>;s.rate_um_s=fit.rate_um_s;r.calibration={kind:'user-reference',label:`사용자 입력 평면 ${fit.samples}개 least-squares fit · 3D 미보정`};})}>첫 증착에 적용</button></p>}</details>
      <details className="process-recipe-json"><summary>전체 Recipe JSON · mask / 출처 / 조건 편집</summary><textarea data-testid="recipe-json-editor" aria-label="공정 Recipe JSON" spellCheck={false} value={text} onChange={e=>setText(e.target.value)}/></details>
      </fieldset>
      <div className="process-flow-actions"><button className="primary" data-testid="recipe-run" disabled={busy} onClick={()=>run()}>공정 순서 계산</button><button data-testid="recipe-convergence" disabled={busy} onClick={()=>run(true)}>해상도 비교 h · 2h</button>{busy&&<button data-testid="recipe-cancel" onClick={cancel}>계산 취소</button>}<span role="status" data-testid="recipe-progress">{progress}</span></div>
      {error&&<div className="process-error" role="alert" data-testid="recipe-error">{error}</div>}
    </details>
    {history&&<div className="process-timeline" data-testid="process-timeline"><header><strong>공정 단계 · {history.engine}</strong><span>속도 기반 형상 예측 / 3D 미보정</span><button data-testid="recipe-result-export" onClick={()=>save('register-process.run.json',history)}>전 단계 결과 저장</button></header><div className="process-stage-buttons">{history.stages.map((s,i)=><button key={s.step_id} data-testid={`process-stage-${i}`} aria-pressed={doc.selected_stage===i} onClick={()=>onDocument({...doc,volume:stageVolume(history,i),selected_stage:i})}>{i}. {s.name}<small>{s.time_s.toPrecision(4)} s · 폐쇄 공극 {s.closed_voids}</small></button>)}</div>
      <table><thead><tr><th>선택 단계</th><th>증가 / 제거 µm³</th><th>폐쇄 공극 µm³</th><th>표면 Z 범위 µm</th><th>피복 미해결 / 평가면</th></tr></thead><tbody><tr><td>{history.stages[doc.selected_stage||0].name}</td><td>{history.stages[doc.selected_stage||0].added_volume_um3.toPrecision(5)} / {history.stages[doc.selected_stage||0].removed_volume_um3.toPrecision(5)}</td><td data-testid="recipe-stage-void-volume">{history.stages[doc.selected_stage||0].closed_void_volume_um3.toPrecision(5)}</td><td>{history.stages[doc.selected_stage||0].surface_range_um.map(n=>n.toPrecision(5)).join(' ~ ')}</td><td>{history.stages[doc.selected_stage||0].deposition_coverage?`${history.stages[doc.selected_stage||0].deposition_coverage!.no_resolved_coating_faces} / ${history.stages[doc.selected_stage||0].deposition_coverage!.assessed_faces}`:'증착 단계 아님'}</td></tr></tbody></table>
      {history.convergence&&<p data-testid="recipe-resolution-result">해상도 {history.convergence.coarse_spacing_um} → {history.convergence.fine_spacing_um} µm · 재료 차이 {(history.convergence.different_fraction*100).toFixed(3)}% / {history.convergence.different_volume_um3.toPrecision(5)} µm³ · 폐쇄 공극 {history.convergence.closed_void_counts.join(' → ')}. 차이 측정이며 수렴 PASS 판정이 아닙니다.</p>}
      <details><summary>모델·해상도 경계 / 경고 / 원본 recipe hash</summary><ul>{history.warnings.map((s,i)=><li key={i}>{s}</li>)}</ul><p className="process-hash">Recipe SHA-256 {history.recipe_sha256} · 저장된 history는 재실행으로 재현하세요.</p></details>
    </div>}
  </div>;
}
