import { useEffect, useMemo, useRef, useState } from 'react';
import { rpc, type Device, type Project, type SchematicCommand } from '@mos/contracts';
import {deleteDesignKey} from './shortcuts';

type Point = [number, number];
type Tool = 'select' | 'wire' | 'junction' | 'pan';
type Drag = { kind: 'device' | 'wire' | 'junction' | 'pan'; id: string; start: Point; delta: Point; original: Point; screenStart?: Point };
interface Validation { valid: boolean; issues?: { code: string; message: string; device_id?: string; pin?: string }[]; connectivity?: { nets: { name: string; pins: { device_id: string; pin: string }[]; wire_ids: string[]; junction_ids: string[] }[]; conflicts?: unknown[]; unconnected_pins?: unknown[] }; }
interface Props { onHierarchy:()=>void; onCopyHierarchy:()=>void; project: Project; cellName: string | null; selection: string | null; readOnly?: boolean; onSelect: (id: string | null) => void; onCellChange: (name: string | null) => void; onCommand: (command: SchematicCommand) => Promise<void>; onValidate: () => void; onExport: () => void; onTestbench: () => void; onXschem: () => void; xschemAvailable: boolean; }
export const pinOffsets = (device: Device): Record<string, Point> => {
  if (device.kind === 'nmos' || device.kind === 'pmos') return { D: [30, device.kind === 'pmos' ? 42 : -42], G: [-46, 0], S: [30, device.kind === 'pmos' ? -42 : 42], B: [49, 0] };
  if (device.kind === 'ground') return { G: [0, -30] };
  if (device.kind === 'port') return { P: [-30, 0] };
  if (device.kind === 'block') { const pins = Object.keys(device.pins); return Object.fromEntries(pins.map((name, index) => [name, [-55, -(pins.length - 1) * 12 + index * 24]])); }
  return Object.fromEntries(Object.keys(device.pins).map((name, index) => [name, [0, index ? 44 : -44]]));
};
function Symbol({ device }: { device: Device }) {
  const common = { fill: 'none', stroke: 'currentColor', strokeWidth: 2.2, strokeLinecap: 'round' as const, strokeLinejoin: 'round' as const };
  if (device.kind === 'nmos' || device.kind === 'pmos') return <g {...common}><path d="M-46 0 H-15 M-15 -26 V26 M-5 -26 V26 M-5 -22 H30 V-42 M-5 22 H30 V42 M-5 0 H49"/><path d={device.kind === 'nmos' ? 'M15 0 L7 -5 M15 0 L7 5' : 'M7 0 L15 -5 M7 0 L15 5'}/>{device.kind === 'pmos' && <circle cx={-22} cy={0} r={5}/>}</g>;
  if (device.kind === 'resistor') return <path {...common} d="M0 -44 V-26 L-8 -20 L8 -12 L-8 -4 L8 4 L-8 12 L8 20 L0 26 V44"/>;
  if (device.kind === 'capacitor') return <g {...common}><path d="M0 -44 V-8 M-18 -8 H18 M-18 8 H18 M0 8 V44"/></g>;
  if (device.kind === 'ground') return <g {...common}><path d="M0 -30 V0 M-20 0 H20 M-13 7 H13 M-6 14 H6"/></g>;
  if (device.kind === 'port') return <g {...common}><path d="M-30 0 H-12 L0 -12 H30 V12 H0 L-12 0"/></g>;
  if (device.kind === 'block') { const height = Math.max(60, Object.keys(device.pins).length * 24); return <g {...common}><rect x={-35} y={-height / 2} width={88} height={height} rx={4}/>{Object.entries(pinOffsets(device)).map(([pin, [x, y]]) => <g key={pin}><path d={`M${x} ${y}H-35`}/><text x={-27} y={y + 3} stroke="none" fill="currentColor" fontSize={9}>{pin}</text></g>)}<text x={10} y={5} fill="currentColor" stroke="none" fontSize={11} textAnchor="middle">↳</text></g>; }
  return <g {...common}><path d="M0 -44 V-23 M0 23 V44"/><circle r={23}/>{device.kind === 'voltage' ? <path d="M-7 -9 H7 M0 -16 V-2 M-7 10 H7"/> : <path d="M0 13 V-13 M-6 -6 L0 -13 L6 -6"/>}</g>;
}
const bridge = (from: Point, to: Point): Point[] => from[0] === to[0] || from[1] === to[1] ? [to] : [[to[0], from[1]], to];
const same = (a: Point, b: Point) => a[0] === b[0] && a[1] === b[1];
export default function SchematicEditor({ onHierarchy, onCopyHierarchy, project, cellName, selection, readOnly = false, onSelect, onCellChange, onCommand, onValidate, onExport, onTestbench, onXschem, xschemAvailable }: Props) {
  const svg = useRef<SVGSVGElement>(null);
  const [zoom, setZoom] = useState(1), [pan, setPan] = useState<Point>([0, 0]), [tool, setTool] = useState<Tool>('select');
  const [drag, setDrag] = useState<Drag | null>(null), [draft, setDraft] = useState<Point[]>([]), [pointer, setPointer] = useState<Point | null>(null);
  const [netName, setNetName] = useState(''), [selectedWire, setSelectedWire] = useState<string | null>(null), [selectedJunction, setSelectedJunction] = useState<string | null>(null);
  const [validation, setValidation] = useState<Validation | null>(null), [validationError, setValidationError] = useState<string | null>(null);
  const [showHierarchy, setShowHierarchy] = useState(false), [newCellName, setNewCellName] = useState('analog_block'), [newCellPorts, setNewCellPorts] = useState('IN, OUT, VDD, VSS');
  const document = cellName ? project.schematic.cells?.[cellName] || project.schematic : project.schematic;
  const devices = document.devices, wires = document.wires || [], junctions = document.junctions || [], mode = document.connectivity_mode || 'explicit';
  const position = (device: Device): Point => drag?.kind === 'device' && drag.id === device.id ? [device.x + drag.delta[0], device.y + drag.delta[1]] : [device.x, device.y];
  const wirePoints = (wire: typeof wires[number]): Point[] => drag?.kind === 'wire' && drag.id === wire.id ? wire.points.map(([x, y]) => [x + drag.delta[0], y + drag.delta[1]]) : wire.points;
  const viewport = useMemo(() => {
    const points = [...devices.map(device => [device.x, device.y] as Point), ...wires.flatMap(wire => wire.points), ...junctions.map(junction => [junction.x, junction.y] as Point)];
    const xs = points.map(point => point[0]), ys = points.map(point => point[1]), xmin = xs.length ? Math.min(...xs) : 200, ymin = ys.length ? Math.min(...ys) : 100, xmax = xs.length ? Math.max(...xs) : 400, ymax = ys.length ? Math.max(...ys) : 300;
    const width = Math.max(500, xmax - xmin + 360), height = Math.max(360, ymax - ymin + 190);
    return { left: (xmin + xmax) / 2 - width / 2 + 30, top: (ymin + ymax) / 2 - height / 2, width, height };
  }, [devices, wires, junctions]);
  const view = `${viewport.left + viewport.width * (1 - 1 / zoom) / 2 + pan[0]} ${viewport.top + viewport.height * (1 - 1 / zoom) / 2 + pan[1]} ${viewport.width / zoom} ${viewport.height / zoom}`;
  useEffect(() => { setPan([0, 0]); setZoom(1); setDraft([]); setSelectedWire(null); setSelectedJunction(null); }, [cellName, project.id]);
  useEffect(() => { let canceled = false; void rpc<Validation>('schematic.validate', { project_id: project.id, ...(cellName ? { cell_name: cellName } : {}) }).then(result => { if (!canceled) { setValidation(result); setValidationError(null); } }).catch(cause => { if (!canceled) { setValidation(null); setValidationError(cause instanceof Error ? cause.message : String(cause)); } }); return () => { canceled = true; }; }, [project.id, project.revision, cellName]);
  useEffect(() => { const element = svg.current; if (!element) return; const wheel = (event: WheelEvent) => { event.preventDefault(); setZoom(current => Math.max(.25, Math.min(5, current * Math.exp(-event.deltaY * .001)))); }; element.addEventListener('wheel', wheel, { passive: false }); return () => element.removeEventListener('wheel', wheel); }, []);
  const coords = (event: React.PointerEvent<SVGElement>): Point => { const point = svg.current!.createSVGPoint(); point.x = event.clientX; point.y = event.clientY; const next = point.matrixTransform(svg.current!.getScreenCTM()!.inverse()); return [next.x, next.y]; };
  const pinPoints = devices.flatMap(device => Object.values(pinOffsets(device)).map(([x, y]) => [device.x + x, device.y + y] as Point));
  const snap = (point: Point): Point => {
    const candidates: Point[] = [...pinPoints, ...wires.flatMap(wire => wire.points), ...junctions.map(junction => [junction.x, junction.y] as Point)];
    const segments = wires.flatMap(wire => wire.points.slice(1).map((end, index) => [wire.points[index], end] as [Point, Point]));
    for (const [a, b] of segments) { if (a[0] === b[0]) candidates.push([a[0], Math.max(Math.min(a[1], b[1]), Math.min(Math.max(a[1], b[1]), Math.round(point[1] / 10) * 10))]); else if (a[1] === b[1]) candidates.push([Math.max(Math.min(a[0], b[0]), Math.min(Math.max(a[0], b[0]), Math.round(point[0] / 10) * 10)), a[1]]); }
    for (const [a, b] of segments) for (const [c, d] of segments) if (a[0] === b[0] && c[1] === d[1] && a[0] >= Math.min(c[0], d[0]) && a[0] <= Math.max(c[0], d[0]) && c[1] >= Math.min(a[1], b[1]) && c[1] <= Math.max(a[1], b[1])) candidates.push([a[0], c[1]]);
    const nearest = candidates.map(candidate => ({ candidate, distance: Math.hypot(point[0] - candidate[0], point[1] - candidate[1]) })).sort((a, b) => a.distance - b.distance)[0];
    return nearest?.distance < 10 / zoom ? nearest.candidate : [Math.round(point[0] / 10) * 10, Math.round(point[1] / 10) * 10];
  };
  const send = (command: SchematicCommand) => { void onCommand(command).catch(() => {}); };
  const commitWire = (points = draft) => { const clean = points.filter((point, index) => !index || !same(point, points[index - 1])); if (clean.length < 2) return; send({ type: 'add_wire', wire: { id: `wire-${crypto.randomUUID()}`, points: clean, ...(netName.trim() ? { net: netName.trim() } : {}) } }); setDraft([]); setPointer(null); };
  const pointClick = (point: Point, pin = false) => { if (readOnly) return; if (tool === 'junction') { send({ type: 'add_junction', junction: { id: `junction-${crypto.randomUUID()}`, x: point[0], y: point[1], ...(netName.trim() ? { net: netName.trim() } : {}) } }); return; } if (tool !== 'wire') return; if (!draft.length) setDraft([point]); else { const next = [...draft, ...bridge(draft[draft.length - 1], point)]; if (pin) commitWire(next); else setDraft(next); } };
  const inferredNets = useMemo(() => { const map = new Map<string, { device: Device; pin: string; offset: Point }[]>(); devices.forEach(device => Object.entries(device.pins).forEach(([pin, net]) => { if (net) map.set(net, [...(map.get(net) || []), { device, pin, offset: pinOffsets(device)[pin] || [0, 0] }]); })); return map; }, [devices]);
  const selectedNet = selectedWire ? validation?.connectivity?.nets.find(net => net.wire_ids.includes(selectedWire)) : selection ? validation?.connectivity?.nets.find(net => net.pins.some(pin => pin.device_id === selection)) : undefined;
  const deleteSelected = () => { if (readOnly) return; if (selectedWire) { send({ type: 'delete_wire', id: selectedWire }); setSelectedWire(null); } else if (selectedJunction) { send({ type: 'delete_junction', id: selectedJunction }); setSelectedJunction(null); } else if (selection) send({ type: 'delete_device', id: selection }); };
  const copySelected = () => { if (readOnly) return; if (selectedWire) send({ type: 'copy_wire', id: selectedWire, dx: 20, dy: 20 }); else if (selection) send({ type: 'copy_device', id: selection, dx: 20, dy: 20 }); };
  return <div className={`schematic-view schematic-tool-${tool}`}>
    <div className="schematic-editor-toolbar"><div className="schematic-breadcrumb"><button onClick={() => onCellChange(null)}>{project.cell}</button>{cellName && <><span>›</span><strong>{cellName}</strong></>}<button title="Cell hierarchy" onClick={() => setShowHierarchy(value => !value)}>▾ Hierarchy</button></div><label>연결<select data-testid="connectivity-mode" value={mode} disabled={readOnly} onChange={event => send({ type: 'set_connectivity_mode', mode: event.target.value as 'explicit' | 'geometric' })}><option value="explicit">명시적 pin/net</option><option value="geometric">실제 pin/wire 기하</option></select></label><button onClick={onTestbench}>Testbench</button><button onClick={onValidate}>Check graph</button><button onClick={onExport}>SPICE</button><button disabled={!xschemAvailable || !!cellName || Object.keys(project.schematic.cells || {}).length > 0} title={!xschemAvailable ? 'Xschem이 설치되지 않았습니다.' : '검증된 flat native schematic의 실제 Xschem netlist'} onClick={onXschem}>Xschem</button></div>
    <div className="schematic-drawing-toolbar"><div className="segmented-control">{(['select', 'wire', 'junction', 'pan'] as Tool[]).map(item => <button data-testid={`schematic-tool-${item}`} key={item} disabled={readOnly && (item === 'wire' || item === 'junction')} className={tool === item ? 'active' : ''} onClick={() => { setTool(item); setDraft([]); }}>{item === 'select' ? '선택 / 이동' : item === 'wire' ? '배선 / Wire' : item === 'junction' ? '접점 / Junction' : 'Pan'}</button>)}</div>{(tool === 'wire' || tool === 'junction') && <input aria-label="Wire net label" value={netName} onChange={event => setNetName(event.target.value)} placeholder="Net label (선택)"/>}{tool === 'wire' && <button disabled={draft.length < 2} onClick={() => commitWire()}>배선 완료 ↵</button>}<span className="schematic-toolbar-spacer"/><button className="button small" data-testid="hierarchy-copy" onClick={onCopyHierarchy}>계층 복사</button><button className="button small" data-testid="open-hierarchy-transfer" disabled={readOnly} onClick={onHierarchy}>계층 가져오기·미리보기</button><button disabled={readOnly || (!selection && !selectedWire)} onClick={copySelected}>복제</button><button disabled={readOnly || (!selection && !selectedWire && !selectedJunction)} onClick={deleteSelected}>삭제</button><button onClick={() => { setZoom(1); setPan([0, 0]); }}>Fit</button><span>{Math.round(zoom * 100)}%</span></div>
    {showHierarchy && <div className="schematic-hierarchy-popover"><strong>SCHEMATIC CELLS</strong><button onClick={() => { onCellChange(null); setShowHierarchy(false); }}>{project.cell} <span>TOP</span></button>{Object.entries(project.schematic.cells || {}).map(([name, cell]) => <div key={name}><button onClick={() => { onCellChange(name); setShowHierarchy(false); }}>{name}<span>{(cell.ports || []).join(', ')}</span></button><button disabled={readOnly || name === cellName} title="현재 cell에 block 배치" onClick={() => { send({ type: 'add_device', device: { id: `block-${crypto.randomUUID()}`, name: `X${name}_${devices.length + 1}`, kind: 'block', cell_name: name, pins: Object.fromEntries((cell.ports || []).map(port => [port, ''])), parameters: {}, x: 320, y: 260 } }); setShowHierarchy(false); }}>＋</button></div>)}<form onSubmit={event => { event.preventDefault(); send({ type: 'add_cell', name: newCellName.trim(), ports: newCellPorts.split(/[\s,]+/).filter(Boolean) }); }}><input aria-label="새 cell 이름" value={newCellName} onChange={event => setNewCellName(event.target.value)}/><input aria-label="Cell ports" value={newCellPorts} onChange={event => setNewCellPorts(event.target.value)}/><button className="button small" disabled={readOnly || !newCellName.trim()}>새 cell 만들기</button></form></div>}
    <div className="viewport-caption"><span className="live-dot"/>{mode === 'geometric' ? 'Geometric connectivity · 실제 pin 접촉' : 'Explicit pin/net IR · 점선은 net reference guide'}<span>{readOnly ? 'VIEWER · 읽기 전용' : validationError ? validationError : validation ? validation.valid ? '연결 검사 완료' : `${validation.issues?.length || 0} graph issues` : '연결 확인 중…'}</span></div>
    <svg ref={svg} tabIndex={0} viewBox={view} className="schematic-svg" role="img" aria-label="편집 가능한 회로도 / Editable circuit schematic" onContextMenu={event => event.preventDefault()} onKeyDown={event => { if (event.key === 'Escape') { setDraft([]); setTool('select'); } if (event.key === 'Enter' && draft.length >= 2) commitWire(); if (deleteDesignKey(event)) { event.preventDefault(); event.stopPropagation(); deleteSelected(); } if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'd') { event.preventDefault(); copySelected(); } }} onPointerMove={event => { const raw = coords(event); setPointer(snap(raw)); if (!drag) return; if (drag.kind === 'pan') { const transform = svg.current!.getScreenCTM()!.inverse(), dx = event.clientX - (drag.screenStart?.[0] ?? event.clientX), dy = event.clientY - (drag.screenStart?.[1] ?? event.clientY); setPan([drag.original[0] - (transform.a * dx + transform.c * dy), drag.original[1] - (transform.b * dx + transform.d * dy)]); } else setDrag({ ...drag, delta: [Math.round((raw[0] - drag.start[0]) / 10) * 10, Math.round((raw[1] - drag.start[1]) / 10) * 10] }); }} onPointerUp={() => { if (!drag) return; const current = drag; setDrag(null); if (current.kind === 'pan' || same(current.delta, [0, 0])) return; if (current.kind === 'device') send({ type: 'move_device', id: current.id, x: current.original[0] + current.delta[0], y: current.original[1] + current.delta[1] }); else send({ type: current.kind === 'wire' ? 'move_wire' : 'move_junction', id: current.id, dx: current.delta[0], dy: current.delta[1] }); }} onPointerCancel={() => setDrag(null)}>
      <defs><pattern id="schematic-grid" width="10" height="10" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".6" fill="var(--grid-color)"/></pattern></defs>
      <rect x={viewport.left - 100000} y={viewport.top - 100000} width={200000} height={200000} fill="url(#schematic-grid)" onPointerDown={event => { svg.current?.focus(); const raw = coords(event); if (tool === 'pan' || event.button === 1) { event.currentTarget.setPointerCapture(event.pointerId); setDrag({ kind: 'pan', id: '', start: raw, delta: [0, 0], original: pan, screenStart: [event.clientX, event.clientY] }); } else if (tool === 'wire' || tool === 'junction') pointClick(snap(raw)); else { onSelect(null); setSelectedWire(null); setSelectedJunction(null); } }} onDoubleClick={() => { if (tool === 'wire') commitWire(); }}/>
      {mode === 'explicit' && [...inferredNets].map(([net, points]) => <g key={net} className={`schematic-net ${points.some(point => point.device.id === selection) ? 'net-highlight' : ''}`}>{points.slice(1).map(point => { const anchor = points[0], [ax, ay] = position(anchor.device), [bx, by] = position(point.device), a = [ax + anchor.offset[0], ay + anchor.offset[1]], b = [bx + point.offset[0], by + point.offset[1]], middle = (a[0] + b[0]) / 2; return <path key={`${point.device.id}-${point.pin}`} d={`M${a[0]} ${a[1]}H${middle}V${b[1]}H${b[0]}`} fill="none" stroke="currentColor" strokeWidth={1.4} strokeDasharray="4 3" opacity={.6} pointerEvents="none"/>; })}</g>)}
      {wires.map(wire => { const points = wirePoints(wire), highlighted = selectedWire === wire.id || selectedNet?.wire_ids.includes(wire.id), d = points.map(([x, y], index) => `${index ? 'L' : 'M'}${x} ${y}`).join(' '); return <g key={wire.id} className={`drawn-wire ${highlighted ? 'selected' : ''}`}><path d={d} className="wire-visible" pointerEvents="none"/><path d={d} className="wire-hit" onPointerDown={event => { event.stopPropagation(); const raw = coords(event); if (tool === 'wire' || tool === 'junction') { pointClick(snap(raw)); return; } onSelect(null); setSelectedWire(wire.id); setSelectedJunction(null); if (!readOnly && tool === 'select') { event.currentTarget.setPointerCapture(event.pointerId); setDrag({ kind: 'wire', id: wire.id, start: raw, delta: [0, 0], original: [0, 0] }); } }}/>{wire.net && <text x={points[0][0] + 8} y={points[0][1] - 7} className="pin-net" pointerEvents="none">{wire.net}</text>}</g>; })}
      {junctions.map(junction => { const x = junction.x + (drag?.kind === 'junction' && drag.id === junction.id ? drag.delta[0] : 0), y = junction.y + (drag?.kind === 'junction' && drag.id === junction.id ? drag.delta[1] : 0); return <g key={junction.id} className={`drawn-junction ${selectedJunction === junction.id ? 'selected' : ''}`} onPointerDown={event => { event.stopPropagation(); onSelect(null); setSelectedWire(null); setSelectedJunction(junction.id); if (!readOnly && tool === 'select') { event.currentTarget.setPointerCapture(event.pointerId); setDrag({ kind: 'junction', id: junction.id, start: coords(event), delta: [0, 0], original: [x, y] }); } }}><circle cx={x} cy={y} r={10} fill="transparent"/><circle cx={x} cy={y} r={3.8} className="junction-point"/></g>; })}
      {draft.length > 0 && <path d={[...draft, ...(pointer ? bridge(draft[draft.length - 1], pointer) : [])].map(([x, y], index) => `${index ? 'L' : 'M'}${x} ${y}`).join(' ')} className="draft-wire" pointerEvents="none"/>}{pointer && (tool === 'wire' || tool === 'junction') && <circle cx={pointer[0]} cy={pointer[1]} r={5 / zoom} className="wire-snap" pointerEvents="none"/>}
      {devices.map(device => { const [x, y] = position(device); return <g key={device.id} transform={`translate(${x} ${y})`} className={`schematic-device ${device.kind} ${selection === device.id ? 'selected' : ''}`} tabIndex={0} role="button" aria-label={`${device.name} ${device.kind}`} onDoubleClick={() => { if (device.kind === 'block' && device.cell_name) onCellChange(device.cell_name); }} onKeyDown={event => { if (event.key === 'Enter') onSelect(device.id); if (!readOnly && ['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight'].includes(event.key)) { event.preventDefault(); send({ type: 'move_device', id: device.id, x: device.x + (event.key === 'ArrowLeft' ? -10 : event.key === 'ArrowRight' ? 10 : 0), y: device.y + (event.key === 'ArrowUp' ? -10 : event.key === 'ArrowDown' ? 10 : 0) }); } }} onPointerDown={event => { event.stopPropagation(); if (tool === 'wire' || tool === 'junction') { pointClick(snap(coords(event))); return; } onSelect(device.id); setSelectedWire(null); setSelectedJunction(null); if (!readOnly && tool === 'select') { event.currentTarget.setPointerCapture(event.pointerId); setDrag({ kind: 'device', id: device.id, start: coords(event), delta: [0, 0], original: [device.x, device.y] }); } }}>
        <rect className="device-target" x={-62} y={-Math.max(55, device.kind === 'block' ? Object.keys(device.pins).length * 12 + 8 : 55)} width={166} height={Math.max(115, device.kind === 'block' ? Object.keys(device.pins).length * 24 + 16 : 115)} rx={8}/><Symbol device={device}/><text x={61} y={-13} className="device-name">{device.name}</text><text x={61} y={5} className="device-kind">{device.kind === 'block' ? device.cell_name : device.kind.toUpperCase()}</text><text x={61} y={24} className="device-value">{device.parameters.w_um ? `W ${device.parameters.w_um} / L ${device.parameters.l_um} µm` : Object.entries(device.parameters).slice(0, 1).map(([key, value]) => `${key}=${value}`).join('')}</text>
        {Object.entries(device.pins).map(([pin, explicitNet]) => { const [px, py] = pinOffsets(device)[pin] || [0, 0], derivedNet = validation?.connectivity?.nets.find(net => net.pins.some(entry => entry.device_id === device.id && entry.pin === pin))?.name, net = mode === 'geometric' ? derivedNet || '' : explicitNet; return <g key={pin}><circle cx={px} cy={py} r={9} fill="transparent" onPointerDown={event => { if (tool !== 'wire' && tool !== 'junction') return; event.stopPropagation(); pointClick([device.x + px, device.y + py], true); }}/><circle cx={px} cy={py} r={2.8} className={`pin-point ${!net ? 'floating' : ''}`} pointerEvents="none"/><text x={px + 5} y={py - 7} className="pin-net">{net || '○ floating'}</text></g>; })}
      </g>; })}
    </svg>
    {validation && !validation.valid && <div className="schematic-issues">{validation.issues?.slice(0, 3).map((issue, index) => <button key={index} onClick={() => { if (issue.device_id) onSelect(issue.device_id); }}>{issue.code} · {issue.device_id}{issue.pin ? `/${issue.pin}` : ''} · {issue.message}</button>)}</div>}
    <div className="viewport-footnote"><span>{tool === 'wire' ? '핀 클릭 → 중간점 → 끝 핀 클릭 / Enter 완료 · Escape 취소' : '10 unit grid · pin exact snap · Ctrl+D 복제 · wheel zoom'}</span><span>{devices.length} devices · {wires.length} wires · {junctions.length} junctions · crossing ≠ junction</span></div>
  </div>;
}
