import {useEffect,useRef,useState} from 'react';
import {rpc,type Project,type Run} from '@mos/contracts';
import {executeValidation,validationRows} from './validation';
import './validation-panel.css';
export default function ValidationPanel({project,onRun,readOnly=false,shared=false}:{project:Project|null;onRun?:(run:Run)=>void|Promise<void>;readOnly?:boolean;shared?:boolean}){
  const [localRuns,setLocalRuns]=useState<Run[]>([]),[running,setRunning]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const controller=useRef<AbortController|undefined>(undefined),activeRun=useRef<Run|undefined>(undefined),epoch=useRef(0);
  useEffect(()=>{epoch.current++;controller.current?.abort();activeRun.current=undefined;setLocalRuns([]);setRunning(false);setError('');setNotice('');return()=>{epoch.current++;controller.current?.abort();};},[project?.id,project?.revision]);
  const combined=project?{...project,runs:[...project.runs.filter(r=>!localRuns.some(v=>v.id===r.id)),...localRuns]}:null,rows=combined?validationRows(combined):[];
  const disabledReason=shared?'일괄 흐름은 로컬에서 실행하세요. 공유 설계는 기존 개별 실행을 사용할 수 있습니다.':project?.analysis_setup||project?.active_backend==='commercial'?'설정된 GDS·상용 도구는 해당 해석 설정 화면에서 검증하세요.':readOnly?'읽기 전용 설계입니다.':'';
  const start=async()=>{if(!project||disabledReason)return;const token=++epoch.current;controller.current=new AbortController();activeRun.current=undefined;setRunning(true);setError('');setNotice('선택한 revision을 실제로 검증합니다.');try{await executeValidation(project,rpc,controller.current.signal,async run=>{if(epoch.current===token)activeRun.current=run;await onRun?.(run);if(epoch.current===token)setLocalRuns(items=>[...items.filter(v=>v.id!==run.id),run]);});if(epoch.current===token&&!controller.current.signal.aborted)setNotice('5개 검증 단계를 완료했습니다. 표시한 조건의 공개 엔진 결과입니다.');}catch(e){if(epoch.current===token)setError(e instanceof Error?e.message:String(e));}finally{if(epoch.current===token)setRunning(false);}};
  const cancel=async()=>{const token=epoch.current,active=activeRun.current;controller.current?.abort();setNotice('다음 단계를 중단했습니다. 실행 중인 현재 job을 취소합니다.');try{if(active&&['queued','running'].includes(active.execution_status)){const run=await rpc<Run>('job.cancel',{run_id:active.id});await onRun?.(run);if(epoch.current===token)setLocalRuns(items=>[...items.filter(v=>v.id!==run.id),run]);}}catch(e){if(epoch.current===token)setError(e instanceof Error?e.message:String(e));}finally{if(epoch.current===token)setRunning(false);}};
  const download=()=>{if(!combined)return;const report={schema_version:1,checked_at:new Date().toISOString(),project_id:combined.id,revision:combined.revision,pdk_id:combined.pdk_id,testbench:combined.testbench,foundry_signoff:false,stages:rows.map(r=>({stage:r.id,passed:r.passed,stale:r.stale,run:r.run?{id:r.run.id,revision:r.run.revision,execution_status:r.run.execution_status,analysis_result:r.run.analysis_result,freshness:r.run.freshness,analysis_stage:r.run.analysis_stage,measurements:r.run.measurements,parasitics:r.run.parasitics,marker_count:r.run.markers?.length,manifest:r.run.manifest_path,message:r.run.message}:null}))};const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`${combined.cell}-r${combined.revision}-validation.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <section className="validation-panel" data-testid="validation-panel"><h3>회로에서 RC 포함 해석까지</h3><p>회로 해석 → DRC → LVS → PEX → RC 포함 해석 순서로 실행합니다. 실패·미지원·취소·설계 변경이 있으면 다음 단계가 중단됩니다.</p><div className="validation-actions"><button className="button primary" data-testid="validation-start" disabled={!project||running||!!disabledReason} onClick={()=>void start()}>현재 revision 전체 검증</button><button className="button" disabled={!running||readOnly} onClick={()=>void cancel()}>검증 취소</button><button className="button" data-testid="validation-export" disabled={!project} onClick={download}>검증 기록 저장</button><span>{rows.filter(r=>r.passed).length}/5 단계 PASS</span></div>{disabledReason&&<p>{disabledReason}</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    <ol>{rows.map(row=><li key={row.id} data-testid={`validation-stage-${row.id}`} data-pass={row.passed}><strong>{row.label}</strong><span className={`status ${row.passed?'pass':row.stale?'stale':row.run?.analysis_result==='fail'||row.run?.execution_status==='failed'?'fail':'neutral'}`}>{row.stale?'STALE':row.run?`${row.run.execution_status} · ${row.run.analysis_result}`:'미실행'}</span><small>{row.run?`${row.run.id.slice(0,8)} · r${row.run.revision} · ${row.run.tool??'Native engine'}`:'실제 job 결과 필요'}</small>{row.run?.measurements&&<small>{row.run.measurements.corner} · {row.run.measurements.temperature_C} °C · {row.run.measurements.supply_V} V · {row.run.measurements.solver??''}</small>}{row.run?.unit_verification&&<span>{row.run.unit_verification.passed_cases}/{row.run.unit_verification.expected_cases} 실제 입력 통과</span>}{row.run?.message&&<p>{row.run.message}</p>}</li>)}</ol><p>창을 닫으면 현재 job은 계속되며 다음 단계를 시작하지 않습니다. 결과는 프로젝트에 남습니다. 각 단계의 조건과 원본 로그를 확인하세요. 전체 PVT·정적 타이밍·제조 승인은 별도입니다.</p></section>;
}
