import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const folder=path.resolve('packages/viewer/tests/evidence');await mkdir(folder,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1800,height:1100}}),errors=[];
page.on('pageerror',error=>errors.push(error.message));
const base=process.env.REGISTER_VIEWER_TEST_URL??'http://127.0.0.1:29991';
const scene=async()=>JSON.parse(await page.getByTestId('smoke-scene').textContent());
try {
  await page.goto(`${base}?example=fixture&presence=1`);
  await page.waitForFunction(()=>document.querySelector('[data-testid="smoke-scene"]')?.textContent?.startsWith('{'));
  let current=await scene();assert.equal(current.source,'fixture');const start=current;
  const viewer=page.getByTestId('layout-viewer-3d');
  await viewer.getByRole('button',{name:'Polygon / Cell 도구',exact:true}).click();
  const panel=viewer.getByLabel('고급 정수 레이아웃 도구',{exact:true});
  const choose=async(tool)=>panel.getByLabel('레이아웃 도구 종류',{exact:true}).selectOption(tool);
  const apply=async()=>{
    const revision=(await scene()).revision;
    await panel.getByRole('button',{name:'고급 명령 적용',exact:true}).click();
    await page.waitForFunction(revision=>JSON.parse(document.querySelector('[data-testid="smoke-scene"]').textContent).revision>revision,revision,{timeout:30000});
    current=await scene();
  };
  await choose('cell');await panel.getByLabel('새 Cell 이름',{exact:true}).fill('viewer_tools_child');await apply();
  assert.ok(current.cells.some(cell=>cell.name==='viewer_tools_child'));
  await choose('polygon');await panel.getByLabel('편집 cell',{exact:true}).selectOption('viewer_tools_child');
  await panel.getByLabel('Layer',{exact:true}).selectOption('68/20');
  await panel.getByLabel('꼭짓점 X,Y (줄마다 DBU)',{exact:true}).fill('0,0\n1000,0\n1000,1000\n0,1000');
  await panel.getByLabel('Holes JSON (선택)',{exact:true}).fill('[[["200","200"],["800","200"],["800","800"],["200","800"]]]');
  await panel.getByLabel('연결 Net (선택)',{exact:true}).fill('VIEWER_NET');await apply();
  assert.equal(current.shapes.length,start.shapes.length,'Uninstantiated child geometry is not invented in the top view');
  await choose('label');await panel.getByLabel('Label text',{exact:true}).fill('REAL_CHILD_LABEL');
  await panel.getByLabel('배치 X',{exact:true}).fill('500');await panel.getByLabel('배치 Y',{exact:true}).fill('500');await apply();
  await choose('pin');await panel.getByLabel('Layer',{exact:true}).selectOption('68/20');
  await panel.getByLabel('Pin 이름',{exact:true}).fill('REAL_PIN');await panel.getByLabel('Pin X₂',{exact:true}).fill('700');await panel.getByLabel('Pin Y₂',{exact:true}).fill('700');await apply();
  await choose('path');await panel.getByLabel('Layer',{exact:true}).selectOption('68/20');
  await panel.getByLabel('꼭짓점 X,Y (줄마다 DBU)',{exact:true}).fill('1000,500\n2000,500\n2000,1500');
  await panel.getByLabel('Path 폭 DBU',{exact:true}).fill('100');await apply();
  await choose('instance');await panel.getByLabel('편집 cell',{exact:true}).selectOption('fixture');
  await panel.getByLabel('원본 Cell',{exact:true}).selectOption('viewer_tools_child');
  await panel.getByLabel('배치 X',{exact:true}).fill('7000');await panel.getByLabel('배치 Y',{exact:true}).fill('3000');
  await panel.getByLabel('Array 열',{exact:true}).fill('2');await panel.getByLabel('Array 행',{exact:true}).fill('3');
  await panel.getByLabel('Array ΔX DBU',{exact:true}).fill('3000');await panel.getByLabel('Array ΔY DBU',{exact:true}).fill('3000');
  await panel.getByLabel('절대 회전',{exact:true}).selectOption('90');await panel.getByLabel('Mirror X축 (절대)',{exact:true}).check();await apply();
  const instance=current.instances.find(instance=>instance.cell_name==='viewer_tools_child');assert.ok(instance);
  assert.deepEqual(instance.array,{columns:2,rows:3,dx:'3000',dy:'3000'});assert.equal(instance.rotation,90);assert.equal(instance.mirror,true);
  assert.equal(current.shapes.filter(shape=>shape.holes?.length).length,6);
  assert.equal(current.labels.filter(label=>label.text==='REAL_CHILD_LABEL').length,6);
  assert.equal(current.pins.filter(pin=>pin.name==='REAL_PIN').length,6);
  const stableIds=current.shapes.filter(shape=>shape.cell_path.includes('viewer_tools_child')).map(shape=>shape.id).sort();
  assert.equal(new Set(stableIds).size,stableIds.length);
  await choose('transform');await panel.getByLabel('Instance ID',{exact:true}).selectOption(instance.id);
  await panel.getByLabel('Instance ΔX',{exact:true}).fill('100');await panel.getByLabel('Instance ΔY',{exact:true}).fill('200');
  await panel.getByLabel('절대 회전',{exact:true}).selectOption('180');await panel.getByLabel('Mirror X축 (절대)',{exact:true}).uncheck();await apply();
  const moved=current.instances.find(item=>item.id===instance.id);assert.equal(moved.rotation,180);assert.equal(moved.mirror,false);
  assert.deepEqual(moved.position,['7100','3200']);
  assert.deepEqual(current.shapes.filter(shape=>shape.cell_path.includes('viewer_tools_child')).map(shape=>shape.id).sort(),stableIds,'Instance transforms retain every occurrence ID');
  const sourceCount=current.shapes.length;
  await panel.getByLabel('Instance 작업',{exact:true}).selectOption('copy');await apply();
  const copied=current.instances.find(item=>item.cell_name==='viewer_tools_child'&&item.id!==instance.id);assert.ok(copied);
  assert.equal(current.shapes.length-start.shapes.length,2*(sourceCount-start.shapes.length));
  await panel.getByLabel('Instance ID',{exact:true}).selectOption(copied.id);await panel.getByLabel('Instance 작업',{exact:true}).selectOption('delete');await apply();
  assert.equal(current.shapes.length,sourceCount);assert.ok(!current.instances.some(item=>item.id===copied.id));
  await panel.getByRole('button',{name:'도구 닫기',exact:true}).click();
  await viewer.getByRole('button',{name:'맞춤',exact:true}).click();
  await page.waitForTimeout(300);assert.ok(Number(await viewer.locator('canvas').getAttribute('data-annotation-count'))>=12,'Actual labels and pins produce rendered annotations');assert.equal(await viewer.locator('canvas').getAttribute('data-peer-outline-count'),'1');assert.ok(await viewer.locator('.mos-viewer-peer').isVisible(),'Decimal DBU remote cursor projects into the real scene');
  await page.screenshot({path:path.join(folder,'advanced-tools.png'),fullPage:true});
  const final=current;
  await page.goto(`${base}?example=fixture&readonly=1`);await page.waitForFunction(()=>document.querySelector('[data-testid="smoke-scene"]')?.textContent?.startsWith('{'));
  for(const name of ['XY 이동','Box 추가','배선 추가','Polygon / Cell 도구'])assert.equal(await page.getByTestId('layout-viewer-3d').getByRole('button',{name,exact:true}).isDisabled(),true);
  assert.equal(await page.getByTestId('layout-viewer-3d').getByRole('button',{name:'위',exact:true}).isDisabled(),false);
  assert.deepEqual(errors,[]);
  const report={checked_at:new Date().toISOString(),authority:'Actual KLayout worker commands, snapshots and hierarchy geometry',project_id:final.project_id,revision:final.revision,source:final.source,
    shape_count:final.shapes.length,instance_count:final.instances.length,checks:['add editable cell','polygon with actual holes','path','label','pin','2x3 array with absolute rotation and mirror','transformed occurrence IDs remain stable','copy instance','delete instance','real annotation rendering','remote decimal DBU cursor overlay','read-only mutation tools disabled while camera works'],errors};
  await writeFile(path.join(folder,'advanced-tools.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}catch(error){console.log({failure:error.message,status:await page.locator('.mos-viewer-status').allTextContents(),alerts:await page.getByRole('alert').allTextContents()});throw error;}finally{await browser.close();}

