import {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';
import {StdioServerTransport} from '@modelcontextprotocol/sdk/server/stdio.js';
import {z} from 'zod/v4';
import {runtimeConfig,workerRpc} from './runtime.mjs';
const workspace=process.env.MOS_WORKSPACE||process.cwd();
const config=await runtimeConfig(workspace);
const server=new McpServer({name:'register-eda',version:'0.12.0'});
const id=z.string().regex(/^[a-f0-9]{32}$/);
const decimal=z.string().regex(/^-?\d{1,18}$/);
const point=z.tuple([decimal,decimal]);
const operation=z.discriminatedUnion('type',[
  z.object({type:z.literal('add_box'),layer_id:z.string().max(100),box:z.tuple([decimal,decimal,decimal,decimal]),net:z.string().max(100).optional()}),
  z.object({type:z.literal('move_shape'),id:z.string().max(300),dx:decimal,dy:decimal}),
  z.object({type:z.literal('add_polygon'),layer_id:z.string().max(100),polygon:z.array(point).min(3).max(256),holes:z.array(z.array(point).min(3).max(256)).max(16).optional()}),
  z.object({type:z.literal('add_route'),layer_id:z.string().max(100),points:z.array(point).min(2).max(64),width:decimal,net:z.string().max(100).optional()}),
  z.object({type:z.literal('update_device'),id:z.string().max(100),parameters:z.object({w_um:z.number().min(.42).max(100).optional(),l_um:z.number().min(.15).max(20).optional()}).strict()}),
  z.object({type:z.enum(['undo','redo'])})
]);
let submissions=0;
async function native(method,params={},cost=0){if(submissions+cost>32)throw new Error('MCP session native job budget exhausted (32). Start a new explicitly authorized session to continue.');submissions+=cost;const value=await workerRpc(config,method,params);if(!value.ok)throw Object.assign(new Error(value.error.message),{code:value.error.code});return value.result;}
function tool(name,description,inputSchema,callback,{readOnly=true,idempotent=readOnly}={}){server.registerTool(name,{description,inputSchema,annotations:{readOnlyHint:readOnly,destructiveHint:false,idempotentHint:idempotent,openWorldHint:false}},async args=>{try{const output=await callback(args);return {content:[{type:'text',text:JSON.stringify(output)}],structuredContent:{result:output}};}catch(e){return {isError:true,content:[{type:'text',text:JSON.stringify({code:e.code||'AGENT_BOUNDARY',message:e.message})}]};}});}
tool('register_doctor','Actual native tool/PDK availability and provenance. No provider API calls.',{},()=>native('toolchain.doctor'));
tool('register_projects','List this explicitly selected local workspace projects.',{},()=>native('project.list'));
tool('register_snapshot','Read schematic, integer scene subset and actual run references of a project.',{project_id:id,max_shapes:z.number().int().min(1).max(2000).default(500)},async p=>({project:await native('project.snapshot',{project_id:p.project_id}),scene:await native('view.get_scene',p)}));
tool('register_create','Create a real supported public-PDK example or a clearly marked geometry fixture.',{name:z.string().min(1).max(80),example:z.enum(['mosfet','inverter','wire','fixture'])},p=>native('project.create',p),{readOnly:false});
tool('register_layout_command','Validated reversible DBU transaction. Revision is mandatory; no shell, raw GDS bytes, PDK changes or fabricated scores.',{project_id:id,expected_revision:z.number().int().positive(),command_id:z.string().min(8).max(120),command:operation},p=>native('layout.apply_command',p),{readOnly:false});
tool('register_simulate','Submit actual ngspice analysis with a fixed bounded testbench.',{project_id:id,expected_revision:z.number().int().positive(),command_id:z.string().min(8).max(120),analysis:z.enum(['op','dc','ac','tran']),corner:z.enum(['tt','ff','ss']).default('tt'),temperature_C:z.number().min(-40).max(125).default(27),post_layout:z.boolean().default(false)},p=>native('simulation.run',p,1),{readOnly:false});
tool('register_verify','Submit real Magic DRC, Netgen LVS or RC extraction. Each remains an independent job.',{project_id:id,expected_revision:z.number().int().positive(),command_id:z.string().min(8).max(120),kind:z.enum(['drc','lvs','pex'])},({kind,...p})=>native({drc:'verification.run_drc',lvs:'verification.run_lvs',pex:'extraction.run_pex'}[kind],p,1),{readOnly:false});
tool('register_job','Read actual execution/result/freshness, raw measurements and manifest references. Failed/canceled is never PASS.',{run_id:id},p=>native('job.status',p));
tool('register_cancel','Cancel a submitted native job without deleting its failure/cancellation evidence.',{run_id:id},p=>native('job.cancel',p),{readOnly:false});
const receipt=z.string().uuid();
const hash=z.string().regex(/^[a-f0-9]{64}$/);
const route=z.object({layer_id:z.string().min(1).max(100),start:point,end:point,width:decimal.optional(),net:z.string().max(100).optional(),order:z.enum(['x-first','y-first']).optional(),points:z.array(point).min(2).max(16).optional(),rule_fingerprint:hash.optional()}).strict();
tool('register_design_catalog','Read available connected circuit templates, analyses and actual physical-layout limitations.',{},()=>native('design.catalog'));
tool('register_semiconductor_catalog','Read semiconductor starting presets, exact analysis conditions, official PDK characteristics and actual installed adapter readiness. Only connected technologies can create projects.',{},()=>native('starter.catalog'));
tool('register_semiconductor_start','Create a new editable semiconductor starter with authoritative circuit, physical-layout scope and saved operating conditions. Creation is idempotent and does not claim DRC/LVS or run simulation.',{preset_id:z.string().min(1).max(80),mode:z.enum(['nominal','slow_hot','fast_cold']).optional(),name:z.string().min(1).max(128).optional(),command_id:receipt},p=>native('starter.create',p),{readOnly:false});
tool('register_design_template','Create a new validated connected circuit template in this local workspace. Physical layout is explicitly ungenerated unless a supported core is requested.',{template_id:z.string().min(1).max(80),name:z.string().min(1).max(80).optional(),parameters:z.record(z.string().max(80),z.number().finite()).optional(),physical_core:z.boolean().optional(),command_id:receipt},p=>native('design.create_template',p),{readOnly:false});
tool('register_route_rules','Read installed PDK rule values, resource hashes and conservative single-layer routing scope.',{project_id:id},p=>native('design.routing_rules',p));
tool('register_route_preview','Preview a bounded Manhattan route against exact current geometry and installed PDK rules. No geometry mutation.',{project_id:id,...route.shape},p=>native('design.route_preview',p));
tool('register_route_search','Find bounded native-checked obstacle detours on metal1. Advisory preview; no global autorouting or verification claim.',{project_id:id,...route.omit({points:true}).shape},p=>native('design.route_search',p));
tool('register_route_apply','Atomically apply a preview only when project revision, input hash and actual PDK fingerprint still match. Real DRC remains required.',{project_id:id,expected_revision:z.number().int().positive(),command_id:receipt,preview:route,preview_hash:hash,rule_fingerprint:hash},p=>native('design.route_apply',p),{readOnly:false});
tool('register_connectivity','Read actual schematic pin/net connections, design issues and explicit layout binding. Net tags alone do not prove electrical correspondence.',{project_id:id,cell_name:z.string().max(100).optional()},p=>native('design.connectivity',p));
const supply=z.discriminatedUnion('kind',[
  z.object({kind:z.literal('testbench'),source_names:z.array(z.string().regex(/^[A-Za-z_][A-Za-z0-9_]*$/)).min(1).max(16)}).strict(),
  z.object({kind:z.literal('device'),device_id:z.string().min(1).max(100)}).strict(),
  z.object({kind:z.literal('port'),name:z.string().regex(/^[A-Za-z_][A-Za-z0-9_]*$/)}).strict()
]);
const pvtConfig=z.object({analysis:z.enum(['op','dc','ac','tran']),corners:z.array(z.enum(['tt','ff','ss'])).min(1).max(3),temperatures_C:z.array(z.number().min(-40).max(125)).min(1).max(32),supplies_V:z.array(z.number().min(.1).max(1.8)).min(1).max(32),supply,metrics:z.array(z.object({name:z.string().min(1).max(80),source:z.enum(['measurement','waveform','branch']),key:z.string().min(1).max(256),reduction:z.enum(['min','max','mean','last']).optional(),absolute:z.boolean().optional()}).strict()).min(1).max(16),constraints:z.array(z.object({metric:z.string().min(1).max(80),op:z.enum(['<=','>=']),value:z.number().finite()}).strict()).max(16).optional(),settings:z.record(z.string().max(80),z.union([z.number().finite(),z.string().max(80),z.boolean()])).optional(),wall_time_s:z.number().int().min(60).max(1800).optional(),point_timeout_s:z.number().int().min(5).max(300).optional(),max_parallel:z.union([z.literal(1),z.literal(2)]).optional()}).strict();
tool('register_pvt_sources','Read supply bindings and supported corners/analyses from the actual project and model profile.',{project_id:id},p=>native('pvt.sources',p));
tool('register_pvt_create','Save an immutable, bounded PVT condition table. Validates actual supply binding and numeric metrics; does not launch engines.',{project_id:id,expected_revision:z.number().int().positive(),command_id:receipt,config:pvtConfig},p=>native('pvt.create',p),{readOnly:false});
tool('register_pvt_start','Run the saved immutable PVT conditions using actual ngspice jobs. All native points count against this session budget.',{project_id:id,study_id:id,expected_revision:z.number().int().positive(),command_id:receipt},async p=>{const study=await native('pvt.status',{project_id:p.project_id,study_id:p.study_id});return native('pvt.start',p,study.execution_status==='created'?study.points.length:0);},{readOnly:false});
tool('register_pvt_study','Read per-point native run references, signed measured metrics, constraints, worst conditions and freshness.',{project_id:id,study_id:id},p=>native('pvt.status',p));
tool('register_pvt_list','List saved PVT studies for exactly this project.',{project_id:id},p=>native('pvt.list',p));
tool('register_pvt_cancel','Cancel a PVT study and its active native points, preserving actual run and failure evidence.',{project_id:id,study_id:id,command_id:receipt},p=>native('pvt.cancel',p),{readOnly:false});
const backendId=z.string().regex(/^[A-Za-z_][A-Za-z0-9_.:-]{0,127}$/);
const backendOperation=z.enum(['simulation','drc','lvs','pex','layout_export','netlist_export','implementation']);
tool('register_database_sources','List explicitly registered local native database readers and their actual capability status. No source registration, filesystem paths, scripts or license values.',{},async()=>({catalog:await native('database.catalog'),sources:await native('database.list_sources')}));
tool('register_database_probe','Read availability and fingerprint evidence for an operator-registered native database source. An absent vendor remains unavailable.',{source_id:backendId},p=>native('database.probe',p));
tool('register_database_cells','List bounded library/cell/view entries through an existing read-only native source. Actual native query budget applies.',{source_id:backendId},p=>native('database.list_cells',p,1),{idempotent:false});
tool('register_database_read','Read a selected native cell through the fixed operator reader, preserving source hashes and immutable receipt. No arbitrary command code or raw binary guesses.',{source_id:backendId,cell:z.string().min(1).max(256),view:z.string().min(1).max(128).optional()},p=>native('database.read',p,1),{idempotent:false});
tool('register_database_import','Apply a validated read receipt in a reversible project revision. Source/graph integrity, revision and receipt checks are mandatory.',{project_id:id,read_id:id,expected_revision:z.number().int().positive(),command_id:z.string().min(8).max(120)},p=>native('database.import',p),{readOnly:false});
tool('register_backend_catalog','Read native tool families and safe installed profile metadata. Vendor execution is unverified until independently tested; no private recipes/credentials.',{},()=>native('backend.catalog'));
tool('register_backend_validate','Validate a preinstalled operator profile and return safe availability/hash evidence. Cannot register recipes, change paths or submit credentials.',{profile_id:backendId},p=>native('backend.validate',p));
tool('register_backend_configure','Save typed inputs for an existing operator-owned native recipe in a reversible project revision. No shell, script fragments, raw model paths or credential values.',{
  project_id:id,expected_revision:z.number().int().nonnegative(),command_id:z.string().min(8).max(120),
  settings:z.object({profile_id:backendId,profile_hash:z.string().regex(/^[a-f0-9]{64}$/),operation:backendOperation,top_cell:backendId,
    parameters:z.record(backendId,z.union([z.number().finite(),z.boolean(),z.string().max(80)])).default({}),netlist_text:z.string().max(256*1024).optional()}).strict()
},p=>native('backend.configure',p),{readOnly:false});
tool('register_backend_run','Submit the saved operator recipe with exact revision/receipt. Native job budget applies. Installed license/site flow required; no open-source fallback or fabricated result.',{
  project_id:id,expected_revision:z.number().int().nonnegative(),command_id:z.string().min(8).max(120),operation:backendOperation.optional()
},p=>native('backend.run',p,1),{readOnly:false});
tool('register_optimize','Start seeded, physically gated MOS search; every trial must pass real PCell/DRC/LVS and ngspice. No LLM-generated metrics.',{project_id:id,algorithm:z.enum(['grid','random','tpe']),min_w_um:z.number().min(.42).max(100),max_w_um:z.number().min(.42).max(100),trial_budget:z.number().int().min(1).max(8),seed:z.number().int().min(0).max(2147483647),objective:z.enum(['Id_max','Id_min','area_um2','power_W']),goal:z.enum(['minimize','maximize'])},async p=>{if(p.max_w_um<p.min_w_um)throw new Error('Parameter bounds reversed.');if(submissions+p.trial_budget*3>32)throw new Error('Native job budget would be exceeded.');submissions+=p.trial_budget*3;const e=await native('experiment.create',{project_id:p.project_id,algorithm:p.algorithm,variables:[{device_id:'mn1',parameter:'w_um',min:p.min_w_um,max:p.max_w_um,steps:Math.max(2,p.trial_budget)}],objective:{metric:p.objective,goal:p.goal},trial_budget:p.trial_budget,seed:p.seed});return native('experiment.evaluate',{experiment_id:e.id});},{readOnly:false});
tool('register_experiment','Actual candidate feasibility, provenance and measured ranking.',{experiment_id:id},async p=>({experiment:await native('experiment.status',p),comparison:await native('experiment.compare',p)}));
tool('register_experiment_cancel','Stop the bounded search and cancel its active native run while preserving trial evidence.',{experiment_id:id},p=>native('experiment.cancel',p),{readOnly:false});
const instruction=z.object({op:z.enum(['LOAD','ADD','AND','XOR']),value:z.number().int().min(0).max(65535)}).strict();
const hierarchy=z.object({project_id:id,mode:z.enum(['place','wrap']),source_project_id:id.optional(),source_cell:z.string().max(96).optional(),target_cell:z.string().max(96).optional(),namespace:z.string().max(96).optional(),pins:z.record(z.string(),z.string().max(100)).optional(),position:point.optional(),rotation:z.union([z.literal(0),z.literal(90),z.literal(180),z.literal(270)]).optional(),mirror:z.boolean().optional(),scope:z.enum(['both','schematic','layout']).optional(),parent_name:z.string().max(96).optional()}).strict();
tool('register_digital_catalog','Read actual SKY130 adder/CPU circuits, ports and native validation cases.',{},()=>native('digital.catalog'));
tool('register_digital_create','Create editable transistor full adder, ripple adder or clocked 4/16-bit accumulator CPU (4-bit PC) with 16-word ROM. Reference physical layout is optional; not manufacturing signoff.',{kind:z.enum(['full_adder','adder4','cpu4','adder16','cpu16']),name:z.string().min(1).max(128),physical:z.boolean().default(true),program:z.array(instruction).length(16).optional(),cycles:z.number().int().min(16).max(64).optional(),period_ns:z.number().min(20).max(1000).optional(),command_id:receipt},p=>native('digital.create',p),{readOnly:false});
tool('register_hierarchy_sources','Search compact saved native hierarchy sources without waveform payloads.',{query:z.string().max(128).default('')},p=>native('hierarchy.sources',p));
tool('register_hierarchy_preview','Read complete before/after native layout, pin mappings, same-layer overlaps and stale-run impact. No mutation. Do not apply until the human has seen and approved this exact preview.',{request:hierarchy},p=>native('hierarchy.preview',p.request));
tool('register_hierarchy_apply','Apply the exact human-approved hierarchy preview, revision locked and undoable. approved:true must follow explicit human approval of the displayed impact.',{project_id:id,request:hierarchy,preview_hash:hash,approved:z.literal(true),expected_revision:z.number().int().positive(),command_id:receipt},p=>native('hierarchy.apply',p),{readOnly:false});
await server.connect(new StdioServerTransport());
