import { chromium } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';

await mkdir('packages/ui/qa', { recursive: true });
const browser = await chromium.launch({ headless: true, args: ['--use-angle=swiftshader', '--enable-webgl'] });
const page = await browser.newPage({ viewport: { width: 1600, height: 1050 } });
const errors = []; page.on('pageerror', error => errors.push(error.message));
await page.routeWebSocket(/ws:\/\/127\.0\.0\.1:5173/, socket => socket.close());
const call = (method, params = {}) => page.evaluate(async ({ method, params }) => { const { rpc } = await import('/packages/contracts/src/index.ts'); return rpc(method, { project_id: document.querySelector('.app-shell').dataset.projectId, ...params }); }, { method, params });
const until = async (operation, message, limit = 180) => { for (let attempt = 0; attempt < limit; attempt++) { if (await operation()) return; await page.waitForTimeout(500); } throw new Error(message); };
const close = () => page.getByRole('dialog').getByRole('button', { name: '닫기', exact: true }).click();
try {
  await page.goto('http://127.0.0.1:5173'); await page.getByTestId('app-ready').waitFor({ timeout: 90000 });
  await page.getByRole('button', { name: '새 프로젝트', exact: true }).first().click(); await page.getByTestId('project-example-select').selectOption('mosfet'); await page.getByTestId('project-name').fill(`UI optimizer ${Date.now()}`); await page.getByTestId('project-create').click();
  await page.getByRole('dialog').waitFor({ state: 'detached', timeout: 45000 }); await until(async () => (await call('project.snapshot')).example === 'mosfet', 'MOS source creation'); await page.getByTestId('tab-schematic').click();
  await page.locator('.schematic-editor-toolbar').getByRole('button', { name: 'Testbench', exact: true }).click(); await page.getByTestId('testbench-analysis').selectOption('op'); await page.getByTestId('testbench-corner').selectOption('ff'); await page.getByTestId('testbench-temperature_C').fill('125'); await page.getByTestId('testbench-supply_V').fill('1.2'); await page.getByTestId('testbench-apply').click(); await page.getByText('worker가 설정을 저장했습니다.', { exact: false }).waitFor();
  const persistedTestbench = (await call('project.snapshot')).testbench; assert.equal(persistedTestbench.corner, 'ff'); assert.equal(persistedTestbench.temperature_C, 125); assert.equal(persistedTestbench.supply_V, 1.2); await close();
  await page.getByRole('button', { name: 'Xschem', exact: true }).click(); await page.locator('.artifact-json').waitFor({ timeout: 45000 }); const xschemArtifact = await page.locator('.artifact-json').innerText(); assert.ok(xschemArtifact.includes('xschem')); await close();
  await page.getByTestId('tab-simulation').click(); await page.getByLabel('Netlister', { exact: false }).selectOption('xschem'); await page.getByRole('button', { name: 'Run analysis', exact: true }).click();
  await until(async () => (await call('project.snapshot')).runs.some(run => run.kind === 'simulation' && run.execution_status === 'completed'), 'actual Xschem simulation'); const simulation = (await call('project.snapshot')).runs.at(-1); assert.equal(simulation.analysis_result, 'pass'); assert.ok(simulation.artifacts.xschem_schematic && simulation.artifacts.xschem_manifest, 'actual Xschem source and bridge manifest must exist'); assert.ok(simulation.measurements.gm > 0, 'actual BSIM gm must exist');
  await page.getByTestId('open-experiments').click(); await page.getByTestId('experiment-budget').fill('2'); await page.getByLabel('w_um minimum').fill('0.65'); await page.getByLabel('w_um maximum').fill('0.75'); await page.locator('.experiment-variables input[type=number]').nth(2).fill('2');
  await page.getByTestId('experiment-run').click(); await page.locator('.experiment-results-heading code').waitFor({ timeout: 45000 }); const experimentId = await page.locator('.experiment-results-heading code').innerText();
  await until(async () => ['completed', 'failed', 'canceled'].includes((await call('experiment.status', { experiment_id: experimentId })).execution_status), 'actual candidate evaluation', 600);
  const experiment = await call('experiment.status', { experiment_id: experimentId }); assert.equal(experiment.execution_status, 'completed'); assert.equal(experiment.trials.length, 2); assert.ok(experiment.trials.some(trial => trial.feasible && typeof trial.score === 'number'));
  for (const trial of experiment.trials.filter(trial => trial.feasible)) { assert.ok(trial.runs.every(run => run.analysis_result === 'pass')); assert.ok(trial.metrics.Id_max > 0); }
  await page.getByRole('button', { name: '실제 feasible 후보 순위', exact: true }).click(); await page.getByText('검증을 통과한 실제 후보 순위', { exact: true }).waitFor(); await page.screenshot({ path: 'packages/ui/qa/register-optimization.png' });
  await close(); await page.getByTestId('open-experiments').click(); await page.getByLabel('Saved experiments').selectOption(experimentId); await page.locator('.experiment-trial-table tbody tr').first().waitFor(); assert.equal(await page.locator('.experiment-trial-table tbody tr').count(), 2);
  assert.deepEqual(errors, []); const evidence = { project_id: experiment.project_id, source_revision: experiment.source_revision, persisted_testbench: persistedTestbench, actual_xschem_op: { run_id: simulation.id, result: simulation.analysis_result, measurements: simulation.measurements }, experiment_id: experimentId, algorithm: experiment.algorithm, trials: experiment.trials.map(trial => ({ id: trial.id, feasible: trial.feasible, score: trial.score, metrics: trial.metrics, gates: trial.runs.map(run => ({ kind: run.kind, result: run.analysis_result })) })), saved_experiment_reopened: true, browser_errors: errors };
  await writeFile('packages/ui/qa/optimization-evidence.json', JSON.stringify(evidence, null, 2)); process.stdout.write(JSON.stringify(evidence));
} catch (cause) { await page.screenshot({ path: 'packages/ui/qa/optimization-failure.png' }); process.stderr.write(JSON.stringify({ errors, inline_errors: await page.locator('.inline-error').allTextContents(), worker_errors: await page.locator('.error-banner').allTextContents() })); throw cause; } finally { await browser.close(); }
